// Alfa Romeo — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Alfa Romeo',
  cars: [
    { model: 'Giulia', gen: '952', years: [2016, 0], bodies: ['saloon'], segment: 'compact-exec',
      priceNew: [32000, 48000], used: [14000, 38000], accel: 5.2, power: [200, 280], top: 149,
      fuels: ['petrol', 'diesel'], mpg: 47, ev: null, seats: 5, doors: 4, boot: 480, len: 4643, kg: 1429,
      mpy: 9000, ncap: [5, 2016], onSale: true, halo: false,
      g: { build: 72, drive: 90, practicality: 72, value: 78, design: 90, running: 66 },
      verdict: 'The best-steering saloon of its generation, wrapped in the prettiest body. Buy with your heart — it’s right this time.',
      issues: ['Electronics niggle more than Germans', 'Dealer network thin'],
      buy: 'Veloce 280 — the sweet spot between sense and Quadrifoglio.',
      tags: ['drivers-car', 'head-turner', 'sleek', 'left-field', 'b-road-hero', 'future-classic'],
      rivals: ['bmw-3-series-g20', 'jaguar-xe-x760', 'mercedes-benz-c-class-w206'] },

    { model: 'Giulia Quadrifoglio', gen: '952', years: [2016, 0], bodies: ['saloon'], segment: 'super-coupe',
      priceNew: [62000, 78000], used: [32000, 60000], accel: 3.9, power: [510, 520], top: 191,
      fuels: ['petrol'], mpg: 27, ev: null, seats: 5, doors: 4, boot: 480, len: 4643, kg: 1580,
      mpy: 5500, ncap: [5, 2016], onSale: true, halo: false,
      g: { build: 74, drive: 95, practicality: 70, value: 76, design: 92, running: 40 },
      verdict: 'A Ferrari-derived V6 in the most beautiful saloon on sale. More alive than an M3 — history will canonise it.',
      issues: ['Residuals soft (buy used, smile)', 'Some early electrical gremlins'],
      buy: '2020-on facelift, Verde Montreale if you can find one.',
      tags: ['drivers-car', 'v8-soundtrack', 'head-turner', 'future-classic', 'b-road-hero', 'autobahn-stormer'],
      rivals: ['bmw-m3-g80', 'mercedes-amg-c63-w205', 'audi-rs4-b9'] },

    { model: 'Stelvio', gen: '949', years: [2017, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [38000, 52000], used: [16000, 40000], accel: 3.8, power: [200, 510], top: 176,
      fuels: ['petrol', 'diesel'], mpg: 45, ev: null, seats: 5, doors: 5, boot: 525, len: 4687, kg: 1660,
      mpy: 9500, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 72, drive: 86, practicality: 78, value: 76, design: 82, running: 60 },
      verdict: 'The family SUV that actually steers — Giulia bones on stilts. The Quadrifoglio version is gloriously unhinged.',
      issues: ['Infotainment behind rivals', 'Trim squeaks'],
      buy: 'Veloce 280 — pace and panache for X3 money used.',
      tags: ['drivers-car', 'head-turner', 'school-run', 'left-field', 'sleek'],
      rivals: ['porsche-macan-95b', 'bmw-x3-g01', 'jaguar-f-pace-x761'] },

    { model: 'Giulietta', gen: '940', years: [2010, 2020], bodies: ['hatch'], segment: 'family-hatch',
      priceNew: [18000, 29000], used: [5000, 13000], accel: 6.0, power: [105, 240], top: 152,
      fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 350, len: 4351, kg: 1355,
      mpy: 8500, ncap: [5, 2010], onSale: false, halo: false,
      g: { build: 68, drive: 72, practicality: 68, value: 76, design: 80, running: 74 },
      verdict: 'The pretty Golf alternative that Italy kept honest. Cloverleaf QV is a warm memory of TCT-flappy fun.',
      issues: ['TCT gearbox history essential', 'Electrics age Italian-ly'],
      buy: '1.75 TBi Veloce, or a tidy 2.0 JTDm for the commute.',
      tags: ['head-turner', 'left-field', 'bargain-hero', 'sleek'],
      rivals: ['volkswagen-golf-mk7', 'seat-leon-5f', 'mazda-3-bm'] },

    { model: '4C', gen: '960', years: [2013, 2020], bodies: ['coupe', 'convertible'], segment: 'sports',
      priceNew: [45000, 60000], used: [38000, 55000], accel: 4.5, power: [240, 240], top: 160,
      fuels: ['petrol'], mpg: 40, ev: null, seats: 2, doors: 2, boot: 110, len: 3989, kg: 895,
      mpy: 3000, ncap: null, onSale: false, halo: false,
      g: { build: 70, drive: 84, practicality: 22, value: 68, design: 92, running: 62 },
      verdict: 'A carbon-tub baby Ferrari with go-kart steering and zero filter. Exhausting, flawed, unforgettable — a keeper.',
      issues: ['No power steering — genuinely heavy parking', 'Turbo four sounds industrial'],
      buy: 'Coupé with the sports exhaust, low miles — collectors circling.',
      tags: ['lightweight', 'future-classic', 'head-turner', 'track-day', 'analogue-joy', 'left-field'],
      rivals: ['alpine-a110-as1', 'lotus-elise-s3', 'porsche-718-cayman-982'] },

    { model: 'Tonale', gen: '965', years: [2022, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [32000, 45000], used: [18000, 34000], accel: 6.2, power: [130, 280], top: 128,
      fuels: ['hybrid', 'phev'], mpg: 49, ev: 38, seats: 5, doors: 5, boot: 500, len: 4528, kg: 1550,
      mpy: 9000, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 74, drive: 68, practicality: 76, value: 72, design: 80, running: 76 },
      verdict: 'The volume Alfa: pretty face, decent hybrid, dynamics a shade softer than the badge promises. Heart says yes anyway.',
      issues: ['Hybrid box hesitates', 'Residuals watch'],
      buy: 'PHEV Q4 Veloce — 38 e-miles of stylish school run.',
      tags: ['head-turner', 'school-run', 'sleek', 'left-field'],
      rivals: ['bmw-x1-u11', 'audi-q3-f3', 'volvo-xc40-p8'] },

    { model: '159', gen: '939', years: [2005, 2011], bodies: ['saloon', 'estate'], segment: 'compact-exec',
      priceNew: [20000, 30000], used: [2000, 6000], accel: 7.0, power: [120, 260], top: 148,
      fuels: ['petrol', 'diesel'], mpg: 42, ev: null, seats: 5, doors: 4, boot: 405, len: 4660, kg: 1505,
      mpy: 7500, ncap: [5, 2006], onSale: false, halo: false,
      g: { build: 64, drive: 68, practicality: 70, value: 74, design: 88, running: 62 },
      verdict: 'Possibly the best-looking saloon of the 2000s, yours for scrap money. The Sportwagon is an Italian oil painting.',
      issues: ['Front suspension arms a service item', 'Heavy nose, heavier depreciation (done now)'],
      buy: '2.4 JTDm Ti Sportwagon — the £4k design statement.',
      tags: ['head-turner', 'bargain-hero', 'modern-classic', 'left-field', 'sleek'],
      rivals: ['bmw-3-series-e90', 'audi-a4-b8', 'saab-9-3-yS3f'] }
  ]
};
