// Audi — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Audi',
  cars: [
    { model: 'A1', gen: 'GB', years: [2018, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [19000, 30000], used: [11000, 26000], accel: 6.5, power: [95, 207], top: 149,
      fuels: ['petrol'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 335, len: 4029, kg: 1165,
      mpy: 8000, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 82, drive: 68, practicality: 62, value: 66, design: 72, running: 76 },
      verdict: 'A Polo in a sharper blazer. Beautifully screwed together, pricier than it needs to be, holds money stubbornly.',
      issues: ['Firm on S line springs', 'Pricey for a supermini'],
      buy: '30 TFSI Sport — the sweet, sane one.',
      tags: ['city-darling', 'badge-value', 'posh-interior', 'first-car-friendly'],
      rivals: ['mini-hatch-f56', 'volkswagen-polo-mk6', 'toyota-yaris-xp210'] },

    { model: 'A3', gen: '8P', years: [2003, 2012], bodies: ['hatch', 'convertible'], segment: 'family-hatch',
      priceNew: [17000, 30000], used: [1800, 6000], accel: 5.6, power: [102, 265], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 47, ev: null, seats: 5, doors: 5, boot: 370, len: 4292, kg: 1310,
      mpy: 8500, ncap: [5, 2003], onSale: false, halo: false,
      g: { build: 76, drive: 66, practicality: 68, value: 76, design: 62, running: 70 },
      verdict: 'The original posh Golf. Solid, sensible, everywhere — a tidy 2.0 TDI Sportback still makes a fine first car.',
      issues: ['DSG mechatronics on early boxes', 'Oil use on 2.0 TFSI EA888 gen1'],
      buy: '2.0 TDI Sportback S line, cambelt done.',
      tags: ['bargain-hero', 'first-car-friendly', 'discreet', 'crowd-pleaser'],
      rivals: ['volkswagen-golf-mk5', 'bmw-1-series-e87', 'ford-focus-mk2'] },

    { model: 'A3', gen: '8V', years: [2012, 2020], bodies: ['hatch', 'saloon', 'convertible'], segment: 'family-hatch',
      priceNew: [20000, 38000], used: [7000, 20000], accel: 5.8, power: [110, 310], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 55, ev: 25, seats: 5, doors: 5, boot: 380, len: 4313, kg: 1280,
      mpy: 9000, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 82, drive: 70, practicality: 70, value: 78, design: 70, running: 76 },
      verdict: 'Quietly one of the most complete cars of its decade. Nothing flashy, nothing wrong — premium as a habit.',
      issues: ['1.8/2.0 TFSI oil consumption on early units'],
      buy: '35 TFSI Sportback S line facelift; e-tron PHEV for town.',
      tags: ['discreet', 'crowd-pleaser', 'company-car-hero', 'posh-interior', 'motorway-muncher'],
      rivals: ['volkswagen-golf-mk7', 'bmw-1-series-f20', 'mercedes-benz-a-class-w176'] },

    { model: 'A3', gen: '8Y', years: [2020, 0], bodies: ['hatch', 'saloon'], segment: 'family-hatch',
      priceNew: [26000, 42000], used: [15000, 34000], accel: 6.8, power: [110, 190], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 52, ev: 40, seats: 5, doors: 5, boot: 380, len: 4343, kg: 1320,
      mpy: 9000, ncap: [5, 2020], onSale: true, halo: false,
      g: { build: 80, drive: 70, practicality: 70, value: 70, design: 70, running: 76 },
      verdict: 'Sharper suit, screen-heavier cabin, some plastics gone walkabout. Still the default junior-exec answer.',
      issues: ['Cabin plastics dipped vs 8V', 'Touch sliders infuriate'],
      buy: '40 TFSI e S line — 40 electric miles, tax-friendly.',
      tags: ['discreet', 'company-car-hero', 'crowd-pleaser', 'tech-fest'],
      rivals: ['bmw-1-series-f40', 'mercedes-benz-a-class-w177', 'volkswagen-golf-mk8'] },

    { model: 'S3', gen: '8V', years: [2013, 2020], bodies: ['hatch', 'saloon'], segment: 'hot-hatch',
      priceNew: [33000, 42000], used: [14000, 26000], accel: 4.6, power: [300, 310], top: 155,
      fuels: ['petrol'], mpg: 40, ev: null, seats: 5, doors: 5, boot: 340, len: 4322, kg: 1500,
      mpy: 8000, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 82, drive: 76, practicality: 68, value: 78, design: 68, running: 60 },
      verdict: 'All-weather pace with zero drama — the fast Audi formula distilled. Effective rather than exciting, hugely usable.',
      issues: ['Numb steering', 'Check for remaps'],
      buy: 'S3 Sportback S tronic, stock, full history.',
      tags: ['pocket-rocket', 'discreet', 'motorway-muncher', 'crowd-pleaser'],
      rivals: ['volkswagen-golf-r-mk7', 'bmw-m135i-f20', 'mercedes-amg-a35-w177'] },

    { model: 'RS3', gen: '8Y', years: [2021, 0], bodies: ['hatch', 'saloon'], segment: 'hot-hatch',
      priceNew: [52000, 62000], used: [36000, 56000], accel: 3.8, power: [400, 400], top: 174,
      fuels: ['petrol'], mpg: 31, ev: null, seats: 5, doors: 5, boot: 282, len: 4389, kg: 1570,
      mpy: 7000, ncap: [5, 2020], onSale: true, halo: false,
      g: { build: 84, drive: 86, practicality: 62, value: 66, design: 74, running: 44 },
      verdict: 'A five-cylinder warble you can’t buy anywhere else, plus a drift-happy rear diff. The engine is the whole argument — and it wins.',
      issues: ['Thirsty driven as intended', 'Firm ride on 19s'],
      buy: 'RS3 Sportback Launch Edition, ceramic-free.',
      tags: ['pocket-rocket', 'head-turner', 'autobahn-stormer', 'future-classic', 'rev-happy'],
      rivals: ['mercedes-amg-a45-w177', 'bmw-m2-g87', 'honda-civic-type-r-fl5'] },

    { model: 'A4', gen: 'B8', years: [2008, 2015], bodies: ['saloon', 'estate'], segment: 'compact-exec',
      priceNew: [23000, 40000], used: [3500, 11000], accel: 5.9, power: [120, 333], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 5, doors: 4, boot: 480, len: 4703, kg: 1465,
      mpy: 9500, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 78, drive: 66, practicality: 78, value: 78, design: 66, running: 70 },
      verdict: 'The sensible-shoes exec that refuses to die. Avant + 2.0 TDI = the unofficial car of every UK trade and family.',
      issues: ['Oil-burning 2.0 TFSI (pre-2012)', 'Multitronic CVT best avoided'],
      buy: '2.0 TDI 177 Avant S line manual, 2013-on.',
      tags: ['bargain-hero', 'discreet', 'dog-friendly', 'motorway-muncher', 'bulletproof'],
      rivals: ['bmw-3-series-e90', 'mercedes-benz-c-class-w204', 'volkswagen-passat-b7'] },

    { model: 'A4', gen: 'B9', years: [2015, 2024], bodies: ['saloon', 'estate'], segment: 'compact-exec',
      priceNew: [28000, 50000], used: [10000, 34000], accel: 4.7, power: [150, 450], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 55, ev: null, seats: 5, doors: 4, boot: 480, len: 4726, kg: 1450,
      mpy: 10000, ncap: [5, 2015], onSale: false, halo: false,
      g: { build: 86, drive: 72, practicality: 80, value: 80, design: 70, running: 74 },
      verdict: 'Screwed together like a bank vault, drives like a very good appliance. The 40 TDI Avant is peak rational motoring.',
      issues: ['AdBlue/EGR niggles on high-milers'],
      buy: '40 TDI S line Avant, 2019-on facelift with the better infotainment.',
      tags: ['discreet', 'bulletproof', 'motorway-muncher', 'dog-friendly', 'company-car-hero', 'posh-interior'],
      rivals: ['bmw-3-series-g20', 'mercedes-benz-c-class-w205', 'volvo-s60-p3'] },

    { model: 'RS4', gen: 'B9', years: [2017, 2024], bodies: ['estate'], segment: 'super-coupe',
      priceNew: [62000, 85000], used: [35000, 62000], accel: 4.1, power: [450, 450], top: 155,
      fuels: ['petrol'], mpg: 28, ev: null, seats: 5, doors: 5, boot: 495, len: 4781, kg: 1745,
      mpy: 7000, ncap: null, onSale: false, halo: false,
      g: { build: 86, drive: 82, practicality: 82, value: 72, design: 78, running: 42 },
      verdict: 'The fast estate perfected as a daily: dogs, kids, 174mph. Less playful than an M3, more usable every single day.',
      issues: ['Optional ceramics cost a kidney to replace', 'Thirsty in town'],
      buy: 'Carbon Black with sports differential and comfort seats.',
      tags: ['autobahn-stormer', 'dog-friendly', 'muscular', 'discreet', 'tardis'],
      rivals: ['bmw-m3-g80', 'mercedes-amg-c63-w205', 'alfa-romeo-giulia-quadrifoglio-952'] },

    { model: 'A5', gen: 'B9', years: [2016, 2024], bodies: ['coupe', 'convertible', 'saloon'], segment: 'sports',
      priceNew: [33000, 55000], used: [13000, 38000], accel: 4.8, power: [150, 354], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 4, doors: 2, boot: 465, len: 4673, kg: 1475,
      mpy: 9000, ncap: [5, 2015], onSale: false, halo: false,
      g: { build: 84, drive: 72, practicality: 70, value: 76, design: 78, running: 70 },
      verdict: 'An A4 with better tailoring. The Sportback is the shape Audi should charge extra for — handsome, hushed, easy.',
      issues: ['S tronic low-speed hesitation'],
      buy: '45 TFSI Sportback S line — pace and polish, no drama.',
      tags: ['sleek', 'grand-tourer', 'discreet', 'motorway-muncher', 'posh-interior'],
      rivals: ['bmw-4-series-g22', 'mercedes-benz-cle-c236', 'volkswagen-arteon-3h'] },

    { model: 'A6', gen: 'C7', years: [2011, 2018], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [32000, 58000], used: [6000, 18000], accel: 5.3, power: [150, 333], top: 155,
      fuels: ['petrol', 'diesel', 'hybrid'], mpg: 52, ev: null, seats: 5, doors: 4, boot: 565, len: 4915, kg: 1670,
      mpy: 11000, ncap: [5, 2011], onSale: false, halo: false,
      g: { build: 84, drive: 68, practicality: 84, value: 82, design: 70, running: 68 },
      verdict: 'Vault-solid autobahn furniture at supermini money. A BiTDI Avant hauls like a freight train and looks the part.',
      issues: ['Some 3.0 TDI timing-chain wear', 'Air suspension on Allroad ages'],
      buy: 'A6 Avant 3.0 BiTDI Black Edition — end-game family diesel.',
      tags: ['motorway-muncher', 'bulletproof', 'tardis', 'bargain-hero', 'discreet', 'dog-friendly'],
      rivals: ['bmw-5-series-f10', 'mercedes-benz-e-class-w212', 'volvo-v90-p5'] },

    { model: 'A6', gen: 'C8', years: [2018, 0], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [40000, 70000], used: [17000, 48000], accel: 5.0, power: [163, 349], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 50, ev: 42, seats: 5, doors: 4, boot: 565, len: 4939, kg: 1725,
      mpy: 11000, ncap: [5, 2018], onSale: true, halo: false,
      g: { build: 86, drive: 70, practicality: 84, value: 76, design: 72, running: 72 },
      verdict: 'Twin-screen tech done with restraint, mile-eating done with mastery. The quiet accountant of big execs.',
      issues: ['Haptic screens smudge and distract', '48v system electrics on early cars'],
      buy: '50 TFSI e quattro S line — plug-in shrinks the tax bill.',
      tags: ['motorway-muncher', 'posh-interior', 'discreet', 'tech-fest', 'company-car-hero'],
      rivals: ['bmw-5-series-g30', 'mercedes-benz-e-class-w213', 'volvo-s90-p5'] },

    { model: 'RS6', gen: 'C8', years: [2019, 0], bodies: ['estate'], segment: 'super-coupe',
      priceNew: [95000, 130000], used: [55000, 100000], accel: 3.6, power: [600, 630], top: 174,
      fuels: ['petrol'], mpg: 23, ev: null, seats: 5, doors: 5, boot: 565, len: 4995, kg: 2075,
      mpy: 7000, ncap: null, onSale: true, halo: false,
      g: { build: 88, drive: 86, practicality: 86, value: 62, design: 88, running: 30 },
      verdict: 'The everything-weapon: 600bhp, five seats, a labrador boot and box arches. The default dream estate, priced like it.',
      issues: ['Consumables: tyres, brakes, fuel, repeat', 'Options list is a trap'],
      buy: 'Performance spec with Dynamic pack; let year one depreciation happen to someone else.',
      tags: ['autobahn-stormer', 'muscular', 'head-turner', 'tardis', 'dog-friendly', 'v8-soundtrack'],
      rivals: ['bmw-m5-f90', 'mercedes-amg-e63-w213', 'porsche-panamera-971'] },

    { model: 'A7', gen: '4G', years: [2010, 2018], bodies: ['saloon'], segment: 'exec',
      priceNew: [45000, 65000], used: [8000, 20000], accel: 5.3, power: [190, 333], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 47, ev: null, seats: 4, doors: 5, boot: 535, len: 4969, kg: 1770,
      mpy: 9500, ncap: null, onSale: false, halo: false,
      g: { build: 82, drive: 68, practicality: 74, value: 78, design: 82, running: 60 },
      verdict: 'The pretty A6 with a hatchback party trick. BiTDI versions waft and wallop; depreciation already done for you.',
      issues: ['3.0 TDI chain tensioners', 'Air suspension age'],
      buy: '3.0 BiTDI quattro Black Edition — the £60k car at £15k.',
      tags: ['sleek', 'head-turner', 'bargain-hero', 'grand-tourer', 'motorway-muncher'],
      rivals: ['mercedes-benz-cls-c218', 'bmw-6-series-gran-coupe-f06', 'jaguar-xf-x250'] },

    { model: 'A8', gen: 'D5', years: [2017, 0], bodies: ['saloon'], segment: 'luxury',
      priceNew: [72000, 110000], used: [22000, 60000], accel: 4.9, power: [286, 585], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 44, ev: 30, seats: 5, doors: 4, boot: 505, len: 5172, kg: 1920,
      mpy: 9000, ncap: [5, 2018], onSale: true, halo: false,
      g: { build: 88, drive: 70, practicality: 80, value: 80, design: 70, running: 46 },
      verdict: 'The stealth-wealth limo. Nobody looks twice, which is exactly the point — and used prices are a scandal in your favour.',
      issues: ['Complex tech ages expensively', 'Predictive suspension repairs'],
      buy: '50 TDI Vorsprung, three years old, at 60% off.',
      tags: ['wafty', 'discreet', 'depreciation-king', 'posh-interior', 'bargain-hero', 'money-pit-risk'],
      rivals: ['mercedes-benz-s-class-w222', 'bmw-7-series-g11', 'lexus-ls-xf50'] },

    { model: 'TT', gen: '8J', years: [2006, 2014], bodies: ['coupe', 'convertible'], segment: 'roadster-classic',
      priceNew: [25000, 40000], used: [4000, 12000], accel: 4.3, power: [160, 340], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 40, ev: null, seats: 4, doors: 2, boot: 290, len: 4178, kg: 1335,
      mpy: 6000, ncap: null, onSale: false, halo: false,
      g: { build: 80, drive: 72, practicality: 50, value: 78, design: 82, running: 66 },
      verdict: 'Design-icon daily that shrugged off the hairdresser jokes. A TTS or the five-pot TT RS are properly rapid.',
      issues: ['Magnetic dampers pricey when tired', 'Haldex servicing often skipped'],
      buy: 'TTS S tronic coupé, magnetic ride working, history stamped.',
      tags: ['modern-classic', 'sleek', 'head-turner', 'first-car-friendly', 'bargain-hero'],
      rivals: ['bmw-z4-e89', 'mercedes-benz-slk-r172', 'nissan-370z-z34'] },

    { model: 'TT', gen: '8S', years: [2014, 2023], bodies: ['coupe', 'convertible'], segment: 'sports',
      priceNew: [30000, 55000], used: [13000, 40000], accel: 3.7, power: [180, 400], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 44, ev: null, seats: 4, doors: 2, boot: 305, len: 4191, kg: 1335,
      mpy: 6000, ncap: null, onSale: false, halo: false,
      g: { build: 84, drive: 76, practicality: 52, value: 76, design: 80, running: 64 },
      verdict: 'The last TT — virtual cockpit, crisp lines, honest pace. The RS’s five-cylinder makes it an instant future classic.',
      issues: ['Rear seats decorative', 'RS values already waking up'],
      buy: 'TT RS coupé 2019-on, or a 45 TFSI quattro for half the money.',
      tags: ['sleek', 'future-classic', 'head-turner', 'drivers-car', 'rev-happy'],
      rivals: ['bmw-z4-g29', 'toyota-gr-supra-a90', 'porsche-718-cayman-982'] },

    { model: 'R8', gen: '4S', years: [2015, 2024], bodies: ['coupe', 'convertible'], segment: 'super-coupe',
      priceNew: [120000, 160000], used: [75000, 130000], accel: 3.1, power: [540, 620], top: 205,
      fuels: ['petrol'], mpg: 21, ev: null, seats: 2, doors: 2, boot: 112, len: 4426, kg: 1595,
      mpy: 3000, ncap: null, onSale: false, halo: true,
      g: { build: 88, drive: 92, practicality: 30, value: 64, design: 88, running: 26 },
      verdict: 'The last great naturally-aspirated V10, wrapped in an everyday-usable supercar. History will be very kind.',
      issues: ['Tyres and services at supercar rates'],
      buy: 'V10 Performance RWD manual-throttle joy; buy on service history.',
      tags: ['v8-soundtrack', 'future-classic', 'head-turner', 'track-day', 'rev-happy'],
      rivals: ['porsche-911-992', 'mercedes-amg-gt-c190', 'mclaren-570s-p13'] },

    { model: 'Q2', gen: 'GA', years: [2016, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [23000, 38000], used: [10000, 28000], accel: 6.5, power: [95, 300], top: 152,
      fuels: ['petrol', 'diesel'], mpg: 48, ev: null, seats: 5, doors: 5, boot: 405, len: 4191, kg: 1280,
      mpy: 8500, ncap: [5, 2016], onSale: true, halo: false,
      g: { build: 80, drive: 68, practicality: 68, value: 68, design: 70, running: 74 },
      verdict: 'An A3 in chunky trainers. Neat to drive, easy to park, more style than substance — and fine with that.',
      issues: ['Back seat merely OK', 'Options pushed prices up'],
      buy: '35 TFSI S line — all the car it needs to be.',
      tags: ['city-darling', 'badge-value', 'school-run', 'crowd-pleaser'],
      rivals: ['volkswagen-t-roc-a11', 'mini-countryman-f60', 'lexus-ux-za10'] },

    { model: 'Q3', gen: 'F3', years: [2018, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [30000, 48000], used: [16000, 38000], accel: 5.8, power: [150, 400], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 47, ev: 30, seats: 5, doors: 5, boot: 530, len: 4484, kg: 1550,
      mpy: 9500, ncap: [5, 2018], onSale: true, halo: false,
      g: { build: 82, drive: 68, practicality: 82, value: 72, design: 72, running: 70 },
      verdict: 'The family-sized Q that quietly does everything: sliding bench, big boot, badge on the nose. Rational premium.',
      issues: ['Infotainment lag on early cars'],
      buy: '35 TDI S line — or the bonkers RS Q3 for the five-pot noise.',
      tags: ['school-run', 'tardis', 'badge-value', 'crowd-pleaser', 'dog-friendly'],
      rivals: ['bmw-x1-u11', 'volvo-xc40-p8', 'mercedes-benz-gla-h247'] },

    { model: 'Q5', gen: 'FY', years: [2017, 2024], bodies: ['suv'], segment: 'family-suv',
      priceNew: [38000, 60000], used: [16000, 42000], accel: 5.1, power: [163, 367], top: 148,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 47, ev: 38, seats: 5, doors: 5, boot: 550, len: 4663, kg: 1770,
      mpy: 10500, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 86, drive: 70, practicality: 82, value: 76, design: 70, running: 68 },
      verdict: 'The sensible one of the premium mid-SUVs. Impeccably built, deliberately unexciting, painlessly excellent.',
      issues: ['AdBlue niggles', 'Air suspension optioned cars age dearer'],
      buy: '40 TDI quattro S line, 2021-on facelift with better hybrid tech.',
      tags: ['school-run', 'bulletproof', 'posh-interior', 'crowd-pleaser', 'tow-car'],
      rivals: ['bmw-x3-g01', 'mercedes-benz-glc-x253', 'volvo-xc60-p6'] },

    { model: 'Q7', gen: '4M', years: [2015, 0], bodies: ['suv'], segment: 'large-suv',
      priceNew: [52000, 90000], used: [20000, 70000], accel: 5.9, power: [218, 507], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 40, ev: 43, seats: 7, doors: 5, boot: 775, len: 5052, kg: 2060,
      mpy: 10000, ncap: [5, 2015], onSale: true, halo: false,
      g: { build: 86, drive: 72, practicality: 92, value: 74, design: 66, running: 44 },
      verdict: 'Seven proper seats and a cabin from business class. The family bus that never feels like defeat.',
      issues: ['Air suspension and 48v bills after year five', 'It is very large'],
      buy: '50 TDI S line with the tow pack — the caravan club’s Rolls.',
      tags: ['family-bus', 'seven-seats', 'tow-car', 'wafty', 'tardis', 'posh-interior'],
      rivals: ['bmw-x5-g05', 'volvo-xc90-p2', 'land-rover-discovery-l462'] },

    { model: 'Q4 e-tron', gen: 'F4', years: [2021, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [45000, 60000], used: [21000, 42000], accel: 5.7, power: [170, 340], top: 112,
      fuels: ['ev'], mpg: null, ev: 330, seats: 5, doors: 5, boot: 520, len: 4588, kg: 2050,
      mpy: 9000, ncap: [5, 2021], onSale: true, halo: false,
      g: { build: 80, drive: 66, practicality: 80, value: 74, design: 70, running: 82 },
      verdict: 'ID.4 bones, Audi finishing school. Calm, roomy, and used values make it the thinking family’s first EV.',
      issues: ['Uninvolving to drive', 'Early software clunk — get updates done'],
      buy: '45 quattro S line, 2023-on with the faster charging.',
      tags: ['silent-cruiser', 'school-run', 'depreciation-king', 'cheap-to-run', 'crowd-pleaser'],
      rivals: ['tesla-model-y-juniper', 'skoda-enyaq-5az', 'bmw-ix1-u11'] },

    { model: 'e-tron GT', gen: 'F83', years: [2021, 0], bodies: ['saloon'], segment: 'ev-native',
      priceNew: [88000, 135000], used: [45000, 90000], accel: 3.3, power: [476, 646], top: 155,
      fuels: ['ev'], mpg: null, ev: 305, seats: 4, doors: 4, boot: 405, len: 4989, kg: 2340,
      mpy: 7000, ncap: null, onSale: true, halo: false,
      g: { build: 90, drive: 84, practicality: 62, value: 66, design: 92, running: 60 },
      verdict: 'A Taycan in couture. Possibly the best-looking EV yet made — and two-year-old cars have halved. Halved.',
      issues: ['Rear headroom', 'Range midfield for the money'],
      buy: 'Used quattro at £50k: six figures of car, hot-hatch money.',
      tags: ['head-turner', 'sleek', 'silent-cruiser', 'depreciation-king', 'grand-tourer'],
      rivals: ['porsche-taycan-y1a', 'tesla-model-s-refresh', 'bmw-i5-g60'] }
  ]
};
