// BYD — model-generations, UK market. Curated for Vroom. (Other Chinese newcomers in newcomers.mjs)
export default {
  make: 'BYD',
  cars: [
    { model: 'Atto 3', gen: 'BA3', years: [2023, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [37000, 40000], used: [18000, 30000], accel: 7.3, power: [204, 204], top: 99,
      fuels: ['ev'], mpg: null, ev: 260, seats: 5, doors: 5, boot: 440, len: 4455, kg: 1750,
      mpy: 9000, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 78, drive: 62, practicality: 78, value: 82, design: 68, running: 86 },
      verdict: 'Blade-battery family EV with a gym-themed cabin (the door handles are dumbbells). Odd, solid, seriously warrantied.',
      issues: ['Guitar-string door pockets — really', 'Infotainment rotates, novelty wears'],
      buy: 'Design trim used — depreciation already absorbed.',
      tags: ['left-field', 'cheap-to-run', 'school-run', 'silent-cruiser', 'bargain-hero'],
      rivals: ['mg-zs-ev-zs11', 'kia-niro-sg2', 'hyundai-kona-sx2'] },

    { model: 'Dolphin', gen: 'BD1', years: [2023, 0], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [26000, 32000], used: [15000, 25000], accel: 7.0, power: [95, 204], top: 99,
      fuels: ['ev'], mpg: null, ev: 265, seats: 5, doors: 5, boot: 345, len: 4290, kg: 1658,
      mpy: 8500, ncap: [5, 2023], onSale: true, halo: false,
      g: { build: 76, drive: 64, practicality: 74, value: 84, design: 62, running: 88 },
      verdict: 'The rational electric hatch: real range, real space, real warranty, unreal price. Charisma sold separately.',
      issues: ['Soft brakes', 'Interior style acquired taste'],
      buy: 'Comfort 60kWh — the value-first family electric.',
      tags: ['bargain-hero', 'cheap-to-run', 'city-darling', 'crowd-pleaser'],
      rivals: ['mg-mg4-mk1', 'citroen-e-c3-cc21', 'volkswagen-id-3-e11'] },

    { model: 'Seal', gen: 'BS1', years: [2023, 0], bodies: ['saloon'], segment: 'ev-native',
      priceNew: [45000, 50000], used: [28000, 40000], accel: 3.8, power: [313, 530], top: 112,
      fuels: ['ev'], mpg: null, ev: 354, seats: 5, doors: 4, boot: 402, len: 4800, kg: 2055,
      mpy: 9500, ncap: [5, 2023], onSale: true, halo: false,
      g: { build: 84, drive: 74, practicality: 72, value: 82, design: 82, running: 86 },
      verdict: 'The Model 3 rival that feels premium inside and undercuts used. The quiet proof China builds properly now.',
      issues: ['Brand residuals unproven', 'Driver-assist nags'],
      buy: 'Design AWD — 3.8s and luxury feel for used-Golf-R money.',
      tags: ['sleek', 'silent-cruiser', 'tech-fest', 'bargain-hero', 'head-turner'],
      rivals: ['tesla-model-3-highland', 'hyundai-ioniq-6-ce', 'polestar-2-p2'] },

    { model: 'Sealion 7', gen: 'BS7', years: [2025, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [47000, 59000], used: [38000, 50000], accel: 4.5, power: [313, 530], top: 133,
      fuels: ['ev'], mpg: null, ev: 312, seats: 5, doors: 5, boot: 500, len: 4830, kg: 2225,
      mpy: 9500, ncap: [5, 2025], onSale: true, halo: false,
      g: { build: 82, drive: 68, practicality: 82, value: 78, design: 74, running: 84 },
      verdict: 'BYD’s Model Y shot: plush, quick, keenly priced. Less efficient than the best, roomier than most.',
      issues: ['Efficiency mid-pack', 'Big kerb weight'],
      buy: 'Comfort RWD — the family-space value play.',
      tags: ['school-run', 'tardis', 'silent-cruiser', 'bargain-hero'],
      rivals: ['tesla-model-y-juniper', 'kia-ev6-cv', 'skoda-enyaq-5az'] },

    { model: 'Seal U DM-i', gen: 'BSU', years: [2024, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [33000, 40000], used: [25000, 35000], accel: 8.9, power: [218, 324], top: 105,
      fuels: ['phev'], mpg: 50, ev: 78, seats: 5, doors: 5, boot: 425, len: 4785, kg: 1940,
      mpy: 10000, ncap: [5, 2024], onSale: true, halo: false,
      g: { build: 78, drive: 60, practicality: 84, value: 88, design: 66, running: 84 },
      verdict: '78 electric miles, huge cabin, £33k — the PHEV maths that terrifies legacy brands. Comfort-first and proud.',
      issues: ['Soft dynamics', 'Brand unknowns'],
      buy: 'Boost trim — the company-car spreadsheet winner.',
      tags: ['bargain-hero', 'school-run', 'cheap-to-run', 'tardis', 'crowd-pleaser'],
      rivals: ['mg-hs-as23', 'kia-sportage-nq5', 'toyota-rav4-xa50'] }
  ]
};
