// Citroën — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Citroen',
  cars: [
    { model: 'C1', gen: 'B4', years: [2014, 2022], bodies: ['hatch'], segment: 'city',
      priceNew: [9000, 14000], used: [4000, 9500], accel: 12.6, power: [68, 82], top: 99,
      fuels: ['petrol'], mpg: 57, ev: null, seats: 4, doors: 5, boot: 196, len: 3466, kg: 840,
      mpy: 6000, ncap: [4, 2014], onSale: false, halo: false,
      g: { build: 68, drive: 62, practicality: 48, value: 82, design: 66, running: 92 },
      verdict: 'Airscape roof, peanut bills, city-perfect footprint. The Aygo triplet with the Gallic grin.',
      issues: ['Motorway drone', 'Thin doors'],
      buy: '1.2 PureTech Flair Airscape — sunshine for pennies.',
      tags: ['city-darling', 'first-car-friendly', 'cheap-to-run', 'bargain-hero'],
      rivals: ['toyota-aygo-ab40', 'peugeot-108-b3', 'volkswagen-up-aa'] },

    { model: 'C3', gen: 'SX', years: [2016, 2024], bodies: ['hatch'], segment: 'supermini',
      priceNew: [13000, 20000], used: [6000, 14000], accel: 9.3, power: [83, 130], top: 118,
      fuels: ['petrol', 'diesel'], mpg: 55, ev: null, seats: 5, doors: 5, boot: 300, len: 3996, kg: 1090,
      mpy: 7500, ncap: [4, 2017], onSale: false, halo: false,
      g: { build: 72, drive: 60, practicality: 68, value: 80, design: 76, running: 86 },
      verdict: 'Airbump cladding, sofa seats, zero sporting pretence — comfort-first small-car honesty at friendly money.',
      issues: ['Soft body roll', 'PureTech belt service history'],
      buy: '1.2 PureTech 110 Shine — the comfy contrarian.',
      tags: ['city-darling', 'wafty', 'cheap-to-run', 'left-field', 'bargain-hero'],
      rivals: ['renault-clio-v', 'peugeot-208-p21', 'skoda-fabia-pj'] },

    { model: 'ë-C3', gen: 'CC21', years: [2024, 0], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [22000, 26000], used: [17000, 23000], accel: 10.4, power: [113, 113], top: 84,
      fuels: ['ev'], mpg: null, ev: 199, seats: 5, doors: 5, boot: 310, len: 4015, kg: 1416,
      mpy: 7000, ncap: [4, 2024], onSale: true, halo: false,
      g: { build: 74, drive: 62, practicality: 72, value: 88, design: 78, running: 90 },
      verdict: 'The £22k EV that finally makes electric normal — comfy suspension, honest range, proper-car feel. Value landmark.',
      issues: ['84mph flat out', 'Range dips in winter like all small packs'],
      buy: 'Max trim — still cheap, fully loaded.',
      tags: ['bargain-hero', 'city-darling', 'cheap-to-run', 'wafty', 'crowd-pleaser'],
      rivals: ['renault-5-e-tech-bfb', 'dacia-spring-bbg', 'fiat-500e-332'] },

    { model: 'C4', gen: 'C41', years: [2021, 0], bodies: ['hatch'], segment: 'family-hatch',
      priceNew: [22000, 33000], used: [12000, 25000], accel: 7.9, power: [100, 156], top: 130,
      fuels: ['petrol', 'diesel', 'ev'], mpg: 52, ev: 260, seats: 5, doors: 5, boot: 380, len: 4355, kg: 1300,
      mpy: 9000, ncap: [4, 2021], onSale: true, halo: false,
      g: { build: 76, drive: 64, practicality: 76, value: 80, design: 74, running: 84 },
      verdict: 'Comfort as a brand strategy: squishy Advanced Comfort seats, bump-swallowing ride, coupé-ish looks. ë-C4 doubles down.',
      issues: ['Vague steering', 'Infotainment mid-table'],
      buy: 'ë-C4 54kWh Shine — the La-Z-Boy of affordable EVs.',
      tags: ['wafty', 'left-field', 'cheap-to-run', 'school-run', 'discreet'],
      rivals: ['volkswagen-golf-mk8', 'renault-megane-e-tech-bcb', 'peugeot-308-p52'] },

    { model: 'C5 Aircross', gen: 'C84', years: [2019, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [25000, 38000], used: [12000, 28000], accel: 8.9, power: [130, 225], top: 130,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 50, ev: 40, seats: 5, doors: 5, boot: 580, len: 4500, kg: 1430,
      mpy: 10000, ncap: [4, 2019], onSale: true, halo: false,
      g: { build: 76, drive: 62, practicality: 84, value: 82, design: 72, running: 80 },
      verdict: 'Three individual sliding rear seats and a magic-carpet ride — the family SUV that prioritised your spine.',
      issues: ['Leans in corners by design', 'PureTech belt records'],
      buy: 'Hybrid 225 Shine Plus — wafting with tax perks.',
      tags: ['wafty', 'school-run', 'tardis', 'bargain-hero', 'dog-friendly'],
      rivals: ['peugeot-3008-p84', 'skoda-karoq-nu7', 'nissan-qashqai-j12'] },

    { model: 'Berlingo', gen: 'K9', years: [2018, 0], bodies: ['mpv'], segment: 'mpv-van',
      priceNew: [22000, 32000], used: [12000, 26000], accel: 11.5, power: [102, 136], top: 109,
      fuels: ['petrol', 'diesel', 'ev'], mpg: 54, ev: 213, seats: 7, doors: 5, boot: 775, len: 4403, kg: 1450,
      mpy: 9500, ncap: [4, 2018], onSale: true, halo: false,
      g: { build: 74, drive: 58, practicality: 96, value: 86, design: 56, running: 84 },
      verdict: 'A van with windows and zero shame — three child seats across, picnic-table boot, unbeatable family maths.',
      issues: ['It is a van and looks it', 'Wind noise at pace'],
      buy: 'XL BlueHDi 130 Flair XTR 7-seat — family logistics solved.',
      tags: ['van-with-windows', 'seven-seats', 'tardis', 'bargain-hero', 'dog-friendly', 'family-bus', 'adventure-ready'],
      rivals: ['volkswagen-caddy-sb', 'ford-tourneo-connect-mk3', 'dacia-jogger-rjl'] },

    { model: 'Grand C4 SpaceTourer', gen: 'B78', years: [2013, 2022], bodies: ['mpv'], segment: 'seven-seater',
      priceNew: [22000, 33000], used: [7000, 17000], accel: 10.0, power: [110, 165], top: 130,
      fuels: ['petrol', 'diesel'], mpg: 55, ev: null, seats: 7, doors: 5, boot: 645, len: 4602, kg: 1430,
      mpy: 9500, ncap: [5, 2014], onSale: false, halo: false,
      g: { build: 72, drive: 60, practicality: 92, value: 86, design: 70, running: 82 },
      verdict: 'Panoramic glasshouse, seven seats, 55mpg — the MPV done with actual design flair, going for a song.',
      issues: ['EAT6 auto history check', 'Trim squeaks'],
      buy: 'BlueHDi 130 Flair — glass-roofed family value.',
      tags: ['seven-seats', 'tardis', 'family-bus', 'bargain-hero', 'left-field', 'cheap-to-run'],
      rivals: ['ford-s-max-mk2', 'volkswagen-touran-5t', 'vauxhall-zafira-tourer-c'] },

    { model: 'DS3', gen: 'A55', years: [2010, 2019], bodies: ['hatch', 'convertible'], segment: 'supermini',
      priceNew: [13000, 24000], used: [3500, 9000], accel: 6.5, power: [82, 208], top: 143,
      fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 5, doors: 3, boot: 285, len: 3948, kg: 1075,
      mpy: 7000, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 74, drive: 74, practicality: 56, value: 78, design: 82, running: 78 },
      verdict: 'The shark-fin style supermini that fought MINIs on charm. Racing versions are pocket-rocket bargains now.',
      issues: ['THP timing chain history', 'Trim rattles'],
      buy: 'DS3 Performance or 1.6 THP DSport — Gallic fizz, MINI money saved.',
      tags: ['head-turner', 'city-darling', 'pocket-rocket', 'bargain-hero', 'modern-classic'],
      rivals: ['mini-hatch-r56', 'audi-a1-8x', 'fiat-500-312'] },

    { model: 'C6', gen: 'TD', years: [2006, 2012], bodies: ['saloon'], segment: 'luxury',
      priceNew: [30000, 42000], used: [4500, 12000], accel: 8.9, power: [173, 240], top: 143,
      fuels: ['petrol', 'diesel'], mpg: 38, ev: null, seats: 5, doors: 4, boot: 421, len: 4908, kg: 1816,
      mpy: 7000, ncap: [5, 2005], onSale: false, halo: false,
      g: { build: 72, drive: 66, practicality: 74, value: 70, design: 90, running: 44 },
      verdict: 'The last great French presidential barge — hydropneumatic waft, concave rear glass, glorious commercial failure.',
      issues: ['Hydraulic spheres and suspension pumps', 'Parts patience required'],
      buy: '2.7 HDi Exclusive, full history, join the owners’ club first.',
      tags: ['wafty', 'left-field', 'modern-classic', 'future-classic', 'head-turner', 'money-pit-risk'],
      rivals: ['jaguar-xj-x351', 'audi-a8-d3', 'lexus-ls-xf40'] },

    { model: 'SM', gen: 'Classic', years: [1970, 1975], bodies: ['coupe'], segment: 'roadster-classic',
      priceNew: [5000, 6000], used: [35000, 70000], accel: 8.9, power: [170, 178], top: 142,
      fuels: ['petrol'], mpg: 20, ev: null, seats: 4, doors: 2, boot: 380, len: 4893, kg: 1450,
      mpy: 2000, ncap: null, onSale: false, halo: true,
      g: { build: 66, drive: 72, practicality: 50, value: 58, design: 97, running: 26 },
      verdict: 'Maserati V6, hydropneumatic glide, spaceship glass nose — the most audacious GT ever made. A rolling artwork.',
      issues: ['Cam chains and carbs need specialists', 'Hydraulics: green fluid religion'],
      buy: 'The best-sorted car you can find; never the cheapest.',
      tags: ['modern-classic', 'head-turner', 'wafty', 'left-field', 'future-classic', 'grand-tourer'],
      rivals: ['jaguar-e-type-s3', 'mercedes-benz-sl-r107'] }
  ]
};
