// Cupra — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Cupra',
  cars: [
    { model: 'Formentor', gen: 'KM7', years: [2020, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [31000, 48000], used: [18000, 38000], accel: 4.9, power: [150, 390], top: 155,
      fuels: ['petrol', 'phev'], mpg: 44, ev: 40, seats: 5, doors: 5, boot: 450, len: 4450, kg: 1510,
      mpy: 9500, ncap: [5, 2021], onSale: true, halo: false,
      g: { build: 82, drive: 80, practicality: 78, value: 78, design: 84, running: 70 },
      verdict: 'The copper-badged crossover-coupé that made Cupra a real brand. VZ2 is a Golf R in a sharper jacket.',
      issues: ['Firm ride is the brand', 'Infotainment sliders'],
      buy: 'VZ2 2.0 TSI 310 — pace, presence, practicality.',
      tags: ['head-turner', 'sporty', 'school-run', 'drivers-car', 'crowd-pleaser'],
      rivals: ['volkswagen-t-roc-a11', 'bmw-x2-f39', 'audi-q3-f3'] },

    { model: 'Born', gen: 'K11', years: [2021, 0], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [32000, 44000], used: [15000, 32000], accel: 5.6, power: [150, 326], top: 111,
      fuels: ['ev'], mpg: null, ev: 340, seats: 5, doors: 5, boot: 385, len: 4322, kg: 1785,
      mpy: 8500, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 78, drive: 76, practicality: 76, value: 80, design: 80, running: 84 },
      verdict: 'The ID.3 with hips and attitude — the EV hatch that remembered design matters. VZ adds real punch.',
      issues: ['Same VW software lineage', 'Copper trim not for wallflowers'],
      buy: '77kWh e-Boost V3, or the 326bhp VZ for grins.',
      tags: ['head-turner', 'silent-cruiser', 'city-darling', 'drivers-car', 'cheap-to-run'],
      rivals: ['volkswagen-id-3-e11', 'renault-megane-e-tech-bcb', 'mg-mg4-mk1'] },

    { model: 'Leon', gen: 'K1', years: [2021, 0], bodies: ['hatch', 'estate'], segment: 'hot-hatch',
      priceNew: [31000, 43000], used: [18000, 34000], accel: 4.9, power: [245, 310], top: 155,
      fuels: ['petrol', 'phev'], mpg: 40, ev: 36, seats: 5, doors: 5, boot: 380, len: 4368, kg: 1450,
      mpy: 8500, ncap: [5, 2020], onSale: true, halo: false,
      g: { build: 80, drive: 82, practicality: 78, value: 80, design: 74, running: 66 },
      verdict: 'The Golf R estate’s cheaper, angrier cousin. 310 ST 4Drive hauls dogs at silly speeds for sensible money.',
      issues: ['Ride firm', 'Touch controls again'],
      buy: 'VZ3 310 Estate 4Drive — the everything-car on a budget.',
      tags: ['pocket-rocket', 'dog-friendly', 'drivers-car', 'bargain-hero', 'discreet'],
      rivals: ['volkswagen-golf-r-mk8', 'audi-s3-8y', 'bmw-m135i-f40'] },

    { model: 'Ateca', gen: '5FP', years: [2018, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [38000, 45000], used: [20000, 36000], accel: 4.9, power: [300, 300], top: 153,
      fuels: ['petrol'], mpg: 34, ev: null, seats: 5, doors: 5, boot: 485, len: 4386, kg: 1615,
      mpy: 9000, ncap: [5, 2016], onSale: true, halo: false,
      g: { build: 80, drive: 80, practicality: 80, value: 76, design: 68, running: 58 },
      verdict: 'A 300bhp family box that hits 62 in under five — the original fast Cupra SUV, still the honest one.',
      issues: ['Thirst when hurried', 'Looks like a normal Ateca (feature?)'],
      buy: 'VZ3 with Brembos and the panoramic roof.',
      tags: ['pocket-rocket', 'school-run', 'discreet', 'dog-friendly'],
      rivals: ['volkswagen-t-roc-r-a11', 'audi-sq2-ga', 'bmw-x1-u11'] },

    { model: 'Tavascan', gen: 'KR', years: [2024, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [47000, 61000], used: [36000, 52000], accel: 5.5, power: [286, 340], top: 112,
      fuels: ['ev'], mpg: null, ev: 353, seats: 5, doors: 5, boot: 540, len: 4644, kg: 2188,
      mpy: 9500, ncap: [5, 2024], onSale: true, halo: false,
      g: { build: 80, drive: 74, practicality: 80, value: 74, design: 84, running: 82 },
      verdict: 'A concept-car cockpit and coupé-SUV drama on VW bones. The stylish family EV for the design-led.',
      issues: ['Rear headroom vs the roofline', 'Brand still building trust'],
      buy: 'VZ2 — the drama spec at the sane price point.',
      tags: ['head-turner', 'sleek', 'silent-cruiser', 'tech-fest', 'school-run'],
      rivals: ['volkswagen-id-4-id-5-e21', 'ford-mustang-mach-e-cx727', 'kia-ev6-cv'] }
  ]
};
