// Dacia — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Dacia',
  cars: [
    { model: 'Sandero', gen: 'BJI', years: [2021, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [10000, 17000], used: [7000, 14000], accel: 11.7, power: [65, 110], top: 111,
      fuels: ['petrol'], mpg: 53, ev: null, seats: 5, doors: 5, boot: 328, len: 4088, kg: 1078,
      mpy: 8000, ncap: [2, 2021], onSale: true, halo: false,
      g: { build: 70, drive: 60, practicality: 76, value: 95, design: 62, running: 90 },
      verdict: 'Britain’s cheapest real car and objectively all most people need. Clio bones, supermarket price — value royalty.',
      issues: ['Two-star NCAP (kit, not structure)', 'Cabin plastics do the job, no more'],
      buy: 'TCe 90 Expression — the rational nation’s choice.',
      tags: ['bargain-hero', 'cheap-to-run', 'first-car-friendly', 'crowd-pleaser', 'discreet'],
      rivals: ['renault-clio-v', 'kia-picanto-ja', 'mg-3-mk2'] },

    { model: 'Sandero Stepway', gen: 'BJI', years: [2021, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [12000, 18000], used: [8000, 15000], accel: 11.9, power: [90, 110], top: 109,
      fuels: ['petrol'], mpg: 51, ev: null, seats: 5, doors: 5, boot: 328, len: 4099, kg: 1125,
      mpy: 8000, ncap: [2, 2021], onSale: true, halo: false,
      g: { build: 70, drive: 60, practicality: 76, value: 92, design: 66, running: 88 },
      verdict: 'The Sandero in hiking boots — crossover looks for hatchback money. The anti-status symbol status symbol.',
      issues: ['Same two-star caveat', 'Roof bars decorative for most'],
      buy: 'TCe 90 Stepway Expression — cheerful, capable, cheap.',
      tags: ['bargain-hero', 'cheap-to-run', 'crowd-pleaser', 'adventure-ready'],
      rivals: ['suzuki-ignis-mf', 'kia-stonic-yb', 'fiat-panda-319'] },

    { model: 'Duster', gen: 'HM', years: [2018, 2024], bodies: ['suv'], segment: 'family-suv',
      priceNew: [14000, 22000], used: [9000, 18000], accel: 9.6, power: [90, 150], top: 124,
      fuels: ['petrol', 'diesel'], mpg: 47, ev: null, seats: 5, doors: 5, boot: 445, len: 4341, kg: 1320,
      mpy: 9000, ncap: [3, 2017], onSale: false, halo: false,
      g: { build: 72, drive: 62, practicality: 80, value: 92, design: 68, running: 86 },
      verdict: 'The people’s 4x4: honest, tough, half the price of everything comparable. 4x4 versions embarrass posh SUVs in mud.',
      issues: ['Wind noise', 'Three-star safety kit'],
      buy: 'TCe 130 4x4 Journey — the farm-lane hero at B-road money.',
      tags: ['bargain-hero', 'go-anywhere', 'chunky-4x4', 'cheap-to-run', 'adventure-ready', 'crowd-pleaser'],
      rivals: ['suzuki-vitara-ly', 'mg-hs-as23', 'skoda-kamiq-nw4'] },

    { model: 'Duster', gen: 'DR3', years: [2024, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [19000, 27000], used: [15000, 23000], accel: 9.9, power: [100, 140], top: 112,
      fuels: ['petrol', 'hybrid'], mpg: 55, ev: null, seats: 5, doors: 5, boot: 472, len: 4343, kg: 1395,
      mpy: 9000, ncap: [3, 2024], onSale: true, halo: false,
      g: { build: 76, drive: 64, practicality: 82, value: 90, design: 78, running: 86 },
      verdict: 'Gen three grew a design language and a hybrid — still unbeatable per pound, now genuinely desirable too.',
      issues: ['Hybrid tow limit low', 'Cabin still hard-wearing plastic'],
      buy: 'Hybrid 140 Journey — the thinking family’s default.',
      tags: ['bargain-hero', 'chunky-4x4', 'cheap-to-run', 'crowd-pleaser', 'adventure-ready', 'head-turner'],
      rivals: ['mg-hs-as23', 'suzuki-vitara-ly', 'kia-stonic-yb'] },

    { model: 'Jogger', gen: 'RJL', years: [2022, 0], bodies: ['estate'], segment: 'seven-seater',
      priceNew: [17000, 24000], used: [12000, 20000], accel: 10.6, power: [110, 140], top: 114,
      fuels: ['petrol', 'hybrid'], mpg: 49, ev: null, seats: 7, doors: 5, boot: 700, len: 4547, kg: 1250,
      mpy: 9500, ncap: [1, 2021], onSale: true, halo: false,
      g: { build: 70, drive: 62, practicality: 92, value: 95, design: 62, running: 88 },
      verdict: 'Seven seats for £17k — nothing else comes within £10k. The family maths destroyer; ignore the badge sniffs.',
      issues: ['One-star NCAP (assist kit, not crash structure)', 'Row three basic'],
      buy: 'Hybrid 140 Expression 7-seat — the family fleet solved.',
      tags: ['seven-seats', 'bargain-hero', 'tardis', 'family-bus', 'cheap-to-run', 'left-field'],
      rivals: ['citroen-berlingo-k9', 'volkswagen-touran-5t', 'skoda-kodiaq-ns7'] },

    { model: 'Spring', gen: 'BBG', years: [2024, 0], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [15000, 17000], used: [11000, 15000], accel: 13.7, power: [45, 65], top: 78,
      fuels: ['ev'], mpg: null, ev: 140, seats: 4, doors: 5, boot: 308, len: 3701, kg: 984,
      mpy: 5000, ncap: [1, 2021], onSale: true, halo: false,
      g: { build: 62, drive: 50, practicality: 60, value: 88, design: 58, running: 94 },
      verdict: 'Britain’s cheapest EV — a tonne of car, 140 town miles, pennies per charge. City transport reduced to essentials.',
      issues: ['One-star NCAP', 'Motorways are ambitious'],
      buy: 'Extreme 65 — the urban runabout for £15k new.',
      tags: ['bargain-hero', 'city-darling', 'cheap-to-run', 'lightweight', 'left-field'],
      rivals: ['citroen-e-c3-cc21', 'fiat-500e-332', 'renault-twingo-iii'] }
  ]
};
