// Fiat & Abarth — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Fiat',
  cars: [
    { model: '500', gen: '312', years: [2008, 2024], bodies: ['hatch', 'convertible'], segment: 'city',
      priceNew: [11000, 18000], used: [3000, 12000], accel: 10.5, power: [69, 105], top: 113,
      fuels: ['petrol', 'hybrid'], mpg: 53, ev: null, seats: 4, doors: 3, boot: 185, len: 3571, kg: 940,
      mpy: 6000, ncap: [5, 2007], onSale: false, halo: false,
      g: { build: 66, drive: 64, practicality: 44, value: 78, design: 90, running: 88 },
      verdict: 'Sixteen years of dolce vita on 14-inch wheels. Objectively mediocre, subjectively irresistible — design wins.',
      issues: ['City-fragile trim', 'TwinAir thirsty if driven with joy (always)'],
      buy: 'TwinAir Lounge for character; 1.0 hybrid for sense.',
      tags: ['retro-charm', 'city-darling', 'head-turner', 'first-car-friendly', 'cheap-to-run'],
      rivals: ['mini-hatch-f56', 'volkswagen-up-aa', 'toyota-aygo-ab40'] },

    { model: '500e', gen: '332', years: [2021, 0], bodies: ['hatch', 'convertible'], segment: 'ev-native',
      priceNew: [25000, 34000], used: [10000, 22000], accel: 9.0, power: [95, 118], top: 93,
      fuels: ['ev'], mpg: null, ev: 199, seats: 4, doors: 3, boot: 185, len: 3632, kg: 1365,
      mpy: 6500, ncap: [4, 2021], onSale: true, halo: false,
      g: { build: 76, drive: 68, practicality: 46, value: 76, design: 90, running: 88 },
      verdict: 'The 500 reborn properly electric — chicer inside, 199 miles, still the prettiest small car in the car park.',
      issues: ['Rear seats decorative', 'Price crept above its weight new'],
      buy: '42kWh La Prima used — Milan fashion at high-street price.',
      tags: ['retro-charm', 'city-darling', 'head-turner', 'silent-cruiser', 'cheap-to-run'],
      rivals: ['mini-cooper-f66', 'renault-5-e-tech-bfb', 'honda-e-ze1'] },

    { model: 'Panda', gen: '319', years: [2012, 2024], bodies: ['hatch'], segment: 'city',
      priceNew: [9000, 15000], used: [3500, 10000], accel: 11.2, power: [69, 90], top: 102,
      fuels: ['petrol', 'hybrid'], mpg: 52, ev: null, seats: 4, doors: 5, boot: 225, len: 3653, kg: 940,
      mpy: 6500, ncap: [3, 2011], onSale: false, halo: false,
      g: { build: 64, drive: 62, practicality: 62, value: 82, design: 68, running: 88 },
      verdict: 'The boxy Italian workhorse — and the 4x4 TwinAir is a mountain goat with cult status. Simple, honest, cheap.',
      issues: ['Basic everything', 'Rust checks on early cars'],
      buy: 'Panda 4x4 TwinAir — the tiny off-road legend.',
      tags: ['city-darling', 'boxy-icon', 'go-anywhere', 'cheap-to-run', 'left-field', 'bargain-hero'],
      rivals: ['suzuki-ignis-mf', 'volkswagen-up-aa', 'dacia-sandero-bji'] },

    { model: 'Tipo', gen: '356', years: [2016, 2023], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [13000, 20000], used: [6000, 13000], accel: 9.6, power: [95, 120], top: 124,
      fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 440, len: 4368, kg: 1270,
      mpy: 8500, ncap: [3, 2016], onSale: false, halo: false,
      g: { build: 66, drive: 58, practicality: 78, value: 84, design: 54, running: 84 },
      verdict: 'Zero glamour, maximum metal-per-pound. The Station Wagon hauls like cars twice the price — that’s the whole pitch.',
      issues: ['Cabin plastics bargain-bin', 'Three-star safety'],
      buy: 'SW 1.6 MultiJet Lounge — family space for city-car money.',
      tags: ['bargain-hero', 'cheap-to-run', 'tardis', 'discreet'],
      rivals: ['dacia-sandero-bji', 'kia-ceed-cd', 'skoda-scala-nw1'] },

    { model: '124 Spider', gen: '348', years: [2016, 2020], bodies: ['convertible'], segment: 'sports',
      priceNew: [20000, 28000], used: [12000, 20000], accel: 6.8, power: [140, 170], top: 134,
      fuels: ['petrol'], mpg: 44, ev: null, seats: 2, doors: 2, boot: 140, len: 4054, kg: 1050,
      mpy: 5000, ncap: null, onSale: false, halo: false,
      g: { build: 78, drive: 84, practicality: 32, value: 80, design: 80, running: 78 },
      verdict: 'An MX-5 with an Italian accent and a turbo torque curve. Rarer than the Mazda, arguably prettier, just as joyful.',
      issues: ['MultiAir needs its oil changes', 'Boot is symbolic'],
      buy: 'Abarth-adjacent Lusso Plus, or hunt the full Abarth 124.',
      tags: ['drivers-car', 'analogue-joy', 'head-turner', 'lightweight', 'left-field', 'future-classic'],
      rivals: ['mazda-mx-5-nd', 'mini-hatch-f56', 'toyota-gt86-zn6'] },

    { model: '500X', gen: '334', years: [2015, 2024], bodies: ['suv'], segment: 'small-suv',
      priceNew: [17000, 27000], used: [7000, 16000], accel: 8.9, power: [110, 180], top: 118,
      fuels: ['petrol', 'diesel', 'hybrid'], mpg: 48, ev: null, seats: 5, doors: 5, boot: 350, len: 4248, kg: 1320,
      mpy: 8000, ncap: [4, 2015], onSale: false, halo: false,
      g: { build: 68, drive: 60, practicality: 68, value: 76, design: 74, running: 80 },
      verdict: 'The 500’s look stretched over crossover bones. Style still carries it; the driving never did. Cheap cheerful Italy.',
      issues: ['Reliability middling', 'Rear space tight'],
      buy: '1.0 FireFly Sport — the style buy at the honest price.',
      tags: ['city-darling', 'retro-charm', 'crowd-pleaser', 'bargain-hero'],
      rivals: ['nissan-juke-f16', 'renault-captur-ii', 'seat-arona-kj7'] },

    { model: 'Abarth 595', gen: '312A', years: [2012, 2024], bodies: ['hatch', 'convertible'], segment: 'hot-hatch',
      priceNew: [16000, 26000], used: [8000, 20000], accel: 6.7, power: [145, 180], top: 140,
      fuels: ['petrol'], mpg: 38, ev: null, seats: 4, doors: 3, boot: 185, len: 3660, kg: 1035,
      mpy: 6000, ncap: null, onSale: false, halo: false,
      g: { build: 66, drive: 80, practicality: 40, value: 74, design: 82, running: 70 },
      verdict: 'A firework in a handbag — pops, bangs, and a ride like a skateboard. Silly, loud, completely loveable.',
      issues: ['Ride punishes bad roads', 'Clutches wear fast when enjoyed'],
      buy: '595 Competizione with the Record Monza exhaust, obviously.',
      tags: ['pocket-rocket', 'head-turner', 'retro-charm', 'city-darling', 'analogue-joy'],
      rivals: ['mini-hatch-f56', 'ford-fiesta-mk8', 'hyundai-i20-n-bc3'] },

    { model: 'Abarth 500e', gen: '332A', years: [2023, 0], bodies: ['hatch', 'convertible'], segment: 'hot-hatch',
      priceNew: [34000, 38000], used: [20000, 30000], accel: 7.0, power: [155, 155], top: 96,
      fuels: ['ev'], mpg: null, ev: 164, seats: 4, doors: 3, boot: 185, len: 3673, kg: 1410,
      mpy: 6000, ncap: [4, 2021], onSale: true, halo: false,
      g: { build: 76, drive: 74, practicality: 42, value: 62, design: 84, running: 82 },
      verdict: 'An electric hot hatch with a fake-noise speaker committing to the bit. Fun in town; range and price limit the joke.',
      issues: ['164-mile range shrinks fast driven hard', 'Expensive new for what it is'],
      buy: 'Turismo used, once depreciation does its Abarth thing.',
      tags: ['pocket-rocket', 'city-darling', 'head-turner', 'left-field', 'silent-cruiser'],
      rivals: ['mini-cooper-f66', 'fiat-500e-332', 'renault-5-e-tech-bfb'] }
  ]
};
