// Ford — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Ford',
  cars: [
    { model: 'Fiesta', gen: 'Mk7', years: [2008, 2017], bodies: ['hatch'], segment: 'supermini',
      priceNew: [10000, 18000], used: [2000, 8000], accel: 6.9, power: [60, 182], top: 137,
      fuels: ['petrol', 'diesel'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 276, len: 3950, kg: 1045,
      mpy: 7500, ncap: [5, 2008], onSale: false, halo: false,
      g: { build: 68, drive: 84, practicality: 62, value: 88, design: 66, running: 86 },
      verdict: 'Britain’s best-seller because it deserved to be — steering joy for pocket money. The ST is an all-time hot hatch.',
      issues: ['Powershift auto = avoid', 'Rusty rear arches now appearing'],
      buy: 'Fiesta ST-2 Mk7.5, or any 1.25 Zetec as a brilliant first car.',
      tags: ['first-car-friendly', 'bargain-hero', 'drivers-car', 'cheap-to-run', 'b-road-hero', 'crowd-pleaser'],
      rivals: ['vauxhall-corsa-d', 'volkswagen-polo-mk5', 'renault-clio-iv'] },

    { model: 'Fiesta', gen: 'Mk8', years: [2017, 2023], bodies: ['hatch'], segment: 'supermini',
      priceNew: [14000, 24000], used: [7000, 20000], accel: 6.5, power: [75, 200], top: 144,
      fuels: ['petrol', 'hybrid'], mpg: 54, ev: null, seats: 5, doors: 5, boot: 292, len: 4040, kg: 1130,
      mpy: 8000, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 72, drive: 86, practicality: 64, value: 84, design: 68, running: 84 },
      verdict: 'The last Fiesta — killed at its peak. Still the driver’s supermini; the ST’s three-pot is a firecracker.',
      issues: ['1.0 EcoBoost wet-belt — check changed', 'Thin rear doors mark easily'],
      buy: 'ST-3 with the Quaife diff, or 1.0 125 ST-Line for daily smiles.',
      tags: ['drivers-car', 'first-car-friendly', 'pocket-rocket', 'cheap-to-run', 'b-road-hero', 'future-classic'],
      rivals: ['volkswagen-polo-mk6', 'renault-clio-v', 'peugeot-208-p21'] },

    { model: 'Focus', gen: 'Mk2', years: [2004, 2011], bodies: ['hatch', 'estate', 'convertible'], segment: 'family-hatch',
      priceNew: [13000, 22000], used: [1200, 5000], accel: 6.8, power: [80, 305], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 45, ev: null, seats: 5, doors: 5, boot: 385, len: 4342, kg: 1275,
      mpy: 8500, ncap: [5, 2004], onSale: false, halo: false,
      g: { build: 62, drive: 80, practicality: 74, value: 84, design: 54, running: 78 },
      verdict: 'Dirt-cheap, great-steering family transport. The five-pot ST and rally-bred RS are the ones history remembers.',
      issues: ['Rust: arches, sills', 'Interior wears its miles'],
      buy: 'ST-2 five-cylinder for noise; any 1.6 Zetec for £1,500 sense.',
      tags: ['bargain-hero', 'first-car-friendly', 'drivers-car', 'cheap-to-run'],
      rivals: ['volkswagen-golf-mk5', 'vauxhall-astra-h', 'honda-civic-fn2'] },

    { model: 'Focus', gen: 'Mk4', years: [2018, 2025], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [20000, 36000], used: [10000, 30000], accel: 5.7, power: [85, 280], top: 155,
      fuels: ['petrol', 'diesel', 'hybrid'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 375, len: 4378, kg: 1320,
      mpy: 9000, ncap: [5, 2018], onSale: false, halo: false,
      g: { build: 74, drive: 84, practicality: 78, value: 82, design: 66, running: 78 },
      verdict: 'The best-steering family hatch to the very end — and the end came. Used STs are the enthusiast bargain of now.',
      issues: ['Wet-belt anxiety on 1.0 (check service)', 'Sync infotainment ages'],
      buy: 'ST Estate manual with the Track Pack — the family car that parties.',
      tags: ['drivers-car', 'b-road-hero', 'bargain-hero', 'dog-friendly', 'crowd-pleaser'],
      rivals: ['volkswagen-golf-mk8', 'seat-leon-k1', 'mazda-3-bp'] },

    { model: 'Focus RS', gen: 'Mk3', years: [2016, 2018], bodies: ['hatch'], segment: 'hot-hatch',
      priceNew: [31000, 37000], used: [22000, 32000], accel: 4.7, power: [350, 375], top: 165,
      fuels: ['petrol'], mpg: 33, ev: null, seats: 5, doors: 5, boot: 260, len: 4390, kg: 1599,
      mpy: 6000, ncap: [5, 2018], onSale: false, halo: false,
      g: { build: 70, drive: 88, practicality: 66, value: 74, design: 72, running: 50 },
      verdict: 'Drift mode in a family hatch — the last mad Fast Ford. Head-gasket saga sorted, values now firming. Buy carefully.',
      issues: ['Head gasket recall — confirm done', 'Hard-used examples common'],
      buy: 'Post-recall car, standard, with the forged-owner paper trail.',
      tags: ['pocket-rocket', 'future-classic', 'track-day', 'head-turner', 'b-road-hero'],
      rivals: ['honda-civic-type-r-fk8', 'volkswagen-golf-r-mk7', 'audi-rs3-8v'] },

    { model: 'Puma', gen: 'Mk1', years: [2019, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [22000, 33000], used: [12000, 28000], accel: 6.7, power: [125, 200], top: 137,
      fuels: ['petrol', 'hybrid'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 456, len: 4186, kg: 1280,
      mpy: 9000, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 74, drive: 82, practicality: 78, value: 80, design: 70, running: 80 },
      verdict: 'Britain’s best-seller with an actual sense of humour. Megabox boot, Fiesta fizz — the crossover for drivers.',
      issues: ['Wet-belt service history essential', 'Firm ST-Line ride'],
      buy: '1.0 155 ST-Line X, or the full-fat ST while they still exist.',
      tags: ['crowd-pleaser', 'drivers-car', 'school-run', 'cheap-to-run', 'b-road-hero'],
      rivals: ['volkswagen-t-roc-a11', 'nissan-juke-f16', 'toyota-yaris-cross-xp210'] },

    { model: 'Kuga', gen: 'Mk3', years: [2020, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [28000, 42000], used: [14000, 34000], accel: 7.5, power: [120, 243], top: 125,
      fuels: ['petrol', 'diesel', 'hybrid', 'phev'], mpg: 52, ev: 39, seats: 5, doors: 5, boot: 475, len: 4614, kg: 1660,
      mpy: 10500, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 74, drive: 74, practicality: 82, value: 82, design: 62, running: 78 },
      verdict: 'The PHEV that quietly outsells the hype. Tidy to drive, honest money — fleet Britain’s default done right.',
      issues: ['Early PHEV battery recall (done)', 'Bland cabin'],
      buy: 'PHEV ST-Line X — 39 electric miles, no plug anxiety.',
      tags: ['school-run', 'crowd-pleaser', 'cheap-to-run', 'dog-friendly', 'company-car-hero'],
      rivals: ['toyota-rav4-xa50', 'volkswagen-tiguan-ad', 'hyundai-tucson-nx4'] },

    { model: 'Mondeo', gen: 'Mk5', years: [2014, 2022], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [22000, 34000], used: [7000, 18000], accel: 7.9, power: [120, 240], top: 145,
      fuels: ['petrol', 'diesel', 'hybrid'], mpg: 55, ev: null, seats: 5, doors: 5, boot: 550, len: 4871, kg: 1530,
      mpy: 11000, ncap: [5, 2014], onSale: false, halo: false,
      g: { build: 74, drive: 76, practicality: 86, value: 86, design: 62, running: 78 },
      verdict: 'Mondeo Man’s swansong: vast, comfy, 60mpg and invisible to thieves and neighbours alike. Peak sensible.',
      issues: ['Nobody will envy you', 'Hybrid CVT drone'],
      buy: '2.0 EcoBlue 190 Titanium Estate — motorway emperor for £12k.',
      tags: ['motorway-muncher', 'bargain-hero', 'tardis', 'discreet', 'dog-friendly', 'cheap-to-run'],
      rivals: ['volkswagen-passat-b8', 'skoda-superb-b8', 'mazda-6-gj'] },

    { model: 'S-Max', gen: 'Mk2', years: [2015, 2023], bodies: ['mpv'], segment: 'seven-seater',
      priceNew: [27000, 40000], used: [11000, 28000], accel: 8.4, power: [120, 240], top: 137,
      fuels: ['petrol', 'diesel', 'hybrid'], mpg: 48, ev: null, seats: 7, doors: 5, boot: 700, len: 4796, kg: 1710,
      mpy: 10500, ncap: [5, 2015], onSale: false, halo: false,
      g: { build: 74, drive: 78, practicality: 90, value: 84, design: 62, running: 72 },
      verdict: 'The seven-seater that steers like a Focus. The MPV for people who refuse to admit the fun is over.',
      issues: ['AWD rare; check tyres/history', 'Middle-row rattles with age'],
      buy: '2.0 EcoBlue 190 Titanium — the driver’s school bus.',
      tags: ['seven-seats', 'family-bus', 'drivers-car', 'tardis', 'bargain-hero', 'dog-friendly'],
      rivals: ['volkswagen-touran-5t', 'seat-alhambra-7n', 'citroen-grand-c4-spacetourer-b78'] },

    { model: 'Mustang', gen: 'S550', years: [2015, 2023], bodies: ['coupe', 'convertible'], segment: 'sports',
      priceNew: [36000, 55000], used: [22000, 45000], accel: 4.3, power: [290, 460], top: 155,
      fuels: ['petrol'], mpg: 25, ev: null, seats: 4, doors: 2, boot: 408, len: 4784, kg: 1720,
      mpy: 6000, ncap: [3, 2017], onSale: false, halo: false,
      g: { build: 70, drive: 78, practicality: 60, value: 82, design: 84, running: 40 },
      verdict: 'A V8 Mustang in right-hand drive for M240i money. Crude in the corners, cinema everywhere else. Buy the noise.',
      issues: ['Three-star NCAP', 'MT82 manual gearbox notchiness'],
      buy: '5.0 GT Fastback manual with the active exhaust. Never the EcoBoost.',
      tags: ['v8-soundtrack', 'muscular', 'head-turner', 'grand-tourer', 'future-classic', 'bargain-hero'],
      rivals: ['bmw-2-series-coupe-f22', 'audi-s5-b9', 'nissan-370z-z34'] },

    { model: 'Mustang Mach-E', gen: 'CX727', years: [2021, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [45000, 65000], used: [20000, 42000], accel: 3.7, power: [269, 487], top: 111,
      fuels: ['ev'], mpg: null, ev: 372, seats: 5, doors: 5, boot: 402, len: 4713, kg: 2110,
      mpy: 9000, ncap: [5, 2021], onSale: true, halo: false,
      g: { build: 74, drive: 76, practicality: 78, value: 78, design: 74, running: 82 },
      verdict: 'Not a Mustang, still a very good EV. Long-range versions do real 300-mile trips; used prices fell off a cliff — climb down and grab one.',
      issues: ['Door-handle nubs baffle valets', 'Infotainment portrait-screen sprawl'],
      buy: 'Extended Range RWD used — the 370-mile one for £25k.',
      tags: ['silent-cruiser', 'depreciation-king', 'school-run', 'cheap-to-run'],
      rivals: ['tesla-model-y-juniper', 'hyundai-ioniq-5-ne', 'kia-ev6-cv'] },

    { model: 'Ranger', gen: 'T6.2', years: [2022, 0], bodies: ['pickup'], segment: 'pickup',
      priceNew: [35000, 60000], used: [24000, 50000], accel: 5.9, power: [170, 292], top: 118,
      fuels: ['diesel', 'petrol'], mpg: 33, ev: null, seats: 5, doors: 4, boot: 1200, len: 5370, kg: 2300,
      mpy: 12000, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 78, drive: 68, practicality: 88, value: 74, design: 76, running: 52 },
      verdict: 'The pickup that ate the UK market. Wildtrak spec is a lifestyle statement; Raptor is a Baja truck with a numberplate.',
      issues: ['Tax rules changed — do the maths', 'It will not fit in a car park'],
      buy: 'Wildtrak 2.0 EcoBlue 205 auto; Raptor if the heart insists.',
      tags: ['chunky-4x4', 'tow-car', 'adventure-ready', 'go-anywhere', 'muscular'],
      rivals: ['toyota-hilux-an120', 'volkswagen-amarok-nf', 'isuzu-d-max-rg'] },

    { model: 'Tourneo Custom', gen: 'Mk2', years: [2023, 0], bodies: ['mpv'], segment: 'mpv-van',
      priceNew: [45000, 62000], used: [30000, 52000], accel: 10.0, power: [136, 233], top: 110,
      fuels: ['diesel', 'phev'], mpg: 38, ev: 35, seats: 8, doors: 5, boot: 1300, len: 5050, kg: 2260,
      mpy: 12000, ncap: [5, 2024], onSale: true, halo: false,
      g: { build: 74, drive: 62, practicality: 94, value: 74, design: 58, running: 62 },
      verdict: 'Eight seats, van bones, surprisingly car-like manners. The V-Class for people who did the spreadsheet.',
      issues: ['Van dimensions everywhere', 'Trim is durable rather than plush'],
      buy: 'Titanium X 2.0 EcoBlue 170 LWB — the family aircraft, economy class.',
      tags: ['van-with-windows', 'family-bus', 'seven-seats', 'tardis', 'bargain-hero'],
      rivals: ['volkswagen-multivan-t7', 'mercedes-benz-v-class-w447', 'citroen-spacetourer-mk1'] },

    { model: 'Ka+', gen: 'Mk2', years: [2016, 2020], bodies: ['hatch'], segment: 'city',
      priceNew: [9000, 13000], used: [4000, 8500], accel: 13.3, power: [70, 85], top: 105,
      fuels: ['petrol'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 270, len: 3929, kg: 1055,
      mpy: 6000, ncap: [3, 2017], onSale: false, halo: false,
      g: { build: 62, drive: 60, practicality: 62, value: 74, design: 44, running: 86 },
      verdict: 'Honest, forgettable city transport — five doors and Fiesta bones for buttons. There are worse first cars.',
      issues: ['Three-star safety', 'Charisma not included'],
      buy: '1.2 85 Zetec, low miles, one careful granny.',
      tags: ['first-car-friendly', 'cheap-to-run', 'city-darling', 'bargain-hero'],
      rivals: ['volkswagen-up-aa', 'hyundai-i10-ac3', 'kia-picanto-ja'] },

    { model: 'Edge', gen: 'Mk2', years: [2016, 2020], bodies: ['suv'], segment: 'large-suv',
      priceNew: [35000, 45000], used: [12000, 22000], accel: 9.4, power: [180, 238], top: 131,
      fuels: ['diesel'], mpg: 43, ev: null, seats: 5, doors: 5, boot: 602, len: 4808, kg: 1949,
      mpy: 10000, ncap: [5, 2016], onSale: false, halo: false,
      g: { build: 72, drive: 62, practicality: 82, value: 78, design: 60, running: 62 },
      verdict: 'America’s take on the family SUV: big, softly plush, forgotten by the market — which makes it quietly cheap.',
      issues: ['Depreciation already happened (good for you)', 'No seven-seat option'],
      buy: '2.0 TDCi 210 Sport bi-turbo, all the toys for £15k.',
      tags: ['left-field', 'bargain-hero', 'tardis', 'motorway-muncher'],
      rivals: ['skoda-kodiaq-ns7', 'hyundai-santa-fe-tm', 'nissan-x-trail-t32'] }
  ]
};
