// Honda — older and extra model-generations, UK market. Curated for Vroom.
export default {
  make: 'Honda',
  cars: [
    { model: 'Jazz', gen: 'GD', years: [2002, 2008], bodies: ['hatch'], segment: 'supermini', priceNew: [9000, 14000], used: [1000, 4500], accel: 11.5, power: [77, 82], top: 106, fuels: ['petrol'], mpg: 48, ev: null, seats: 5, doors: 5, boot: 380, len: 3830, kg: 1005, mpy: 6000, ncap: [4, 2004], onSale: false, halo: false,
      g: { build: 82, drive: 55, practicality: 91, value: 91, design: 46, running: 94 }, verdict: 'The first Magic Seat miracle: tiny outside, van-like inside and content to survive on annual oil changes.', issues: ['CVT judder if fluid was neglected', 'Rear arches can rust'], buy: '1.4 SE manual with dry boot and rust-free arches.', tags: ['tardis', 'bulletproof', 'cheap-to-run', 'bargain-hero', 'first-car-friendly'], rivals: ['toyota-yaris-xp90', 'nissan-note-e11', 'ford-fusion-mk1'] },

    { model: 'Jazz', gen: 'GK', years: [2015, 2020], bodies: ['hatch'], segment: 'supermini', priceNew: [14000, 19000], used: [6500, 13000], accel: 11.2, power: [102, 130], top: 118, fuels: ['petrol'], mpg: 56, ev: null, seats: 5, doors: 5, boot: 354, len: 4028, kg: 1070, mpy: 6500, ncap: [5, 2015], onSale: false, halo: false,
      g: { build: 84, drive: 60, practicality: 91, value: 82, design: 52, running: 92 }, verdict: 'Peak practical Jazz: adult rear legroom, seats that perform origami and a naturally aspirated engine built for retirement.', issues: ['CVT gets vocal on inclines', 'Touch climate controls annoy'], buy: '1.3 EX manual, or rare 1.5 Sport for actual pace.', tags: ['tardis', 'bulletproof', 'cheap-to-run', 'first-car-friendly'], rivals: ['toyota-yaris-xp130', 'nissan-note-e12', 'skoda-fabia-mk3'] },

    { model: 'Civic', gen: 'EP', years: [2001, 2005], bodies: ['hatch'], segment: 'family-hatch', priceNew: [12000, 19000], used: [1200, 6000], accel: 8.7, power: [89, 160], top: 132, fuels: ['petrol', 'diesel'], mpg: 42, ev: null, seats: 5, doors: 5, boot: 315, len: 4140, kg: 1190, mpy: 7000, ncap: [4, 2001], onSale: false, halo: false,
      g: { build: 81, drive: 68, practicality: 79, value: 89, design: 51, running: 87 }, verdict: 'A column-shifter family hatch with a flat floor and secretly brilliant packaging. The sensible EP hides beneath Type R fame.', issues: ['Gearbox input bearings can whine', 'Rear arches rust'], buy: '1.6 SE Executive manual with quiet gearbox and solid arches.', tags: ['tardis', 'bulletproof', 'bargain-hero', 'first-car-friendly'], rivals: ['toyota-corolla-e120', 'ford-focus-mk1', 'volkswagen-golf-mk4'] },

    { model: 'Civic', gen: 'FK2', years: [2012, 2017], bodies: ['hatch', 'estate'], segment: 'family-hatch', priceNew: [17000, 29000], used: [5500, 15000], accel: 8.2, power: [100, 142], top: 134, fuels: ['petrol', 'diesel'], mpg: 60, ev: null, seats: 5, doors: 5, boot: 477, len: 4300, kg: 1305, mpy: 8500, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 82, drive: 68, practicality: 88, value: 85, design: 62, running: 86 }, verdict: 'The enormous-boot Civic generation, made even cleverer as a Tourer. Strange rear end, serious family-car talent.', issues: ['Diesel DPF needs regular long runs', 'Rear visibility is poor'], buy: '1.8 i-VTEC Sport manual; Tourer if dogs or bikes feature.', tags: ['tardis', 'dog-friendly', 'bulletproof', 'bargain-hero', 'motorway-muncher'], rivals: ['toyota-auris-e180', 'ford-focus-mk3', 'volkswagen-golf-mk7'] },

    { model: 'Civic', gen: 'FK7', years: [2017, 2022], bodies: ['hatch', 'saloon'], segment: 'family-hatch', priceNew: [19000, 32000], used: [9000, 22000], accel: 7.8, power: [126, 182], top: 137, fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 478, len: 4518, kg: 1300, mpy: 9000, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 80, drive: 81, practicality: 84, value: 83, design: 68, running: 80 }, verdict: 'Long, low and unusually keen to steer for a family hatch. The 1.5 turbo is fast enough to embarrass old hot hatches.', issues: ['1.0 wet timing belt needs documented care', 'Air-con condensers can fail'], buy: '1.5 VTEC Turbo Sport manual with working air-con.', tags: ['drivers-car', 'tardis', 'bargain-hero', 'motorway-muncher'], rivals: ['mazda-mazda3-bm', 'ford-focus-mk4', 'toyota-corolla-e210'] },

    { model: 'Civic Type R', gen: 'EP3', years: [2001, 2005], bodies: ['hatch'], segment: 'hot-hatch', priceNew: [16000, 19000], used: [6000, 18000], accel: 6.4, power: [200, 200], top: 146, fuels: ['petrol'], mpg: 31, ev: null, seats: 4, doors: 3, boot: 315, len: 4140, kg: 1204, mpy: 4500, ncap: [4, 2001], onSale: false, halo: false,
      g: { build: 84, drive: 94, practicality: 68, value: 86, design: 76, running: 67 }, verdict: 'The 8,250rpm hot-hatch scripture: perfect shift, manic engine, no electronic excuses. A modern classic in real time.', issues: ['Rear arches and sills rust', 'Second-gear synchros suffer abuse'], buy: 'Standard UK car with rust proofing, healthy gearbox and no bargain tyres.', tags: ['modern-classic', 'rev-happy', 'drivers-car', 'analogue-joy', 'b-road-hero', 'future-classic'], rivals: ['renault-megane-rs-225', 'ford-focus-st-mk2', 'volkswagen-golf-gti-mk5'] },

    { model: 'Civic Type R', gen: 'FN2', years: [2007, 2011], bodies: ['hatch'], segment: 'hot-hatch', priceNew: [18000, 24000], used: [4500, 14000], accel: 6.6, power: [201, 201], top: 146, fuels: ['petrol'], mpg: 31, ev: null, seats: 4, doors: 3, boot: 485, len: 4275, kg: 1338, mpy: 4500, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 80, drive: 84, practicality: 72, value: 87, design: 79, running: 65 }, verdict: 'The spaceship Type R lost independent rear suspension but kept the glorious engine. More GT than EP3, still addictive.', issues: ['Harsh ride and cabin rattles', 'Rear beam and arches can corrode'], buy: 'Championship White Edition or tidy GT, standard suspension preferred.', tags: ['rev-happy', 'modern-classic', 'bargain-hero', 'head-turner', 'analogue-joy'], rivals: ['renault-megane-rs-250', 'ford-focus-st-mk2', 'volkswagen-golf-gti-mk6'] },

    { model: 'Civic Type R', gen: 'FK2', years: [2015, 2017], bodies: ['hatch'], segment: 'hot-hatch', priceNew: [30000, 33000], used: [19000, 30000], accel: 5.7, power: [310, 310], top: 167, fuels: ['petrol'], mpg: 34, ev: null, seats: 4, doors: 5, boot: 477, len: 4390, kg: 1382, mpy: 5500, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 84, drive: 92, practicality: 76, value: 78, design: 67, running: 59 }, verdict: 'Honda discovered turbo boost and turned the sensible Civic into an angry touring car. Rare, ferocious and already collectible.', issues: ['Firm ride never relaxes', 'Front tyres vanish under torque'], buy: 'Unmodified GT with matched premium tyres and careful service history.', tags: ['track-day', 'future-classic', 'drivers-car', 'pocket-rocket', 'head-turner'], rivals: ['ford-focus-rs-mk3', 'volkswagen-golf-r-mk7', 'renault-megane-rs-275'] },

    { model: 'Accord', gen: 'CG', years: [1998, 2003], bodies: ['saloon', 'hatch', 'coupe'], segment: 'exec', priceNew: [16000, 26000], used: [1000, 6000], accel: 7.2, power: [115, 209], top: 142, fuels: ['petrol'], mpg: 33, ev: null, seats: 5, doors: 4, boot: 427, len: 4595, kg: 1370, mpy: 6500, ncap: [3, 2000], onSale: false, halo: false,
      g: { build: 83, drive: 71, practicality: 72, value: 88, design: 57, running: 75 }, verdict: 'A precisely engineered nineties saloon, crowned by the hand-built Type R. Ordinary versions simply refuse to retire.', issues: ['Rear arches rust vigorously', 'Type R parts are scarce'], buy: '2.0 SE for sense; original Type R only after expert rust inspection.', tags: ['bulletproof', 'discreet', 'modern-classic', 'bargain-hero', 'rev-happy'], rivals: ['toyota-avensis-t250', 'mazda-mazda6-gg', 'ford-mondeo-mk2'] },

    { model: 'Accord', gen: 'CL', years: [2003, 2008], bodies: ['saloon', 'estate'], segment: 'exec', priceNew: [18000, 28000], used: [1500, 6500], accel: 7.9, power: [138, 190], top: 142, fuels: ['petrol', 'diesel'], mpg: 47, ev: null, seats: 5, doors: 4, boot: 459, len: 4665, kg: 1505, mpy: 8000, ncap: [4, 2003], onSale: false, halo: false,
      g: { build: 86, drive: 76, practicality: 78, value: 90, design: 66, running: 82 }, verdict: 'Honda’s best-kept executive secret: beautifully damped, beautifully assembled and available as an enormous Tourer.', issues: ['Diesel exhaust manifolds can crack', 'Rear brakes may bind'], buy: '2.0 petrol Executive manual; Tourer tailgates need to work smoothly.', tags: ['bulletproof', 'motorway-muncher', 'dog-friendly', 'bargain-hero', 'drivers-car'], rivals: ['toyota-avensis-t250', 'mazda-mazda6-gg', 'bmw-3-series-e46'] },

    { model: 'Accord', gen: 'CU', years: [2008, 2015], bodies: ['saloon', 'estate'], segment: 'exec', priceNew: [21000, 33000], used: [3500, 11000], accel: 7.8, power: [150, 201], top: 141, fuels: ['petrol', 'diesel'], mpg: 51, ev: null, seats: 5, doors: 4, boot: 467, len: 4725, kg: 1570, mpy: 8500, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 87, drive: 74, practicality: 77, value: 87, design: 70, running: 80 }, verdict: 'The final UK Accord feels carved from granite and steers with quiet precision. A premium car without badge theatre.', issues: ['Diesel DPF clogs on short use', 'Clutches and dual-mass flywheels wear'], buy: '2.0 i-VTEC EX manual, avoiding diesel complexity for town use.', tags: ['bulletproof', 'discreet', 'motorway-muncher', 'bargain-hero', 'posh-interior'], rivals: ['toyota-avensis-t270', 'mazda-mazda6-gh', 'volvo-s60-p3'] },

    { model: 'CR-V', gen: 'RD', years: [1997, 2001], bodies: ['suv'], segment: 'family-suv', priceNew: [16000, 21000], used: [1200, 6000], accel: 11.0, power: [126, 147], top: 110, fuels: ['petrol'], mpg: 30, ev: null, seats: 5, doors: 5, boot: 375, len: 4520, kg: 1420, mpy: 6000, ncap: null, onSale: false, halo: false,
      g: { build: 85, drive: 55, practicality: 79, value: 87, design: 68, running: 67 }, verdict: 'The picnic-table crossover before crossover was a word. Boxy visibility, switchable four-wheel drive, indestructible B-series heart.', issues: ['Rear arches and sills rust', 'Automatic gearboxes need fluid changes'], buy: 'Facelift manual with solid body and intact boot-floor picnic table.', tags: ['retro-charm', 'boxy-icon', 'bulletproof', 'adventure-ready', 'dog-friendly'], rivals: ['toyota-rav4-xa10', 'suzuki-grand-vitara-ft', 'land-rover-freelander-l314'] },

    { model: 'CR-V', gen: 'RE', years: [2007, 2012], bodies: ['suv'], segment: 'family-suv', priceNew: [20000, 31000], used: [3500, 10000], accel: 10.3, power: [140, 150], top: 118, fuels: ['petrol', 'diesel'], mpg: 43, ev: null, seats: 5, doors: 5, boot: 556, len: 4530, kg: 1655, mpy: 8500, ncap: [4, 2007], onSale: false, halo: false,
      g: { build: 85, drive: 61, practicality: 87, value: 87, design: 56, running: 80 }, verdict: 'A vast, flat-floored family SUV with a reliability record that makes premium rivals look faintly ridiculous.', issues: ['Diesel clutch and flywheel wear', 'Rear differential fluid causes groaning'], buy: '2.0 i-VTEC EX automatic with evidence of differential-fluid changes.', tags: ['bulletproof', 'school-run', 'dog-friendly', 'tardis', 'bargain-hero'], rivals: ['toyota-rav4-xa30', 'nissan-x-trail-t31', 'mazda-cx-5-ke'] },

    { model: 'CR-V', gen: 'RM', years: [2012, 2018], bodies: ['suv'], segment: 'family-suv', priceNew: [22000, 36000], used: [7000, 18000], accel: 9.7, power: [120, 160], top: 121, fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 589, len: 4570, kg: 1580, mpy: 9500, ncap: [5, 2013], onSale: false, halo: false,
      g: { build: 86, drive: 62, practicality: 90, value: 84, design: 58, running: 82 }, verdict: 'Almost comically spacious, easy to see out of and built for family abuse. The crossover as dependable white goods.', issues: ['1.6 diesel DPF dislikes short trips', 'Infotainment was dated from launch'], buy: '2.0 petrol automatic SE Plus for uncomplicated family miles.', tags: ['bulletproof', 'school-run', 'dog-friendly', 'tardis', 'motorway-muncher'], rivals: ['toyota-rav4-xa40', 'nissan-x-trail-t32', 'mazda-cx-5-ke'] },

    { model: 'HR-V', gen: 'GH', years: [1999, 2006], bodies: ['suv'], segment: 'small-suv', priceNew: [13000, 18000], used: [1500, 6000], accel: 10.6, power: [104, 123], top: 112, fuels: ['petrol'], mpg: 34, ev: null, seats: 5, doors: 5, boot: 285, len: 4110, kg: 1250, mpy: 5500, ncap: null, onSale: false, halo: false,
      g: { build: 80, drive: 64, practicality: 65, value: 84, design: 78, running: 72 }, verdict: 'A high-riding three-door oddity two decades ahead of fashion. VTEC versions add sparkle; boxy style has aged brilliantly.', issues: ['Rear arches and sills rust', 'CVT start clutch can judder'], buy: 'Five-door VTEC manual with a solid underside and recent cambelt.', tags: ['retro-charm', 'left-field', 'adventure-ready', 'future-classic', 'city-darling'], rivals: ['toyota-urban-cruiser-xp110', 'suzuki-sx4-gy', 'nissan-juke-f15'] },

    { model: 'HR-V', gen: 'RU', years: [2015, 2021], bodies: ['suv'], segment: 'small-suv', priceNew: [18000, 29000], used: [8000, 18000], accel: 7.8, power: [120, 182], top: 134, fuels: ['petrol', 'diesel'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 470, len: 4295, kg: 1325, mpy: 8000, ncap: [5, 2015], onSale: false, halo: false,
      g: { build: 82, drive: 63, practicality: 86, value: 80, design: 64, running: 84 }, verdict: 'A coupe-ish crossover that somehow retains Magic Seats and a huge boot. Not exciting, unusually well packaged.', issues: ['CVT drones under load', '1.5 turbo is rare and firm-riding'], buy: '1.5 i-VTEC SE manual; Sport if you find an unmodified one.', tags: ['tardis', 'bulletproof', 'school-run', 'cheap-to-run'], rivals: ['toyota-c-hr-ax10', 'nissan-juke-f16', 'mazda-cx-3-dk'] },

    { model: 'FR-V', gen: 'BE', years: [2005, 2009], bodies: ['mpv'], segment: 'mpv-van', priceNew: [16000, 22000], used: [1800, 6500], accel: 10.1, power: [125, 140], top: 121, fuels: ['petrol', 'diesel'], mpg: 43, ev: null, seats: 6, doors: 5, boot: 439, len: 4285, kg: 1475, mpy: 7000, ncap: [4, 2005], onSale: false, halo: false,
      g: { build: 84, drive: 65, practicality: 91, value: 89, design: 55, running: 82 }, verdict: 'Three seats abreast, twice: the Fiat Multipla idea executed with Honda quality and far less visual trauma.', issues: ['Diesel manifolds can crack', 'Middle front seat is narrow'], buy: '1.8 petrol manual with six intact seat mechanisms.', tags: ['tardis', 'family-bus', 'left-field', 'bargain-hero', 'bulletproof'], rivals: ['fiat-multipla-186', 'toyota-corolla-verso-ar10', 'ford-s-max-mk1'] },

    { model: 'Insight', gen: 'ZE2', years: [2009, 2014], bodies: ['hatch'], segment: 'family-hatch', priceNew: [16000, 22000], used: [2500, 7500], accel: 12.5, power: [98, 98], top: 113, fuels: ['hybrid'], mpg: 61, ev: null, seats: 5, doors: 5, boot: 408, len: 4395, kg: 1204, mpy: 8000, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 80, drive: 51, practicality: 75, value: 88, design: 57, running: 93 }, verdict: 'A cheaper, simpler Prius rival that lost the showroom fight. Used, its 60mpg durability makes a compelling apology.', issues: ['CVT needs correct fluid', 'Rear headroom is tight'], buy: 'HE trim with annual servicing and a smooth, judder-free CVT.', tags: ['cheap-to-run', 'bulletproof', 'bargain-hero', 'discreet', 'left-field'], rivals: ['toyota-prius-xw30', 'lexus-ct-zwa10', 'hyundai-ioniq-ae'] },

    { model: 'CR-Z', gen: 'ZF', years: [2010, 2015], bodies: ['coupe'], segment: 'sports', priceNew: [17000, 24000], used: [4500, 12000], accel: 9.1, power: [124, 137], top: 124, fuels: ['hybrid'], mpg: 56, ev: null, seats: 4, doors: 3, boot: 225, len: 4080, kg: 1198, mpy: 5000, ncap: [5, 2010], onSale: false, halo: false,
      g: { build: 82, drive: 74, practicality: 44, value: 84, design: 84, running: 86 }, verdict: 'A manual hybrid coupe that promised CRX fireworks and delivered eco fizz. Still distinctive, frugal and sweet-shifting.', issues: ['Rear seats are symbolic', 'Hybrid battery age softens performance'], buy: '2013-on GT with the lithium battery and six-speed manual.', tags: ['future-classic', 'left-field', 'cheap-to-run', 'sleek', 'analogue-joy'], rivals: ['toyota-celica-t230', 'volkswagen-scirocco-mk3', 'peugeot-rcz-t75'] },

    { model: 'NSX', gen: 'NA1', years: [1990, 2005], bodies: ['coupe'], segment: 'super-coupe', priceNew: [60000, 70000], used: [65000, 150000], accel: 5.2, power: [270, 290], top: 168, fuels: ['petrol'], mpg: 24, ev: null, seats: 2, doors: 2, boot: 154, len: 4425, kg: 1370, mpy: 2500, ncap: null, onSale: false, halo: true,
      g: { build: 95, drive: 96, practicality: 40, value: 60, design: 95, running: 48 }, verdict: 'The aluminium supercar that taught Ferrari manners. Senna fingerprints, 8,000rpm precision and usability that changed everything.', issues: ['Timing belts and ageing hoses demand specialists', 'Original panels are expensive'], buy: 'Manual coupe with documented belt work; originality outweighs low mileage.', tags: ['boxy-icon', 'future-classic', 'analogue-joy', 'drivers-car', 'rev-happy', 'head-turner'], rivals: ['ferrari-348-tb', 'porsche-911-993', 'lotus-esprit-s4'] }
  ]
};
