// Honda — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Honda',
  cars: [
    { model: 'Jazz', gen: 'GE4', years: [2008, 2015], bodies: ['hatch'], segment: 'supermini',
      priceNew: [11000, 16000], used: [3000, 8000], accel: 11.2, power: [90, 100], top: 110,
      fuels: ['petrol', 'hybrid'], mpg: 51, ev: null, seats: 5, doors: 5, boot: 399, len: 3900, kg: 1090,
      mpy: 6500, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 84, drive: 58, practicality: 88, value: 84, design: 50, running: 90 },
      verdict: 'Magic Seats turn a supermini into a small van. Beloved of grandparents because grandparents are right.',
      issues: ['CVT whine', 'Style not on the menu'],
      buy: '1.4 EX manual — flip those seats, carry a bicycle upright.',
      tags: ['tardis', 'bulletproof', 'cheap-to-run', 'first-car-friendly', 'bargain-hero'],
      rivals: ['toyota-yaris-xp130', 'ford-fiesta-mk7', 'suzuki-swift-zc72'] },

    { model: 'Jazz', gen: 'GR', years: [2020, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [20000, 27000], used: [13000, 24000], accel: 9.4, power: [109, 122], top: 108,
      fuels: ['hybrid'], mpg: 62, ev: null, seats: 5, doors: 5, boot: 304, len: 4044, kg: 1280,
      mpy: 7000, ncap: [5, 2020], onSale: true, halo: false,
      g: { build: 86, drive: 62, practicality: 86, value: 76, design: 56, running: 92 },
      verdict: 'The cleverest small car on sale: 62mpg hybrid, van-flexible seats, zero drama for a decade guaranteed.',
      issues: ['Pricier than image suggests', 'Engine drones under load'],
      buy: 'Advance grade; Crosstar if gravel driveways feature.',
      tags: ['tardis', 'bulletproof', 'cheap-to-run', 'crowd-pleaser', 'city-darling'],
      rivals: ['toyota-yaris-xp210', 'renault-clio-v', 'volkswagen-polo-mk6'] },

    { model: 'Civic', gen: 'FN2', years: [2006, 2011], bodies: ['hatch'], segment: 'family-hatch',
      priceNew: [14000, 21000], used: [2000, 7000], accel: 6.6, power: [83, 201], top: 146,
      fuels: ['petrol', 'diesel'], mpg: 45, ev: null, seats: 5, doors: 5, boot: 415, len: 4256, kg: 1265,
      mpy: 8000, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 80, drive: 72, practicality: 74, value: 82, design: 74, running: 78 },
      verdict: 'Spaceship styling that still looks 2030. The Type R revs to the moon; the 1.8 just runs forever.',
      issues: ['Rear visibility through the split screen', 'Crashy ride on 18s'],
      buy: 'Type R GT for VTEC theatre; 1.8 EX for immortal commuting.',
      tags: ['bulletproof', 'bargain-hero', 'left-field', 'first-car-friendly', 'rev-happy'],
      rivals: ['ford-focus-mk2', 'volkswagen-golf-mk5', 'toyota-auris-e150'] },

    { model: 'Civic', gen: 'FL1', years: [2022, 0], bodies: ['hatch'], segment: 'family-hatch',
      priceNew: [30000, 40000], used: [21000, 35000], accel: 7.8, power: [143, 184], top: 112,
      fuels: ['hybrid'], mpg: 56, ev: null, seats: 5, doors: 5, boot: 410, len: 4551, kg: 1430,
      mpy: 9500, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 88, drive: 78, practicality: 80, value: 74, design: 74, running: 88 },
      verdict: 'Quietly the best family hatch on sale: gorgeous to steer, 56mpg real-world, built like a Swiss bank vault.',
      issues: ['Only one powertrain', 'Not cheap new'],
      buy: 'Sport grade — the Goldilocks trim.',
      tags: ['bulletproof', 'drivers-car', 'cheap-to-run', 'crowd-pleaser', 'motorway-muncher'],
      rivals: ['toyota-corolla-e210', 'volkswagen-golf-mk8', 'mazda-3-bp'] },

    { model: 'Civic Type R', gen: 'FK8', years: [2017, 2022], bodies: ['hatch'], segment: 'hot-hatch',
      priceNew: [32000, 40000], used: [24000, 38000], accel: 5.8, power: [320, 320], top: 169,
      fuels: ['petrol'], mpg: 33, ev: null, seats: 4, doors: 5, boot: 420, len: 4557, kg: 1380,
      mpy: 6500, ncap: [5, 2022], onSale: false, halo: false,
      g: { build: 86, drive: 94, practicality: 74, value: 78, design: 66, running: 62 },
      verdict: 'The front-drive benchmark — Ring-record pace with a boot for the dog. The wing embarrasses; the chassis apologises.',
      issues: ['Styling shouts', 'Good ones tracked — inspect'],
      buy: 'GT spec, standard, history stamped. Ignore the memes.',
      tags: ['drivers-car', 'track-day', 'pocket-rocket', 'b-road-hero', 'future-classic', 'dog-friendly'],
      rivals: ['volkswagen-golf-gti-mk7', 'ford-focus-rs-mk3', 'hyundai-i30-n-pd'] },

    { model: 'Civic Type R', gen: 'FL5', years: [2023, 0], bodies: ['hatch'], segment: 'hot-hatch',
      priceNew: [47000, 52000], used: [38000, 48000], accel: 5.4, power: [329, 329], top: 171,
      fuels: ['petrol'], mpg: 34, ev: null, seats: 4, doors: 5, boot: 410, len: 4594, kg: 1430,
      mpy: 6000, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 88, drive: 96, practicality: 74, value: 70, design: 76, running: 60 },
      verdict: 'The best front-driven car ever made, wearing sensible trousers at last. £50k for a Civic — and worth it.',
      issues: ['Price of a used Cayman', 'Allocation games'],
      buy: 'Championship White, no options needed. Keep miles honest.',
      tags: ['drivers-car', 'track-day', 'future-classic', 'b-road-hero', 'pocket-rocket'],
      rivals: ['toyota-gr-yaris-xp210', 'mercedes-amg-a45-w177', 'volkswagen-golf-r-mk8'] },

    { model: 'CR-V', gen: 'RW', years: [2018, 2023], bodies: ['suv'], segment: 'family-suv',
      priceNew: [28000, 40000], used: [16000, 32000], accel: 8.8, power: [173, 184], top: 112,
      fuels: ['petrol', 'hybrid'], mpg: 48, ev: null, seats: 7, doors: 5, boot: 561, len: 4600, kg: 1615,
      mpy: 10500, ncap: [5, 2019], onSale: false, halo: false,
      g: { build: 86, drive: 64, practicality: 86, value: 78, design: 58, running: 84 },
      verdict: 'The family SUV your mechanic would buy. Vast inside, hybrid frugal, dull as ditchwater and proud of it.',
      issues: ['CVT moo under load', '7-seat version tight in row three'],
      buy: 'Hybrid EX AWD — the 200,000-mile family plan.',
      tags: ['bulletproof', 'school-run', 'tardis', 'cheap-to-run', 'dog-friendly'],
      rivals: ['toyota-rav4-xa50', 'mazda-cx-5-kf', 'volkswagen-tiguan-ad'] },

    { model: 'HR-V', gen: 'RV', years: [2021, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [27000, 33000], used: [16000, 28000], accel: 10.6, power: [131, 131], top: 107,
      fuels: ['hybrid'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 319, len: 4340, kg: 1380,
      mpy: 8500, ncap: [4, 2022], onSale: true, halo: false,
      g: { build: 84, drive: 62, practicality: 78, value: 72, design: 70, running: 88 },
      verdict: 'Magic Seats meet crossover practicality. Slow, serene and sensible — ownership as a warm bath.',
      issues: ['Leisurely performance', 'Boot smaller than rivals'],
      buy: 'Advance — heated everything, hybrid sips fuel.',
      tags: ['city-darling', 'bulletproof', 'cheap-to-run', 'school-run'],
      rivals: ['toyota-c-hr-ax10', 'nissan-juke-f16', 'volkswagen-t-roc-a11'] },

    { model: 'e', gen: 'ZE1', years: [2020, 2024], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [30000, 34000], used: [11000, 18000], accel: 8.3, power: [136, 154], top: 90,
      fuels: ['ev'], mpg: null, ev: 137, seats: 4, doors: 5, boot: 171, len: 3894, kg: 1520,
      mpy: 5000, ncap: [4, 2020], onSale: false, halo: false,
      g: { build: 84, drive: 74, practicality: 44, value: 62, design: 92, running: 84 },
      verdict: 'The cutest EV ever sold and a commercial flop — 137 miles killed it. As a second city car, it is pure joy.',
      issues: ['Range is genuinely tiny', 'Was wildly overpriced new'],
      buy: 'Advance used at half price — the design-classic city pod.',
      tags: ['city-darling', 'retro-charm', 'future-classic', 'head-turner', 'left-field', 'minimalist'],
      rivals: ['bmw-i3-i01', 'fiat-500e-332', 'mini-electric-f56'] },

    { model: 'NSX', gen: 'NC1', years: [2016, 2022], bodies: ['coupe'], segment: 'super-coupe',
      priceNew: [140000, 170000], used: [85000, 130000], accel: 2.9, power: [581, 610], top: 191,
      fuels: ['hybrid'], mpg: 26, ev: null, seats: 2, doors: 2, boot: 110, len: 4487, kg: 1780,
      mpy: 3000, ncap: null, onSale: false, halo: true,
      g: { build: 90, drive: 88, practicality: 30, value: 62, design: 84, running: 44 },
      verdict: 'The thinking person’s hybrid supercar, ignored by the market — which is precisely why used ones tempt.',
      issues: ['Dealer network thin for servicing', 'Depreciated hard (buyer’s friend)'],
      buy: 'Any tidy UK-supplied car — rarity will age well.',
      tags: ['left-field', 'future-classic', 'tech-fest', 'head-turner', 'silent-cruiser'],
      rivals: ['audi-r8-4s', 'porsche-911-991', 'mclaren-570s-p13'] },

    { model: 'ZR-V', gen: 'RZ', years: [2023, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [40000, 45000], used: [28000, 38000], accel: 7.8, power: [184, 184], top: 108,
      fuels: ['hybrid'], mpg: 49, ev: null, seats: 5, doors: 5, boot: 380, len: 4568, kg: 1590,
      mpy: 9500, ncap: [4, 2023], onSale: true, halo: false,
      g: { build: 86, drive: 74, practicality: 74, value: 68, design: 64, running: 84 },
      verdict: 'A Civic on stilts — which makes it the best-driving Honda SUV. Priced brave, drives lovely, will outlast us all.',
      issues: ['Small boot for the class', 'Anonymous styling'],
      buy: 'Sport grade — the driver’s pick of sensible SUVs.',
      tags: ['bulletproof', 'drivers-car', 'school-run', 'cheap-to-run'],
      rivals: ['toyota-rav4-xa50', 'mazda-cx-5-kf', 'kia-sportage-nq5'] },

    { model: 'S2000', gen: 'AP1', years: [1999, 2009], bodies: ['convertible'], segment: 'roadster-classic',
      priceNew: [27000, 30000], used: [12000, 30000], accel: 6.2, power: [237, 240], top: 150,
      fuels: ['petrol'], mpg: 28, ev: null, seats: 2, doors: 2, boot: 154, len: 4135, kg: 1260,
      mpy: 4000, ncap: null, onSale: false, halo: false,
      g: { build: 86, drive: 92, practicality: 34, value: 78, design: 80, running: 60 },
      verdict: '9,000rpm of VTEC violin and a gearshift from the gods. Values only go one way now — the analogue endgame.',
      issues: ['Rust in rear arches', 'Snap oversteer pre-facelift — respect it'],
      buy: 'AP2 (2004-on) UK car, stock, hood unripped, history thick.',
      tags: ['modern-classic', 'analogue-joy', 'rev-happy', 'drivers-car', 'future-classic', 'lightweight'],
      rivals: ['mazda-mx-5-nb', 'porsche-boxster-987', 'nissan-350z-z33'] }
  ]
};
