// Hyundai — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Hyundai',
  cars: [
    { model: 'i10', gen: 'AC3', years: [2020, 0], bodies: ['hatch'], segment: 'city',
      priceNew: [13000, 18000], used: [7500, 15000], accel: 10.5, power: [63, 100], top: 112,
      fuels: ['petrol'], mpg: 53, ev: null, seats: 4, doors: 5, boot: 252, len: 3670, kg: 955,
      mpy: 6000, ncap: [3, 2020], onSale: true, halo: false,
      g: { build: 78, drive: 66, practicality: 62, value: 84, design: 64, running: 92 },
      verdict: 'The grown-up city car: five-year warranty, big-car feel, pocket-money bills. The sensible list starts here.',
      issues: ['Three-star NCAP (adult occupant fine)', 'N Line firm on scars'],
      buy: '1.0 MPi Premium — heated wheel in a city car, why not.',
      tags: ['city-darling', 'first-car-friendly', 'cheap-to-run', 'bargain-hero', 'crowd-pleaser'],
      rivals: ['kia-picanto-ja', 'toyota-aygo-x-ab70', 'volkswagen-up-aa'] },

    { model: 'i20', gen: 'BC3', years: [2020, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [18000, 26000], used: [11000, 22000], accel: 6.2, power: [84, 204], top: 143,
      fuels: ['petrol', 'hybrid'], mpg: 55, ev: null, seats: 5, doors: 5, boot: 352, len: 4040, kg: 1120,
      mpy: 8000, ncap: [4, 2021], onSale: true, halo: false,
      g: { build: 78, drive: 72, practicality: 72, value: 80, design: 68, running: 84 },
      verdict: 'Quietly excellent supermini with a big boot and long warranty. The N version is the fireworks display.',
      issues: ['Busy dashboard graphics', 'Firm N Line springs'],
      buy: '1.0 T-GDi 100 Premium — all the car most people need.',
      tags: ['first-car-friendly', 'cheap-to-run', 'crowd-pleaser', 'bargain-hero'],
      rivals: ['ford-fiesta-mk8', 'volkswagen-polo-mk6', 'renault-clio-v'] },

    { model: 'i20 N', gen: 'BC3', years: [2021, 2024], bodies: ['hatch'], segment: 'hot-hatch',
      priceNew: [25000, 27000], used: [17000, 24000], accel: 6.2, power: [204, 204], top: 143,
      fuels: ['petrol'], mpg: 40, ev: null, seats: 5, doors: 5, boot: 352, len: 4075, kg: 1190,
      mpy: 7000, ncap: [4, 2021], onSale: false, halo: false,
      g: { build: 80, drive: 91, practicality: 66, value: 84, design: 70, running: 74 },
      verdict: 'The spiritual Fiesta ST successor — fizzy, riotous, rev-matched manual joy. Killed young; buy one while you can.',
      issues: ['Firm ride is the price of entry', 'Short production run'],
      buy: 'Any one you can find, Performance Blue, standard.',
      tags: ['pocket-rocket', 'drivers-car', 'b-road-hero', 'future-classic', 'analogue-joy', 'bargain-hero'],
      rivals: ['ford-fiesta-mk8', 'toyota-gr-yaris-xp210', 'volkswagen-polo-gti-mk6'] },

    { model: 'i30 N', gen: 'PD', years: [2017, 2024], bodies: ['hatch'], segment: 'hot-hatch',
      priceNew: [28000, 36000], used: [15000, 28000], accel: 5.9, power: [250, 280], top: 155,
      fuels: ['petrol'], mpg: 36, ev: null, seats: 5, doors: 5, boot: 381, len: 4335, kg: 1400,
      mpy: 7500, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 80, drive: 88, practicality: 74, value: 86, design: 66, running: 68 },
      verdict: 'Hyundai’s first hot hatch and instantly one of the best: exuberant, adjustable, warrantied. Used ones are a steal.',
      issues: ['First-gen infotainment dated', 'Standard cars lack the e-diff — get Performance'],
      buy: 'Performance Pack manual, post-2021 facelift with the DCT if preferred.',
      tags: ['pocket-rocket', 'drivers-car', 'b-road-hero', 'bargain-hero', 'track-day', 'crowd-pleaser'],
      rivals: ['volkswagen-golf-gti-mk7', 'honda-civic-type-r-fk8', 'ford-focus-st-mk4'] },

    { model: 'i30', gen: 'PD', years: [2017, 2024], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [19000, 28000], used: [9000, 21000], accel: 8.9, power: [110, 159], top: 119,
      fuels: ['petrol', 'hybrid'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 395, len: 4340, kg: 1300,
      mpy: 9000, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 78, drive: 66, practicality: 76, value: 80, design: 60, running: 82 },
      verdict: 'The quiet golf-club Golf. Nothing remarkable except the warranty, the price and the way it never goes wrong.',
      issues: ['Forgettable to drive', 'Trim rattles at big miles'],
      buy: 'Tourer 1.0 T-GDi Premium — wagon practicality, city bills.',
      tags: ['crowd-pleaser', 'cheap-to-run', 'bargain-hero', 'dog-friendly'],
      rivals: ['kia-ceed-cd', 'toyota-corolla-e210', 'skoda-octavia-mk4'] },

    { model: 'Tucson', gen: 'NX4', years: [2021, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [30000, 43000], used: [17000, 36000], accel: 8.0, power: [150, 265], top: 120,
      fuels: ['petrol', 'hybrid', 'phev'], mpg: 49, ev: 38, seats: 5, doors: 5, boot: 620, len: 4500, kg: 1560,
      mpy: 10500, ncap: [5, 2021], onSale: true, halo: false,
      g: { build: 82, drive: 68, practicality: 86, value: 82, design: 80, running: 80 },
      verdict: 'The origami-faced SUV that made Hyundai desirable. Huge boot, hybrid choice, warranty for days — deserved best-seller.',
      issues: ['Ride busy on 19s', 'PHEV boot loses some depth'],
      buy: 'Hybrid Premium — the family default, upgraded.',
      tags: ['school-run', 'crowd-pleaser', 'head-turner', 'tardis', 'cheap-to-run'],
      rivals: ['kia-sportage-nq5', 'toyota-rav4-xa50', 'nissan-qashqai-j12'] },

    { model: 'Santa Fe', gen: 'TM', years: [2018, 2024], bodies: ['suv'], segment: 'seven-seater',
      priceNew: [38000, 50000], used: [20000, 40000], accel: 8.8, power: [200, 265], top: 116,
      fuels: ['diesel', 'hybrid', 'phev'], mpg: 42, ev: 36, seats: 7, doors: 5, boot: 571, len: 4785, kg: 1810,
      mpy: 10500, ncap: [5, 2018], onSale: false, halo: false,
      g: { build: 82, drive: 64, practicality: 90, value: 82, design: 66, running: 74 },
      verdict: 'Seven proper seats, premium-adjacent cabin, half a Discovery’s price. The family bus the badge snobs miss.',
      issues: ['Diesel gruff cold', 'Middle-row belts fiddly with child seats'],
      buy: 'Hybrid Ultimate 7-seat — leather-lined logistics.',
      tags: ['seven-seats', 'family-bus', 'tardis', 'bargain-hero', 'tow-car', 'dog-friendly'],
      rivals: ['kia-sorento-mq4', 'skoda-kodiaq-ns7', 'peugeot-5008-p87'] },

    { model: 'Santa Fe', gen: 'MX5', years: [2024, 0], bodies: ['suv'], segment: 'seven-seater',
      priceNew: [47000, 58000], used: [38000, 52000], accel: 9.3, power: [215, 253], top: 112,
      fuels: ['hybrid', 'phev'], mpg: 43, ev: 34, seats: 7, doors: 5, boot: 628, len: 4830, kg: 1935,
      mpy: 10500, ncap: [5, 2024], onSale: true, halo: false,
      g: { build: 84, drive: 62, practicality: 92, value: 74, design: 84, running: 76 },
      verdict: 'Went full Tonka-box and became an instant style object. The Range Rover silhouette for school-run money.',
      issues: ['Divisive rear-end design', 'No diesel for towing folk'],
      buy: 'Hybrid Calligraphy 7-seat in matte green — commit.',
      tags: ['boxy-icon', 'seven-seats', 'family-bus', 'head-turner', 'tardis'],
      rivals: ['kia-ev9-mv', 'skoda-kodiaq-ns8', 'land-rover-discovery-sport-l550'] },

    { model: 'Ioniq 5', gen: 'NE', years: [2021, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [40000, 58000], used: [19000, 42000], accel: 5.1, power: [170, 325], top: 115,
      fuels: ['ev'], mpg: null, ev: 315, seats: 5, doors: 5, boot: 527, len: 4635, kg: 1985,
      mpy: 9000, ncap: [5, 2021], onSale: true, halo: false,
      g: { build: 84, drive: 74, practicality: 84, value: 80, design: 92, running: 84 },
      verdict: '8-bit concept-car looks, lounge interior, 350kW charging. The EV that made everyone else look timid.',
      issues: ['No rear wiper pre-facelift', 'Soft brake feel'],
      buy: '77kWh RWD Premium — range, price and pace in balance.',
      tags: ['head-turner', 'retro-charm', 'tech-fest', 'silent-cruiser', 'school-run', 'future-classic'],
      rivals: ['kia-ev6-cv', 'tesla-model-y-juniper', 'ford-mustang-mach-e-cx727'] },

    { model: 'Ioniq 5 N', gen: 'NE', years: [2024, 0], bodies: ['suv'], segment: 'hot-hatch',
      priceNew: [65000, 68000], used: [45000, 60000], accel: 3.4, power: [650, 650], top: 161,
      fuels: ['ev'], mpg: null, ev: 278, seats: 5, doors: 5, boot: 480, len: 4715, kg: 2230,
      mpy: 7000, ncap: [5, 2021], onSale: true, halo: false,
      g: { build: 86, drive: 92, practicality: 78, value: 68, design: 86, running: 72 },
      verdict: 'The first EV that genuinely giggles — fake gears, drift mode, 650bhp. The future of fun, arrived early.',
      issues: ['2.2 tonnes is 2.2 tonnes', 'Range drops when you use it as intended'],
      buy: 'Standard car, Performance Blue matte if brave.',
      tags: ['pocket-rocket', 'tech-fest', 'head-turner', 'track-day', 'future-classic', 'silent-cruiser'],
      rivals: ['tesla-model-3-performance-highland', 'bmw-i4-g26', 'kia-ev6-gt-cv'] },

    { model: 'Ioniq 6', gen: 'CE', years: [2022, 0], bodies: ['saloon'], segment: 'ev-native',
      priceNew: [47000, 55000], used: [24000, 40000], accel: 5.1, power: [151, 325], top: 115,
      fuels: ['ev'], mpg: null, ev: 338, seats: 5, doors: 4, boot: 401, len: 4855, kg: 1985,
      mpy: 9500, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 84, drive: 72, practicality: 66, value: 78, design: 76, running: 88 },
      verdict: 'The streamliner: slippery shape, huge real-world efficiency, oddball charm. The aero nerd’s Tesla alternative.',
      issues: ['Rear headroom under that roofline', 'Small boot opening'],
      buy: '77kWh RWD Premium — 300+ real miles, rapid charging.',
      tags: ['sleek', 'silent-cruiser', 'cheap-to-run', 'left-field', 'tech-fest'],
      rivals: ['tesla-model-3-highland', 'bmw-i4-g26', 'polestar-2-p2'] },

    { model: 'Kona', gen: 'SX2', years: [2023, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [26000, 43000], used: [16000, 34000], accel: 7.8, power: [120, 218], top: 107,
      fuels: ['petrol', 'hybrid', 'ev'], mpg: 52, ev: 319, seats: 5, doors: 5, boot: 466, len: 4350, kg: 1415,
      mpy: 9000, ncap: [4, 2023], onSale: true, halo: false,
      g: { build: 80, drive: 66, practicality: 78, value: 78, design: 74, running: 86 },
      verdict: 'Pick a powertrain, any powertrain. The EV does 300 miles; the hybrid does sense. Family-friendly either way.',
      issues: ['Light steering', 'EV top trims price near bigger cars'],
      buy: 'Kona Electric 65kWh Advance — the everyday EV done right.',
      tags: ['school-run', 'cheap-to-run', 'crowd-pleaser', 'silent-cruiser'],
      rivals: ['kia-niro-sg2', 'toyota-c-hr-ax10', 'volkswagen-t-roc-a11'] }
  ]
};
