// Jaguar — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Jaguar',
  cars: [
    { model: 'XE', gen: 'X760', years: [2015, 2024], bodies: ['saloon'], segment: 'compact-exec',
      priceNew: [27000, 45000], used: [10000, 30000], accel: 5.7, power: [163, 300], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 52, ev: null, seats: 5, doors: 4, boot: 410, len: 4678, kg: 1530,
      mpy: 9500, ncap: [5, 2015], onSale: false, halo: false,
      g: { build: 74, drive: 84, practicality: 66, value: 80, design: 78, running: 68 },
      verdict: 'Sweeter to steer than a 3 Series, cheaper to buy used, tighter in the back. The underdog that deserved better.',
      issues: ['Rear space and boot trail rivals', 'Early Ingenium diesel history matters'],
      buy: 'P250 R-Dynamic 2020-on — the polished late car.',
      tags: ['drivers-car', 'bargain-hero', 'sleek', 'left-field', 'discreet'],
      rivals: ['bmw-3-series-g20', 'alfa-romeo-giulia-952', 'audi-a4-b9'] },

    { model: 'XF', gen: 'X250', years: [2008, 2015], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [33000, 50000], used: [4500, 14000], accel: 4.9, power: [163, 510], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 46, ev: null, seats: 5, doors: 4, boot: 540, len: 4961, kg: 1660,
      mpy: 10000, ncap: [4, 2011], onSale: false, halo: false,
      g: { build: 74, drive: 78, practicality: 76, value: 82, design: 82, running: 58 },
      verdict: 'The car that saved Jaguar — rotating vents, whisky-bar cabin, 3.0d muscle. XFR is a £15k super-saloon secret.',
      issues: ['Timing chain tensioners on early 5.0s', 'Electrics age — check everything'],
      buy: '3.0d S Portfolio Sportbrake — grace, pace, £12k.',
      tags: ['bargain-hero', 'wafty', 'sleek', 'motorway-muncher', 'head-turner', 'v8-soundtrack'],
      rivals: ['bmw-5-series-f10', 'mercedes-benz-e-class-w212', 'audi-a6-c7'] },

    { model: 'F-Type', gen: 'X152', years: [2013, 2024], bodies: ['coupe', 'convertible'], segment: 'sports',
      priceNew: [52000, 100000], used: [25000, 70000], accel: 3.5, power: [300, 575], top: 186,
      fuels: ['petrol'], mpg: 27, ev: null, seats: 2, doors: 2, boot: 336, len: 4470, kg: 1545,
      mpy: 4500, ncap: null, onSale: false, halo: false,
      g: { build: 78, drive: 86, practicality: 36, value: 78, design: 94, running: 42 },
      verdict: 'The loudest, prettiest thing Britain built this century. V8 R used costs Cayman money and sounds like a war.',
      issues: ['Thirst is operatic too', 'Check supercharger service history'],
      buy: 'V8 R AWD coupé — the full theatre, before they’re gone.',
      tags: ['head-turner', 'v8-soundtrack', 'grand-tourer', 'future-classic', 'drivers-car', 'sleek'],
      rivals: ['porsche-911-991', 'mercedes-amg-gt-c190', 'bmw-m4-f82'] },

    { model: 'F-Pace', gen: 'X761', years: [2016, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [40000, 60000], used: [16000, 48000], accel: 4.0, power: [163, 550], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 44, ev: 33, seats: 5, doors: 5, boot: 650, len: 4746, kg: 1760,
      mpy: 10000, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 76, drive: 80, practicality: 82, value: 76, design: 84, running: 54 },
      verdict: 'The Jag SUV that drives like a Jag should. SVR is a bellowing bargain; diesels do the school run with grace.',
      issues: ['Infotainment pre-Pivi frustrates', 'Ingenium history check'],
      buy: 'D300 R-Dynamic SE facelift — polish and pace.',
      tags: ['drivers-car', 'head-turner', 'school-run', 'sleek', 'dog-friendly'],
      rivals: ['porsche-macan-95b', 'bmw-x3-g01', 'alfa-romeo-stelvio-949'] },

    { model: 'I-Pace', gen: 'X590', years: [2018, 2024], bodies: ['suv'], segment: 'ev-native',
      priceNew: [65000, 75000], used: [16000, 32000], accel: 4.8, power: [400, 400], top: 124,
      fuels: ['ev'], mpg: null, ev: 292, seats: 5, doors: 5, boot: 656, len: 4682, kg: 2133,
      mpy: 8500, ncap: [5, 2018], onSale: false, halo: false,
      g: { build: 76, drive: 80, practicality: 78, value: 74, design: 86, running: 76 },
      verdict: 'World Car of the Year 2019, now 75% off. Beautiful, quick, occasionally buggy — the used EV gamble worth taking.',
      issues: ['Software/charging gremlins — get the recalls done', 'Real range nearer 230'],
      buy: 'HSE with full JLR history and battery health report.',
      tags: ['head-turner', 'depreciation-king', 'silent-cruiser', 'bargain-hero', 'sleek', 'left-field'],
      rivals: ['audi-e-tron-ge', 'mercedes-benz-eqc-n293', 'tesla-model-x-classic'] },

    { model: 'XJ', gen: 'X351', years: [2010, 2019], bodies: ['saloon'], segment: 'luxury',
      priceNew: [56000, 95000], used: [12000, 35000], accel: 4.9, power: [275, 575], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 40, ev: null, seats: 5, doors: 4, boot: 520, len: 5127, kg: 1755,
      mpy: 8000, ncap: null, onSale: false, halo: false,
      g: { build: 76, drive: 80, practicality: 74, value: 78, design: 88, running: 44 },
      verdict: 'The limo for people who drive themselves — a leaping cat in a world of sombre suits. XJR 575 is gloriously unhinged.',
      issues: ['Air suspension and electronics age', 'V6 diesel timing chains'],
      buy: '3.0d Portfolio LWB — clubhouse rear, hot-hatch bills (almost).',
      tags: ['wafty', 'head-turner', 'sleek', 'depreciation-king', 'left-field', 'money-pit-risk'],
      rivals: ['mercedes-benz-s-class-w222', 'bmw-7-series-g11', 'audi-a8-d4'] },

    { model: 'XK', gen: 'X150', years: [2006, 2014], bodies: ['coupe', 'convertible'], segment: 'super-coupe',
      priceNew: [60000, 85000], used: [16000, 35000], accel: 4.6, power: [300, 550], top: 155,
      fuels: ['petrol'], mpg: 25, ev: null, seats: 4, doors: 2, boot: 330, len: 4794, kg: 1660,
      mpy: 4000, ncap: null, onSale: false, halo: false,
      g: { build: 76, drive: 80, practicality: 44, value: 80, design: 86, running: 40 },
      verdict: 'Aluminium grand touring with a V8 growl, at hot-hatch prices. The XKR is the gentleman thug of the used market.',
      issues: ['Corrosion around screen surrounds', 'Supercharger service records'],
      buy: 'XKR 5.0 coupé — continent-crushing theatre for £25k.',
      tags: ['grand-tourer', 'v8-soundtrack', 'modern-classic', 'bargain-hero', 'head-turner', 'future-classic'],
      rivals: ['porsche-911-997', 'aston-martin-v8-vantage-classic', 'mercedes-benz-sl-r230'] }
  ]
};
