// Jeep — model-generations, UK market. Curated for Vroom. (Dacia in dacia.mjs)
export default {
  make: 'Jeep',
  cars: [
    { model: 'Wrangler', gen: 'JK', years: [2007, 2018], bodies: ['suv'], segment: 'off-roader',
      priceNew: [28000, 40000], used: [15000, 30000], accel: 8.9, power: [200, 284], top: 112,
      fuels: ['petrol', 'diesel'], mpg: 28, ev: null, seats: 5, doors: 5, boot: 498, len: 4751, kg: 1905,
      mpy: 7000, ncap: null, onSale: false, halo: false,
      g: { build: 74, drive: 44, practicality: 68, value: 72, design: 88, running: 40 },
      verdict: 'Doors off, roof off, worries off. Terrible on the M25, magnificent everywhere Instagram lives. An icon at play.',
      issues: ['Death-wobble front ends need bushes', 'Rust underneath UK cars'],
      buy: 'JK Unlimited 2.8 CRD Sahara — the usable one.',
      tags: ['boxy-icon', 'go-anywhere', 'off-grid', 'head-turner', 'chunky-4x4', 'adventure-ready', 'analogue-joy'],
      rivals: ['land-rover-defender-classic', 'toyota-land-cruiser-j150', 'suzuki-jimny-jb74'] },

    { model: 'Wrangler', gen: 'JL', years: [2018, 0], bodies: ['suv'], segment: 'off-roader',
      priceNew: [50000, 65000], used: [32000, 55000], accel: 6.4, power: [272, 380], top: 112,
      fuels: ['petrol', 'phev'], mpg: 25, ev: 26, seats: 5, doors: 5, boot: 533, len: 4882, kg: 2110,
      mpy: 7000, ncap: [1, 2018], onSale: true, halo: false,
      g: { build: 76, drive: 52, practicality: 72, value: 64, design: 90, running: 38 },
      verdict: 'Still the only convertible 4x4 with real rock-crawling chops. One-star NCAP, five-star grin — know the deal.',
      issues: ['One-star Euro NCAP (2018)', 'Wanders on motorways'],
      buy: 'Rubicon 4xe — silent trails, tax relief, maximum Jeep.',
      tags: ['boxy-icon', 'go-anywhere', 'off-grid', 'head-turner', 'chunky-4x4', 'adventure-ready'],
      rivals: ['land-rover-defender-l663', 'ineos-grenadier-b52', 'ford-bronco-u725'] },

    { model: 'Renegade', gen: 'BU', years: [2015, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [19000, 32000], used: [8000, 22000], accel: 8.9, power: [110, 240], top: 122,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 47, ev: 26, seats: 5, doors: 5, boot: 351, len: 4236, kg: 1320,
      mpy: 8500, ncap: [5, 2014], onSale: true, halo: false,
      g: { build: 70, drive: 62, practicality: 72, value: 74, design: 78, running: 74 },
      verdict: 'The cute-ute with Easter-egg Jeeps hidden in every panel. Trailhawk actually goes off-road; most never will.',
      issues: ['DDCT gearbox history', 'Italian-American electrics'],
      buy: '4xe Trailhawk for trails; 1.0 GSE Limited for town.',
      tags: ['boxy-icon', 'city-darling', 'retro-charm', 'go-anywhere', 'left-field'],
      rivals: ['suzuki-vitara-ly', 'fiat-500x-334', 'mini-countryman-f60'] },

    { model: 'Grand Cherokee', gen: 'WK2', years: [2011, 2021], bodies: ['suv'], segment: 'large-suv',
      priceNew: [38000, 70000], used: [12000, 35000], accel: 3.7, power: [190, 710], top: 180,
      fuels: ['petrol', 'diesel'], mpg: 34, ev: null, seats: 5, doors: 5, boot: 782, len: 4822, kg: 2270,
      mpy: 9000, ncap: [4, 2011], onSale: false, halo: false,
      g: { build: 70, drive: 66, practicality: 84, value: 78, design: 70, running: 38 },
      verdict: 'America’s Range Rover at half the ticket. The Trackhawk is a 710bhp dare; the diesel a towing workhorse.',
      issues: ['Electrics and interior wear', 'Air suspension age'],
      buy: '3.0 CRD Summit — or the SRT for V8 comedy.',
      tags: ['muscular', 'tow-car', 'bargain-hero', 'left-field', 'chunky-4x4', 'v8-soundtrack'],
      rivals: ['land-rover-discovery-l462', 'volkswagen-touareg-cr', 'bmw-x5-f15'] },

    { model: 'Avenger', gen: 'JJ', years: [2023, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [25000, 32000], used: [16000, 26000], accel: 9.0, power: [100, 156], top: 112,
      fuels: ['petrol', 'ev'], mpg: 50, ev: 249, seats: 5, doors: 5, boot: 355, len: 4084, kg: 1520,
      mpy: 8000, ncap: [3, 2024], onSale: true, halo: false,
      g: { build: 74, drive: 64, practicality: 68, value: 78, design: 80, running: 84 },
      verdict: 'Europe’s Car of the Year in Tonka-toy form — tiny, chunky, charming. The e-Avenger is the style pick of small EVs.',
      issues: ['Rear seat snug', 'Three-star NCAP'],
      buy: 'Avenger Electric Summit — maximum toy-box energy.',
      tags: ['boxy-icon', 'city-darling', 'head-turner', 'retro-charm', 'cheap-to-run'],
      rivals: ['volvo-ex30-y1', 'suzuki-jimny-jb74', 'peugeot-2008-p24'] }
  ]
};
