// Kia — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Kia',
  cars: [
    { model: 'Picanto', gen: 'JA', years: [2017, 0], bodies: ['hatch'], segment: 'city',
      priceNew: [11000, 17000], used: [6000, 14000], accel: 11.6, power: [67, 100], top: 112,
      fuels: ['petrol'], mpg: 52, ev: null, seats: 4, doors: 5, boot: 255, len: 3595, kg: 935,
      mpy: 6000, ncap: [3, 2017], onSale: true, halo: false,
      g: { build: 76, drive: 64, practicality: 60, value: 86, design: 66, running: 92 },
      verdict: 'Seven-year warranty on a city car — maths that ends arguments. Cheerful, tiny, tougher than it needs to be.',
      issues: ['Motorway hum', 'Three-star NCAP'],
      buy: 'GT-Line 1.0 — the fun trim on the sensible car.',
      tags: ['city-darling', 'first-car-friendly', 'cheap-to-run', 'bargain-hero'],
      rivals: ['hyundai-i10-ac3', 'toyota-aygo-x-ab70', 'volkswagen-up-aa'] },

    { model: 'Ceed', gen: 'CD', years: [2018, 0], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [19000, 29000], used: [10000, 24000], accel: 7.5, power: [100, 204], top: 130,
      fuels: ['petrol', 'phev'], mpg: 50, ev: 35, seats: 5, doors: 5, boot: 395, len: 4310, kg: 1275,
      mpy: 9000, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 78, drive: 68, practicality: 78, value: 82, design: 62, running: 82 },
      verdict: 'The rational family hatch: seven-year warranty, honest money, zero pretension. The SW estate is the smart buy.',
      issues: ['Cabin plastics functional', 'DCT hesitation in town'],
      buy: 'Sportswagon 1.5 T-GDi GT-Line — space and warranty for less.',
      tags: ['bargain-hero', 'cheap-to-run', 'dog-friendly', 'crowd-pleaser'],
      rivals: ['hyundai-i30-pd', 'skoda-octavia-mk4', 'toyota-corolla-e210'] },

    { model: 'Sportage', gen: 'NQ5', years: [2022, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [28000, 45000], used: [18000, 38000], accel: 7.9, power: [150, 265], top: 120,
      fuels: ['petrol', 'hybrid', 'phev'], mpg: 48, ev: 43, seats: 5, doors: 5, boot: 591, len: 4515, kg: 1595,
      mpy: 10500, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 82, drive: 68, practicality: 86, value: 84, design: 78, running: 80 },
      verdict: 'Britain’s best-seller lists exist because of cars like this: bold face, big boot, seven-year safety net. Complete.',
      issues: ['Boomerang DRLs divide dinner tables', 'Base engines merely adequate'],
      buy: 'Hybrid GT-Line — the spec that holds its money.',
      tags: ['school-run', 'crowd-pleaser', 'tardis', 'cheap-to-run', 'head-turner'],
      rivals: ['hyundai-tucson-nx4', 'nissan-qashqai-j12', 'toyota-rav4-xa50'] },

    { model: 'Sorento', gen: 'MQ4', years: [2020, 0], bodies: ['suv'], segment: 'seven-seater',
      priceNew: [42000, 55000], used: [25000, 46000], accel: 8.7, power: [194, 265], top: 119,
      fuels: ['diesel', 'hybrid', 'phev'], mpg: 42, ev: 35, seats: 7, doors: 5, boot: 616, len: 4810, kg: 1885,
      mpy: 10500, ncap: [5, 2020], onSale: true, halo: false,
      g: { build: 84, drive: 66, practicality: 92, value: 80, design: 74, running: 74 },
      verdict: 'Seven real seats, premium finish, warranty to 2032. The Discovery for people who read the reliability surveys.',
      issues: ['Not small in town', 'PHEV tow limit lower'],
      buy: 'Hybrid Edition 7-seat — the family flagship without the flagship bills.',
      tags: ['seven-seats', 'family-bus', 'tardis', 'tow-car', 'crowd-pleaser', 'dog-friendly'],
      rivals: ['hyundai-santa-fe-tm', 'skoda-kodiaq-ns7', 'volvo-xc90-p2'] },

    { model: 'Niro', gen: 'SG2', years: [2022, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [28000, 42000], used: [16000, 34000], accel: 7.8, power: [141, 204], top: 104,
      fuels: ['hybrid', 'phev', 'ev'], mpg: 60, ev: 285, seats: 5, doors: 5, boot: 451, len: 4420, kg: 1470,
      mpy: 9500, ncap: [4, 2022], onSale: true, halo: false,
      g: { build: 80, drive: 62, practicality: 80, value: 82, design: 68, running: 90 },
      verdict: 'Pick your electrons: 60mpg hybrid, plug-in, or 285-mile EV in one sensible suit. Minicab fleets know best.',
      issues: ['Anodyne to drive', 'EV charging speed mid-pack'],
      buy: 'Niro EV 3 — the rational family electric.',
      tags: ['cheap-to-run', 'school-run', 'crowd-pleaser', 'silent-cruiser', 'bulletproof'],
      rivals: ['hyundai-kona-sx2', 'toyota-c-hr-ax10', 'mg-zs-ev-zs11'] },

    { model: 'EV6', gen: 'CV', years: [2021, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [42000, 62000], used: [22000, 45000], accel: 3.5, power: [229, 585], top: 161,
      fuels: ['ev'], mpg: null, ev: 328, seats: 5, doors: 5, boot: 490, len: 4695, kg: 2005,
      mpy: 9500, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 84, drive: 80, practicality: 80, value: 80, design: 84, running: 84 },
      verdict: 'The Ioniq 5’s athletic sibling — swoopier, sharper, same 350kW party trick. GT does 0-62 in 3.5 for M3 money used.',
      issues: ['Rear visibility slot-like', 'Firm on GT-Line 20s'],
      buy: 'RWD GT-Line 77kWh; the full GT if lottery numbers land.',
      tags: ['sleek', 'silent-cruiser', 'drivers-car', 'tech-fest', 'head-turner', 'school-run'],
      rivals: ['hyundai-ioniq-5-ne', 'tesla-model-y-juniper', 'ford-mustang-mach-e-cx727'] },

    { model: 'EV9', gen: 'MV', years: [2023, 0], bodies: ['suv'], segment: 'seven-seater',
      priceNew: [65000, 78000], used: [45000, 65000], accel: 5.3, power: [204, 384], top: 124,
      fuels: ['ev'], mpg: null, ev: 349, seats: 7, doors: 5, boot: 828, len: 5015, kg: 2560,
      mpy: 10000, ncap: [5, 2023], onSale: true, halo: true,
      g: { build: 86, drive: 68, practicality: 94, value: 72, design: 88, running: 78 },
      verdict: 'The first great seven-seat EV — a concept car that escaped with the family aboard. Big money, bigger presence.',
      issues: ['It is enormous and 2.6 tonnes', 'Efficiency drops at pace'],
      buy: 'Air RWD 7-seat — the sensible spec of the statement car.',
      tags: ['boxy-icon', 'seven-seats', 'family-bus', 'head-turner', 'tech-fest', 'silent-cruiser', 'future-classic'],
      rivals: ['volvo-ex90-p3', 'mercedes-benz-eqb-x243', 'hyundai-santa-fe-mx5'] },

    { model: 'Stinger', gen: 'CK', years: [2018, 2023], bodies: ['saloon'], segment: 'exec',
      priceNew: [32000, 42000], used: [17000, 32000], accel: 4.7, power: [197, 366], top: 168,
      fuels: ['petrol', 'diesel'], mpg: 33, ev: null, seats: 5, doors: 5, boot: 406, len: 4830, kg: 1780,
      mpy: 8500, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 80, drive: 80, practicality: 74, value: 84, design: 80, running: 56 },
      verdict: 'Kia’s twin-turbo V6 gran turismo — the left-field M340i that never got its due. Rare, rapid, quietly collectible.',
      issues: ['Thirsty V6', 'Depreciated hard (your gain)'],
      buy: 'GT S 3.3 V6 — the full-fat one, always.',
      tags: ['left-field', 'grand-tourer', 'future-classic', 'bargain-hero', 'sleek', 'autobahn-stormer'],
      rivals: ['bmw-4-series-f32', 'audi-s5-b9', 'volkswagen-arteon-3h'] },

    { model: 'XCeed', gen: 'CD', years: [2019, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [23000, 33000], used: [13000, 27000], accel: 7.5, power: [120, 204], top: 124,
      fuels: ['petrol', 'phev'], mpg: 48, ev: 30, seats: 5, doors: 5, boot: 426, len: 4395, kg: 1355,
      mpy: 9000, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 78, drive: 68, practicality: 76, value: 80, design: 72, running: 80 },
      verdict: 'A Ceed in hiking boots — the crossover for people who don’t really want one. Neat, sensible, warrantied forever.',
      issues: ['PHEV boot shrinks', 'GT-Line ride firm'],
      buy: '1.5 T-GDi GT-Line S — looks the part, bills don’t.',
      tags: ['crowd-pleaser', 'school-run', 'cheap-to-run', 'city-darling'],
      rivals: ['volkswagen-t-roc-a11', 'ford-puma-mk1', 'seat-ateca-5fp'] },

    { model: 'Rio', gen: 'YB', years: [2017, 2023], bodies: ['hatch'], segment: 'supermini',
      priceNew: [13000, 19000], used: [7000, 15000], accel: 10.0, power: [84, 120], top: 118,
      fuels: ['petrol'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 325, len: 4065, kg: 1110,
      mpy: 7500, ncap: [3, 2017], onSale: false, halo: false,
      g: { build: 76, drive: 62, practicality: 72, value: 82, design: 56, running: 88 },
      verdict: 'Zero-drama supermini with warranty to spare. Not fun, not pretty, never broken — transport, distilled.',
      issues: ['Charisma bypass', 'Three-star NCAP'],
      buy: '1.0 T-GDi 2 — the fleet spec is the right spec.',
      tags: ['cheap-to-run', 'first-car-friendly', 'bargain-hero', 'bulletproof'],
      rivals: ['hyundai-i20-bc3', 'ford-fiesta-mk8', 'skoda-fabia-pj'] }
  ]
};
