// Land Rover / Range Rover — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Land Rover',
  cars: [
    { model: 'Defender', gen: 'Classic', years: [1990, 2016], bodies: ['suv', 'pickup'], segment: 'off-roader',
      priceNew: [23000, 45000], used: [15000, 60000], accel: 14.7, power: [107, 122], top: 90,
      fuels: ['diesel'], mpg: 28, ev: null, seats: 7, doors: 5, boot: 1000, len: 4599, kg: 2055,
      mpy: 5000, ncap: null, onSale: false, halo: false,
      g: { build: 74, drive: 38, practicality: 80, value: 62, design: 96, running: 40 },
      verdict: 'A farm tool that became a fashion icon. Awful to drive, impossible not to love — and values only climb.',
      issues: ['Rust: chassis and bulkhead are the car', 'Theft magnet — garage and tracker essential'],
      buy: '110 XS Station Wagon TDCi, galvanised-chassis history, or walk away.',
      tags: ['boxy-icon', 'go-anywhere', 'future-classic', 'off-grid', 'analogue-joy', 'chunky-4x4', 'head-turner'],
      rivals: ['mercedes-benz-g-class-w463', 'toyota-land-cruiser-j150', 'jeep-wrangler-jl'] },

    { model: 'Defender', gen: 'L663', years: [2020, 0], bodies: ['suv'], segment: 'off-roader',
      priceNew: [56000, 100000], used: [35000, 85000], accel: 5.2, power: [200, 525], top: 149,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 33, ev: 27, seats: 7, doors: 5, boot: 786, len: 5018, kg: 2245,
      mpy: 9000, ncap: [5, 2020], onSale: true, halo: false,
      g: { build: 82, drive: 80, practicality: 90, value: 70, design: 92, running: 42 },
      verdict: 'The rare reboot that improved the legend: genuinely superb on-road, unstoppable off it, cool in every postcode.',
      issues: ['JLR electrics — buy the warranty', 'Thirst and tyres at these masses'],
      buy: 'D250 110 SE — the sweet spot; 130 if the tribe is large.',
      tags: ['boxy-icon', 'go-anywhere', 'head-turner', 'family-bus', 'chunky-4x4', 'adventure-ready', 'tow-car', 'seven-seats'],
      rivals: ['mercedes-benz-g-class-w463a', 'toyota-land-cruiser-j250', 'ineos-grenadier-b52'] },

    { model: 'Discovery', gen: 'L319', years: [2004, 2017], bodies: ['suv'], segment: 'large-suv',
      priceNew: [33000, 55000], used: [6000, 25000], accel: 8.8, power: [190, 306], top: 121,
      fuels: ['petrol', 'diesel'], mpg: 32, ev: null, seats: 7, doors: 5, boot: 1124, len: 4838, kg: 2570,
      mpy: 9500, ncap: [4, 2006], onSale: false, halo: false,
      g: { build: 70, drive: 66, practicality: 94, value: 74, design: 78, running: 36 },
      verdict: 'Disco 3/4: seven adult seats, stadium seating, farm-to-opera range. Budget for the air suspension and love it anyway.',
      issues: ['Air suspension + crank issues on 3.0 — history is everything', 'Timing chains on early 3.0'],
      buy: 'Disco 4 3.0 SDV6 HSE 2014-on with a folder of receipts.',
      tags: ['seven-seats', 'go-anywhere', 'tow-car', 'family-bus', 'money-pit-risk', 'chunky-4x4', 'dog-friendly'],
      rivals: ['toyota-land-cruiser-j150', 'audi-q7-4m', 'volvo-xc90-p2'] },

    { model: 'Discovery', gen: 'L462', years: [2017, 0], bodies: ['suv'], segment: 'large-suv',
      priceNew: [50000, 75000], used: [22000, 60000], accel: 6.5, power: [249, 360], top: 130,
      fuels: ['petrol', 'diesel'], mpg: 36, ev: null, seats: 7, doors: 5, boot: 1137, len: 4956, kg: 2230,
      mpy: 10000, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 78, drive: 72, practicality: 94, value: 72, design: 64, running: 42 },
      verdict: 'The most complete seven-seat tow-anything family machine — if the reliability dice roll your way. Warranty, always.',
      issues: ['Electrical gremlins persist', 'Offset numberplate still upsets people'],
      buy: 'D300 Dynamic HSE, approved-used with the full JLR warranty.',
      tags: ['seven-seats', 'tow-car', 'family-bus', 'go-anywhere', 'tardis', 'money-pit-risk'],
      rivals: ['audi-q7-4m', 'bmw-x5-g05', 'kia-ev9-mv'] },

    { model: 'Discovery Sport', gen: 'L550', years: [2015, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [32000, 50000], used: [12000, 40000], accel: 7.1, power: [150, 309], top: 124,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 40, ev: 38, seats: 7, doors: 5, boot: 897, len: 4597, kg: 1855,
      mpy: 10000, ncap: [5, 2014], onSale: true, halo: false,
      g: { build: 74, drive: 70, practicality: 88, value: 70, design: 72, running: 50 },
      verdict: 'The 5+2 family Landie: green-lane able, school-run polished. Early diesels rattled nerves; late cars much sorted.',
      issues: ['Ingenium diesel timing chains (early)', 'Infotainment lag pre-2020'],
      buy: 'P300e or D200 R-Dynamic SE, 2021-on, approved used.',
      tags: ['seven-seats', 'school-run', 'go-anywhere', 'dog-friendly', 'tow-car'],
      rivals: ['bmw-x3-g01', 'audi-q5-fy', 'volvo-xc60-p6'] },

    { model: 'Range Rover Evoque', gen: 'L551', years: [2019, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [33000, 55000], used: [18000, 45000], accel: 6.6, power: [150, 309], top: 130,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 42, ev: 39, seats: 5, doors: 5, boot: 472, len: 4371, kg: 1787,
      mpy: 9000, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 78, drive: 68, practicality: 70, value: 66, design: 86, running: 52 },
      verdict: 'The design-led Range Rover in miniature — kerb theatre per pound unmatched. Just budget like a Range Rover owner.',
      issues: ['Reliability surveys wince', 'Rear seat tight for the class'],
      buy: 'P300e R-Dynamic HSE — the tax-savvy poser, approved used.',
      tags: ['head-turner', 'city-darling', 'posh-interior', 'sleek', 'money-pit-risk'],
      rivals: ['volvo-xc40-p8', 'bmw-x1-u11', 'audi-q3-f3'] },

    { model: 'Range Rover Sport', gen: 'L494', years: [2013, 2022], bodies: ['suv'], segment: 'large-suv',
      priceNew: [60000, 100000], used: [22000, 65000], accel: 4.5, power: [258, 575], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 34, ev: 25, seats: 7, doors: 5, boot: 780, len: 4879, kg: 2115,
      mpy: 9500, ncap: [5, 2013], onSale: false, halo: false,
      g: { build: 76, drive: 78, practicality: 86, value: 68, design: 84, running: 34 },
      verdict: 'The footballer’s favourite for good reason — imperious everywhere. Buy the best history you can find, then a warranty.',
      issues: ['Air suspension, gearboxes, electrics: history or misery', 'Thirst across the range'],
      buy: 'SDV6 HSE Dynamic 2019-on, approved used, warranty stacked.',
      tags: ['head-turner', 'wafty', 'muscular', 'tow-car', 'posh-interior', 'money-pit-risk', 'go-anywhere'],
      rivals: ['bmw-x5-g05', 'porsche-cayenne-e3', 'audi-q7-4m'] },

    { model: 'Range Rover Sport', gen: 'L461', years: [2022, 0], bodies: ['suv'], segment: 'large-suv',
      priceNew: [80000, 140000], used: [60000, 120000], accel: 3.9, power: [249, 635], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 36, ev: 70, seats: 5, doors: 5, boot: 835, len: 4946, kg: 2310,
      mpy: 9000, ncap: [5, 2022], onSale: true, halo: true,
      g: { build: 84, drive: 82, practicality: 84, value: 62, design: 90, running: 34 },
      verdict: 'Minimalist muscle — the moment’s definitive status SUV. The P460e does 70 electric miles between poses.',
      issues: ['Theft target (get every tracker)', 'Waiting lists for the spec you want'],
      buy: 'P460e Dynamic SE — silent school runs, weekend thunder.',
      tags: ['head-turner', 'posh-interior', 'wafty', 'muscular', 'tow-car', 'sleek'],
      rivals: ['porsche-cayenne-e3', 'bmw-x5-g05', 'mercedes-benz-g-class-w463a'] },

    { model: 'Range Rover', gen: 'L405', years: [2012, 2021], bodies: ['suv'], segment: 'luxury',
      priceNew: [75000, 120000], used: [25000, 70000], accel: 5.1, power: [258, 565], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 33, ev: 25, seats: 5, doors: 5, boot: 909, len: 4999, kg: 2160,
      mpy: 8500, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 78, drive: 74, practicality: 86, value: 66, design: 90, running: 30 },
      verdict: 'The original luxury 4x4 at its imperial peak. £100k of presence for £30k — plus the running costs of £100k.',
      issues: ['Everything electronic can and will misbehave', 'Air suspension a service item'],
      buy: 'SDV8 Vogue SE, immaculate history, indie specialist on speed dial.',
      tags: ['wafty', 'head-turner', 'posh-interior', 'depreciation-king', 'money-pit-risk', 'go-anywhere', 'tow-car'],
      rivals: ['mercedes-benz-s-class-w222', 'bmw-x7-g07', 'bentley-bentayga-4v'] },

    { model: 'Range Rover', gen: 'L460', years: [2022, 0], bodies: ['suv'], segment: 'luxury',
      priceNew: [105000, 190000], used: [80000, 160000], accel: 4.6, power: [249, 615], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 35, ev: 70, seats: 7, doors: 5, boot: 818, len: 5052, kg: 2385,
      mpy: 8500, ncap: null, onSale: true, halo: true,
      g: { build: 86, drive: 80, practicality: 88, value: 58, design: 94, running: 28 },
      verdict: 'Still the king of arriving. Serene beyond measure, styled like carved soap — the one they all still chase.',
      issues: ['Insurance in London is its own mortgage', 'Early build gremlins'],
      buy: 'D350 Autobiography — the diesel remains the connoisseur pick.',
      tags: ['wafty', 'head-turner', 'posh-interior', 'go-anywhere', 'seven-seats', 'sleek'],
      rivals: ['mercedes-benz-g-class-w463a', 'bmw-x7-g07', 'bentley-bentayga-4v'] },

    { model: 'Velar', gen: 'L560', years: [2017, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [45000, 75000], used: [22000, 60000], accel: 5.2, power: [204, 550], top: 150,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 38, ev: 38, seats: 5, doors: 5, boot: 625, len: 4803, kg: 1841,
      mpy: 9000, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 78, drive: 72, practicality: 78, value: 64, design: 92, running: 44 },
      verdict: 'The beautiful one. Concept-car reduction outside, velvet calm inside — the aesthete’s Range Rover.',
      issues: ['Flush handles and screens age nervily', 'Options soar'],
      buy: 'D300 Dynamic HSE — six-cylinder polish, approved used.',
      tags: ['sleek', 'head-turner', 'posh-interior', 'discreet', 'money-pit-risk'],
      rivals: ['porsche-macan-95b', 'bmw-x4-g02', 'audi-q5-fy'] },

    { model: 'Freelander', gen: 'L359', years: [2006, 2014], bodies: ['suv'], segment: 'family-suv',
      priceNew: [21000, 33000], used: [3500, 10000], accel: 8.7, power: [150, 233], top: 118,
      fuels: ['petrol', 'diesel'], mpg: 40, ev: null, seats: 5, doors: 5, boot: 755, len: 4500, kg: 1770,
      mpy: 9000, ncap: [5, 2007], onSale: false, halo: false,
      g: { build: 72, drive: 62, practicality: 80, value: 76, design: 60, running: 54 },
      verdict: 'The honest Landie — school run in wellies. Tough Ford diesel, real off-road talent, none of the pretension.',
      issues: ['Rear diff and Haldex wear', 'Interior plastics age'],
      buy: 'Freelander 2 SD4 HSE 2012-on — the sorted years.',
      tags: ['go-anywhere', 'dog-friendly', 'bargain-hero', 'chunky-4x4', 'school-run'],
      rivals: ['toyota-rav4-xa30', 'honda-cr-v-re', 'volvo-xc60-p5'] }
  ]
};
