// Lexus — older and extra model-generations, UK market. Curated for Vroom.
export default {
  make: 'Lexus',
  cars: [
    { model: 'LS', gen: 'XF10', years: [1990, 1994], bodies: ['saloon'], segment: 'luxury', priceNew: [35000, 42000], used: [5000, 18000], accel: 8.5, power: [245, 250], top: 155, fuels: ['petrol'], mpg: 23, ev: null, seats: 5, doors: 4, boot: 430, len: 4995, kg: 1750, mpy: 4000, ncap: null, onSale: false, halo: false,
      g: { build: 98, drive: 70, practicality: 72, value: 82, design: 82, running: 42 }, verdict: 'The £1bn moonshot that humbled Mercedes: silent at 150mph, obsessively assembled and still astonishing three decades later.', issues: ['Air suspension and capacitors age', 'Trim parts require patience'], buy: 'Original LS 400 with specialist history, no rust and every electric toy working.', tags: ['boxy-icon', 'bulletproof', 'wafty', 'future-classic', 'posh-interior', 'v8-soundtrack'], rivals: ['mercedes-benz-s-class-w140', 'bmw-7-series-e32', 'jaguar-xj-x300'] },

    { model: 'LS', gen: 'XF20', years: [1995, 2000], bodies: ['saloon'], segment: 'luxury', priceNew: [43000, 50000], used: [3500, 12000], accel: 7.0, power: [260, 290], top: 155, fuels: ['petrol'], mpg: 24, ev: null, seats: 5, doors: 4, boot: 430, len: 4995, kg: 1760, mpy: 4500, ncap: null, onSale: false, halo: false,
      g: { build: 97, drive: 71, practicality: 72, value: 87, design: 74, running: 43 }, verdict: 'The LS 400 refined perfection into near invisibility. Silk V8, bank-vault body, old-luxury bills without old-luxury fragility.', issues: ['Suspension bushes and air struts age', 'Cambelt service is essential'], buy: 'Facelift car with cambelt invoice and immaculate electrical operation.', tags: ['bulletproof', 'wafty', 'bargain-hero', 'discreet', 'v8-soundtrack'], rivals: ['mercedes-benz-s-class-w140', 'bmw-7-series-e38', 'jaguar-xj-x308'] },

    { model: 'LS', gen: 'XF30', years: [2000, 2006], bodies: ['saloon'], segment: 'luxury', priceNew: [49000, 58000], used: [3500, 11000], accel: 6.3, power: [278, 282], top: 155, fuels: ['petrol'], mpg: 25, ev: null, seats: 5, doors: 4, boot: 573, len: 5005, kg: 1830, mpy: 5000, ncap: null, onSale: false, halo: false,
      g: { build: 97, drive: 72, practicality: 77, value: 90, design: 68, running: 46 }, verdict: 'Perhaps the finest shed money can buy: 290bhp V8 serenity, heroic equipment and a reputation for intergalactic mileage.', issues: ['Air suspension is costly when tired', 'Mark Levinson amplifiers can fail'], buy: 'LS 430 Premium with cambelt done and functioning air suspension.', tags: ['bulletproof', 'wafty', 'bargain-hero', 'posh-interior', 'v8-soundtrack'], rivals: ['mercedes-benz-s-class-w220', 'bmw-7-series-e65', 'jaguar-xj-x350'] },

    { model: 'LS', gen: 'XF40', years: [2007, 2017], bodies: ['saloon'], segment: 'luxury', priceNew: [61000, 100000], used: [7000, 26000], accel: 5.5, power: [382, 445], top: 155, fuels: ['petrol', 'hybrid'], mpg: 30, ev: null, seats: 5, doors: 4, boot: 560, len: 5060, kg: 1945, mpy: 6000, ncap: [5, 2007], onSale: false, halo: false,
      g: { build: 96, drive: 73, practicality: 75, value: 86, design: 72, running: 38 }, verdict: 'A technology-laden palace with reclining massage seats and optional hybrid V8. Depreciation did buyers a magnificent favour.', issues: ['Air suspension and brake actuators cost thousands', 'Hybrid boot is small'], buy: 'LS 460 with specialist inspection; avoid deferred-maintenance bargains.', tags: ['wafty', 'bulletproof', 'depreciation-king', 'posh-interior', 'tech-fest', 'money-pit-risk'], rivals: ['mercedes-benz-s-class-w221', 'bmw-7-series-f01', 'audi-a8-d4'] },

    { model: 'GS', gen: 'S160', years: [1998, 2005], bodies: ['saloon'], segment: 'exec', priceNew: [30000, 44000], used: [2500, 10000], accel: 5.9, power: [209, 280], top: 155, fuels: ['petrol'], mpg: 25, ev: null, seats: 5, doors: 4, boot: 515, len: 4805, kg: 1690, mpy: 5500, ncap: null, onSale: false, halo: false,
      g: { build: 92, drive: 72, practicality: 76, value: 90, design: 77, running: 46 }, verdict: 'A curvy, rear-drive executive with bombproof straight-six or V8 power. The discreet Japanese muscle bargain persists.', issues: ['Front ball joints need monitoring', 'Cambelts and cooling systems age'], buy: 'GS 430 if fuel is irrelevant; GS 300 for near-immortal daily use.', tags: ['bulletproof', 'bargain-hero', 'discreet', 'wafty', 'v8-soundtrack'], rivals: ['bmw-5-series-e39', 'mercedes-benz-e-class-w210', 'jaguar-s-type-x200'] },

    { model: 'GS', gen: 'S190', years: [2005, 2011], bodies: ['saloon'], segment: 'exec', priceNew: [33000, 52000], used: [3000, 11000], accel: 5.9, power: [245, 345], top: 155, fuels: ['petrol', 'hybrid'], mpg: 35, ev: null, seats: 5, doors: 4, boot: 430, len: 4830, kg: 1770, mpy: 6000, ncap: [5, 2005], onSale: false, halo: false,
      g: { build: 92, drive: 74, practicality: 71, value: 90, design: 75, running: 57 }, verdict: 'The GS added hybrid punch and sci-fi equipment without losing Lexus durability. A 450h remains absurd performance per pound.', issues: ['Hybrid battery and brake actuator age', 'Boot is compromised on 450h'], buy: 'GS 450h SE-L with battery report and functioning Mark Levinson audio.', tags: ['bulletproof', 'bargain-hero', 'tech-fest', 'discreet', 'depreciation-king'], rivals: ['bmw-5-series-e60', 'mercedes-benz-e-class-w211', 'audi-a6-c6'] },

    { model: 'GS', gen: 'L10', years: [2012, 2018], bodies: ['saloon'], segment: 'exec', priceNew: [35000, 70000], used: [9000, 26000], accel: 4.6, power: [223, 477], top: 168, fuels: ['petrol', 'hybrid'], mpg: 46, ev: null, seats: 5, doors: 4, boot: 482, len: 4880, kg: 1765, mpy: 7500, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 94, drive: 80, practicality: 75, value: 88, design: 81, running: 65 }, verdict: 'The forgotten 5 Series rival finally learned to corner. GS F adds a glorious V8; 300h adds minicab thrift.', issues: ['Infotainment mouse is maddening', 'GS F brakes and tyres are costly'], buy: 'GS 450h F Sport for pace and sanity; GS F for the soundtrack.', tags: ['bulletproof', 'left-field', 'bargain-hero', 'posh-interior', 'drivers-car'], rivals: ['bmw-5-series-f10', 'mercedes-benz-e-class-w212', 'jaguar-xf-x260'] },

    { model: 'RX', gen: 'XU10', years: [2000, 2003], bodies: ['suv'], segment: 'large-suv', priceNew: [32000, 38000], used: [1800, 7000], accel: 8.5, power: [217, 217], top: 124, fuels: ['petrol'], mpg: 23, ev: null, seats: 5, doors: 5, boot: 490, len: 4580, kg: 1805, mpy: 5500, ncap: null, onSale: false, halo: false,
      g: { build: 91, drive: 58, practicality: 80, value: 88, design: 68, running: 38 }, verdict: 'The original luxury crossover arrived before anyone used the phrase. Plush, simple, thirsty and almost unbreakable.', issues: ['Fuel economy is relentlessly poor', 'Ageing exhausts and suspension cost money'], buy: 'RX 300 SE-L with cambelt proof and corrosion-free rear subframe.', tags: ['bulletproof', 'wafty', 'bargain-hero', 'school-run', 'posh-interior'], rivals: ['mercedes-benz-m-class-w163', 'bmw-x5-e53', 'honda-cr-v-rd'] },

    { model: 'RX', gen: 'XU30', years: [2003, 2009], bodies: ['suv'], segment: 'large-suv', priceNew: [34000, 48000], used: [2500, 10000], accel: 7.6, power: [201, 272], top: 124, fuels: ['petrol', 'hybrid'], mpg: 34, ev: null, seats: 5, doors: 5, boot: 439, len: 4740, kg: 1975, mpy: 6000, ncap: [5, 2004], onSale: false, halo: false,
      g: { build: 92, drive: 57, practicality: 78, value: 90, design: 67, running: 59 }, verdict: 'The RX 400h made hybrid SUVs viable years before Europe noticed. Soft, silent and improbably cheap today.', issues: ['Hybrid batteries and inverters are ageing', 'Rear air suspension can sag'], buy: 'RX 400h SE-L with clean battery report and smooth brake actuator.', tags: ['bulletproof', 'wafty', 'bargain-hero', 'cheap-to-run', 'school-run'], rivals: ['volvo-xc90-p1', 'bmw-x5-e70', 'mercedes-benz-m-class-w164'] },

    { model: 'RX', gen: 'AL10', years: [2009, 2015], bodies: ['suv'], segment: 'large-suv', priceNew: [41000, 60000], used: [7000, 20000], accel: 7.8, power: [249, 295], top: 124, fuels: ['petrol', 'hybrid'], mpg: 44, ev: null, seats: 5, doors: 5, boot: 496, len: 4770, kg: 2110, mpy: 7500, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 93, drive: 59, practicality: 81, value: 87, design: 68, running: 72 }, verdict: 'A leather-lined hybrid cocoon with impeccable manners and almost no sporting intent. Used luxury without workshop dread.', issues: ['Brake actuators and dampers are expensive', 'CVT drone spoils hard acceleration'], buy: 'RX 450h SE-L with Lexus history and annual hybrid health checks.', tags: ['bulletproof', 'wafty', 'school-run', 'posh-interior', 'bargain-hero'], rivals: ['volvo-xc90-p1', 'bmw-x5-f15', 'mercedes-benz-m-class-w166'] },

    { model: 'NX', gen: 'AZ10', years: [2014, 2021], bodies: ['suv'], segment: 'family-suv', priceNew: [30000, 50000], used: [14000, 30000], accel: 7.1, power: [195, 235], top: 124, fuels: ['petrol', 'hybrid'], mpg: 54, ev: null, seats: 5, doors: 5, boot: 475, len: 4640, kg: 1785, mpy: 9000, ncap: [5, 2014], onSale: false, halo: false,
      g: { build: 90, drive: 64, practicality: 78, value: 83, design: 78, running: 86 }, verdict: 'Origami styling wrapped a Toyota-hybrid heart and magnificent dealer care. Not dynamic, but dependability is its luxury.', issues: ['Touchpad infotainment frustrates', 'F Sport ride can be brittle'], buy: 'NX 300h Luxury with full Lexus history and sensible wheel size.', tags: ['bulletproof', 'cheap-to-run', 'school-run', 'posh-interior', 'crowd-pleaser'], rivals: ['toyota-rav4-xa40', 'bmw-x3-f25', 'volvo-xc60-p3'] },

    { model: 'SC', gen: 'Z40', years: [2001, 2010], bodies: ['convertible'], segment: 'roadster-classic', priceNew: [53000, 62000], used: [7000, 18000], accel: 6.2, power: [282, 282], top: 155, fuels: ['petrol'], mpg: 23, ev: null, seats: 4, doors: 2, boot: 321, len: 4515, kg: 1740, mpy: 3500, ncap: null, onSale: false, halo: false,
      g: { build: 94, drive: 62, practicality: 42, value: 83, design: 70, running: 41 }, verdict: 'A folding-metal-roof V8 boulevardier built like expensive jewellery. Handling is sleepy; ownership can be wonderfully calm.', issues: ['Roof mechanisms require perfect alignment', 'Mark Levinson equipment and tyres cost'], buy: 'SC 430 with flawless roof operation, cambelt invoice and original wheels.', tags: ['wafty', 'bulletproof', 'grand-tourer', 'bargain-hero', 'v8-soundtrack'], rivals: ['mercedes-benz-sl-r230', 'jaguar-xk-x150', 'bmw-6-series-e64'] },

    { model: 'RC', gen: 'C10', years: [2015, 2020], bodies: ['coupe'], segment: 'super-coupe', priceNew: [35000, 76000], used: [17000, 50000], accel: 4.5, power: [223, 477], top: 168, fuels: ['petrol', 'hybrid'], mpg: 44, ev: null, seats: 4, doors: 2, boot: 374, len: 4705, kg: 1775, mpy: 5500, ncap: null, onSale: false, halo: false,
      g: { build: 93, drive: 81, practicality: 52, value: 84, design: 88, running: 54 }, verdict: 'A heavyweight coupe with concept-car angles. The hybrid cruises; RC F erupts with one of the last great V8s.', issues: ['Touchpad infotainment is dated', 'RC F consumes brakes, tyres and fuel'], buy: 'RC F Carbon with complete Lexus history, or 300h F Sport for calm.', tags: ['head-turner', 'v8-soundtrack', 'grand-tourer', 'bulletproof', 'future-classic'], rivals: ['bmw-m4-f82', 'mercedes-amg-c63-c205', 'audi-rs5-b9'] },

    { model: 'LFA', gen: 'LFA10', years: [2010, 2012], bodies: ['coupe'], segment: 'super-coupe', priceNew: [340000, 350000], used: [700000, 1000000], accel: 3.7, power: [560, 560], top: 202, fuels: ['petrol'], mpg: 16, ev: null, seats: 2, doors: 2, boot: 110, len: 4505, kg: 1480, mpy: 1000, ncap: null, onSale: false, halo: true,
      g: { build: 99, drive: 99, practicality: 25, value: 35, design: 99, running: 20 }, verdict: 'A carbon-fibre moonshot with a 9,000rpm V10 that needed a digital tachometer. Japan’s supercar masterpiece, now priceless.', issues: ['Tyres and bespoke servicing are collector-grade expensive', 'Availability is essentially theoretical'], buy: 'Buy the provenance and specialist relationship; colour is a distant concern.', tags: ['future-classic', 'head-turner', 'rev-happy', 'drivers-car', 'track-day', 'money-pit-risk'], rivals: ['porsche-carrera-gt-980', 'ferrari-599-gto-f141', 'mercedes-benz-sls-amg-c197'] },

    { model: 'LBX', gen: 'AY10', years: [2024, 0], bodies: ['suv'], segment: 'small-suv', priceNew: [30000, 41000], used: [24000, 36000], accel: 9.2, power: [136, 136], top: 106, fuels: ['hybrid'], mpg: 61, ev: null, seats: 5, doors: 5, boot: 402, len: 4190, kg: 1280, mpy: 7500, ncap: [4, 2024], onSale: true, halo: false,
      g: { build: 89, drive: 70, practicality: 68, value: 70, design: 82, running: 91 }, verdict: 'A Yaris Cross transformed by insulation, upholstery and obsessive assembly. Expensive for its size, convincingly premium within.', issues: ['Rear space is supermini-tight', 'Four-star safety result disappoints'], buy: 'Premium Plus Design front-driver; all-wheel drive adds little in Britain.', tags: ['posh-interior', 'city-darling', 'cheap-to-run', 'bulletproof', 'sleek'], rivals: ['toyota-yaris-cross-xp210', 'audi-q2-ga', 'mini-countryman-u25'] }
  ]
};
