// Mazda — older and extra model-generations, UK market. Curated for Vroom.
export default {
  make: 'Mazda',
  cars: [
    { model: 'MX-5', gen: 'NA', years: [1990, 1998], bodies: ['convertible'], segment: 'roadster-classic', priceNew: [14000, 17000], used: [5000, 20000], accel: 8.2, power: [114, 131], top: 123, fuels: ['petrol'], mpg: 32, ev: null, seats: 2, doors: 2, boot: 135, len: 3975, kg: 955, mpy: 3500, ncap: null, onSale: false, halo: false,
      g: { build: 77, drive: 97, practicality: 30, value: 83, design: 96, running: 75 }, verdict: 'Pop-up lamps, one tonne, perfect controls: the roadster reset button. Rust is the enemy; joy is guaranteed.', issues: ['Sills and rear arches hide serious rust', 'Original panels and trim are ageing'], buy: 'UK 1.8 with specialist rust inspection; originality beats cosmetic shine.', tags: ['boxy-icon', 'analogue-joy', 'drivers-car', 'lightweight', 'modern-classic', 'b-road-hero'], rivals: ['toyota-mr2-w30', 'lotus-elise-s1', 'bmw-z3-e36-7'] },

    { model: 'MX-5', gen: 'NB', years: [1998, 2005], bodies: ['convertible'], segment: 'roadster-classic', priceNew: [15000, 19000], used: [2500, 9000], accel: 7.8, power: [110, 146], top: 130, fuels: ['petrol'], mpg: 34, ev: null, seats: 2, doors: 2, boot: 144, len: 3975, kg: 1065, mpy: 4000, ncap: [4, 2002], onSale: false, halo: false,
      g: { build: 75, drive: 94, practicality: 31, value: 91, design: 82, running: 77 }, verdict: 'The sweet spot between classic delicacy and daily usability. Cheap to fix, sublime to steer, alarmingly skilled at rusting.', issues: ['Front chassis rails corrode invisibly', 'Sills and arches rot from within'], buy: '1.8 Sport with full structural inspection and no cheap modifications.', tags: ['analogue-joy', 'drivers-car', 'lightweight', 'bargain-hero', 'b-road-hero', 'modern-classic'], rivals: ['toyota-mr2-w30', 'mg-tf-mk2', 'honda-s2000-ap1'] },

    { model: 'Mazda2', gen: 'DY', years: [2003, 2007], bodies: ['hatch'], segment: 'supermini', priceNew: [9000, 13000], used: [900, 3500], accel: 10.1, power: [74, 100], top: 112, fuels: ['petrol', 'diesel'], mpg: 45, ev: null, seats: 5, doors: 5, boot: 268, len: 3925, kg: 1080, mpy: 5500, ncap: [4, 2004], onSale: false, halo: false,
      g: { build: 70, drive: 63, practicality: 76, value: 90, design: 45, running: 86 }, verdict: 'A tall, boxy supermini with Ford bones and Mazda cheer. Almost forgotten, meaning useful cars cost pocket money.', issues: ['Sills and rear arches rust', 'Wheel bearings wear'], buy: '1.4 petrol manual with clean metal; avoid rusty bargain blindness.', tags: ['tardis', 'bargain-hero', 'first-car-friendly', 'cheap-to-run'], rivals: ['honda-jazz-gd', 'toyota-yaris-xp90', 'ford-fusion-mk1'] },

    { model: 'Mazda2', gen: 'DE', years: [2007, 2015], bodies: ['hatch'], segment: 'supermini', priceNew: [9000, 15000], used: [1800, 6500], accel: 8.7, power: [75, 102], top: 117, fuels: ['petrol', 'diesel'], mpg: 54, ev: null, seats: 5, doors: 5, boot: 250, len: 3900, kg: 1030, mpy: 6000, ncap: [5, 2007], onSale: false, halo: false,
      g: { build: 72, drive: 77, practicality: 64, value: 89, design: 68, running: 89 }, verdict: 'Light, eager and refreshingly simple, this is the supermini for people who notice steering. Cheap fun without hot-hatch bills.', issues: ['Rear arches can bubble', 'Cabins wear if neglected'], buy: '1.5 Sport manual, ideally facelift, with rust-free arches.', tags: ['lightweight', 'drivers-car', 'bargain-hero', 'first-car-friendly', 'cheap-to-run'], rivals: ['ford-fiesta-mk7', 'suzuki-swift-zc72', 'toyota-yaris-xp130'] },

    { model: 'Mazda3', gen: 'BK', years: [2004, 2009], bodies: ['hatch', 'saloon'], segment: 'family-hatch', priceNew: [13000, 21000], used: [1000, 6000], accel: 6.1, power: [84, 260], top: 155, fuels: ['petrol', 'diesel'], mpg: 42, ev: null, seats: 5, doors: 5, boot: 346, len: 4420, kg: 1280, mpy: 6500, ncap: [4, 2006], onSale: false, halo: false,
      g: { build: 68, drive: 75, practicality: 73, value: 88, design: 62, running: 70 }, verdict: 'Focus underpinnings with Japanese engines made a sharp family hatch. MPS added 260bhp and heroic torque steer.', issues: ['Structural rust is the defining risk', 'Diesel turbos and DPFs can fail'], buy: '2.0 Sport petrol with rigorous underside inspection; MPS only standard.', tags: ['drivers-car', 'bargain-hero', 'left-field', 'pocket-rocket'], rivals: ['ford-focus-mk2', 'honda-civic-fn2', 'toyota-auris-e150'] },

    { model: 'Mazda3', gen: 'BL', years: [2009, 2013], bodies: ['hatch', 'saloon'], segment: 'family-hatch', priceNew: [15000, 24000], used: [2500, 8000], accel: 6.1, power: [105, 260], top: 155, fuels: ['petrol', 'diesel'], mpg: 47, ev: null, seats: 5, doors: 5, boot: 340, len: 4460, kg: 1315, mpy: 7000, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 72, drive: 76, practicality: 72, value: 86, design: 65, running: 72 }, verdict: 'The smiling Mazda3 kept keen steering and added polish. MPS remained a discreet missile with a voracious front axle.', issues: ['Diesel oil dilution can destroy engines', 'Rust protection remains average'], buy: '2.0 petrol Sport manual; avoid diesel unless history is exceptional.', tags: ['drivers-car', 'bargain-hero', 'left-field', 'discreet'], rivals: ['ford-focus-mk3', 'honda-civic-fn2', 'volkswagen-golf-mk6'] },

    { model: 'Mazda3', gen: 'BM', years: [2014, 2019], bodies: ['hatch', 'saloon'], segment: 'family-hatch', priceNew: [17000, 26000], used: [6500, 15000], accel: 8.2, power: [100, 165], top: 130, fuels: ['petrol', 'diesel'], mpg: 55, ev: null, seats: 5, doors: 5, boot: 364, len: 4465, kg: 1280, mpy: 8000, ncap: [5, 2013], onSale: false, halo: false,
      g: { build: 82, drive: 80, practicality: 71, value: 85, design: 84, running: 80 }, verdict: 'The Mazda3 grew elegant without going numb. Naturally aspirated petrols feel honest; the cabin punches above used prices.', issues: ['Diesels suffer DPF and carbon issues', 'Infotainment screens can delaminate'], buy: '2.0 Skyactiv-G 120 Sport Nav manual, petrol without hesitation.', tags: ['sleek', 'drivers-car', 'posh-interior', 'bargain-hero', 'left-field'], rivals: ['honda-civic-fk2', 'ford-focus-mk3', 'toyota-auris-e180'] },

    { model: 'Mazda6', gen: 'GG', years: [2002, 2008], bodies: ['saloon', 'hatch', 'estate'], segment: 'exec', priceNew: [15000, 25000], used: [800, 5000], accel: 8.4, power: [120, 256], top: 149, fuels: ['petrol', 'diesel'], mpg: 43, ev: null, seats: 5, doors: 5, boot: 492, len: 4670, kg: 1395, mpy: 7000, ncap: [4, 2003], onSale: false, halo: false,
      g: { build: 66, drive: 78, practicality: 80, value: 88, design: 66, running: 66 }, verdict: 'The first Mazda6 made repmobiles fun and estates handsome. Rust consumed too many; solid petrols are terrific sheds.', issues: ['Severe sill and arch corrosion', 'Diesel failures are rarely economical'], buy: '2.0 petrol estate after an uncompromising structural inspection.', tags: ['drivers-car', 'dog-friendly', 'bargain-hero', 'motorway-muncher'], rivals: ['honda-accord-cl', 'toyota-avensis-t250', 'ford-mondeo-mk3'] },

    { model: 'Mazda6', gen: 'GH', years: [2008, 2013], bodies: ['saloon', 'hatch', 'estate'], segment: 'exec', priceNew: [17000, 27000], used: [1800, 7000], accel: 8.0, power: [120, 180], top: 135, fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 510, len: 4755, kg: 1455, mpy: 8000, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 72, drive: 77, practicality: 82, value: 88, design: 72, running: 70 }, verdict: 'A lighter, sharper Mondeo alternative with a huge hatch or estate. Petrol power keeps the bargain simple.', issues: ['Diesel DPF and oil-dilution problems', 'Subframes can corrode'], buy: '2.0 petrol Sport hatch with clean underside and full history.', tags: ['drivers-car', 'bargain-hero', 'dog-friendly', 'motorway-muncher'], rivals: ['honda-accord-cu', 'toyota-avensis-t270', 'ford-mondeo-mk4'] },

    { model: 'CX-5', gen: 'KE', years: [2012, 2017], bodies: ['suv'], segment: 'family-suv', priceNew: [21000, 33000], used: [7000, 16000], accel: 8.8, power: [150, 175], top: 129, fuels: ['petrol', 'diesel'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 503, len: 4555, kg: 1515, mpy: 9000, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 78, drive: 79, practicality: 81, value: 82, design: 76, running: 70 }, verdict: 'The crossover that proved family SUVs need not steer like trolleys. Petrol is lovely; diesel can become a cautionary tale.', issues: ['2.2 diesel oil dilution and DPF failures', 'Early infotainment is basic'], buy: '2.0 petrol Sport Nav, accepting modest pace for peace of mind.', tags: ['drivers-car', 'school-run', 'dog-friendly', 'bargain-hero'], rivals: ['toyota-rav4-xa40', 'honda-cr-v-rm', 'nissan-x-trail-t32'] },

    { model: 'CX-3', gen: 'DK', years: [2015, 2021], bodies: ['suv'], segment: 'small-suv', priceNew: [18000, 25000], used: [8000, 17000], accel: 8.8, power: [105, 150], top: 124, fuels: ['petrol', 'diesel'], mpg: 49, ev: null, seats: 5, doors: 5, boot: 350, len: 4275, kg: 1230, mpy: 7500, ncap: [4, 2015], onSale: false, halo: false,
      g: { build: 81, drive: 77, practicality: 63, value: 79, design: 84, running: 81 }, verdict: 'A Mazda2 in a beautifully tailored crossover suit. Rear space disappoints; steering and cabin make amends.', issues: ['Rear seat and boot are tight', 'Diesel is unsuitable for short trips'], buy: '2.0 petrol Sport Nav manual, front-wheel drive.', tags: ['sleek', 'drivers-car', 'city-darling', 'left-field'], rivals: ['honda-hr-v-ru', 'nissan-juke-f16', 'toyota-c-hr-ax10'] },

    { model: 'CX-7', gen: 'ER', years: [2007, 2012], bodies: ['suv'], segment: 'family-suv', priceNew: [24000, 29000], used: [2500, 7500], accel: 8.0, power: [173, 256], top: 130, fuels: ['petrol', 'diesel'], mpg: 33, ev: null, seats: 5, doors: 5, boot: 455, len: 4680, kg: 1770, mpy: 6500, ncap: [4, 2010], onSale: false, halo: false,
      g: { build: 65, drive: 70, practicality: 73, value: 75, design: 72, running: 25 }, verdict: 'A handsome turbo crossover whose appetite and mechanical risks explain the astonishing price. Fast can become financially frightening.', issues: ['Diesel engines suffer severe oil and timing problems', 'Turbo petrol drinks heavily'], buy: 'Only a specialist-inspected petrol with impeccable cooling and oil history.', tags: ['depreciation-king', 'left-field', 'money-pit-risk', 'sleek'], rivals: ['nissan-murano-z51', 'ford-kuga-mk1', 'subaru-forester-sh'] },

    { model: 'RX-7', gen: 'FD', years: [1992, 2002], bodies: ['coupe'], segment: 'super-coupe', priceNew: [32000, 35000], used: [25000, 70000], accel: 5.1, power: [237, 276], top: 156, fuels: ['petrol'], mpg: 20, ev: null, seats: 4, doors: 2, boot: 160, len: 4295, kg: 1280, mpy: 2500, ncap: null, onSale: false, halo: false,
      g: { build: 69, drive: 97, practicality: 35, value: 55, design: 98, running: 20 }, verdict: 'One of the most beautiful cars Japan ever made, powered by sequential-turbo rotary witchcraft. Sublime and needy in equal measure.', issues: ['Rotary rebuilds and overheating are endemic', 'Modified imports demand forensic checks'], buy: 'Compression-tested specialist car with cooling upgrades and documented rebuild.', tags: ['head-turner', 'future-classic', 'drivers-car', 'sleek', 'money-pit-risk', 'lightweight'], rivals: ['toyota-supra-a80', 'nissan-200sx-s14', 'porsche-968-club-sport'] },

    { model: '323F', gen: 'BA', years: [1994, 1998], bodies: ['hatch'], segment: 'family-hatch', priceNew: [13000, 18000], used: [1000, 5000], accel: 9.4, power: [88, 143], top: 126, fuels: ['petrol'], mpg: 36, ev: null, seats: 5, doors: 5, boot: 345, len: 4240, kg: 1160, mpy: 4000, ncap: null, onSale: false, halo: false,
      g: { build: 72, drive: 71, practicality: 68, value: 84, design: 86, running: 73 }, verdict: 'A frameless-window family coupe with a tiny V6 option. Nineties design flair now outweighs its ordinary-car roots.', issues: ['Rust attacks arches and sills', 'V6 cooling systems need care'], buy: '1.8 manual with solid shell; V6 only with enthusiast history.', tags: ['retro-charm', 'left-field', 'future-classic', 'sleek'], rivals: ['honda-civic-mb', 'toyota-corolla-e110', 'alfa-romeo-145-930'] },

    { model: 'Tribute', gen: 'EP', years: [2001, 2008], bodies: ['suv'], segment: 'family-suv', priceNew: [17000, 24000], used: [1200, 4500], accel: 8.8, power: [123, 197], top: 121, fuels: ['petrol'], mpg: 25, ev: null, seats: 5, doors: 5, boot: 405, len: 4395, kg: 1590, mpy: 5500, ncap: [3, 2002], onSale: false, halo: false,
      g: { build: 63, drive: 55, practicality: 75, value: 81, design: 47, running: 32 }, verdict: 'A Ford Escape in Mazda clothes: roomy, robust-ish and almost entirely erased from memory. V6 fuel bills explain some.', issues: ['Rear arches and subframes rust', 'V6 economy struggles past the twenties'], buy: '2.0 manual with solid underside; the V6 is hard to justify.', tags: ['bargain-hero', 'left-field', 'dog-friendly', 'money-pit-risk'], rivals: ['honda-cr-v-rd', 'toyota-rav4-xa20', 'ford-maverick-u204'] },

    { model: 'Mazda5', gen: 'CR', years: [2005, 2010], bodies: ['mpv'], segment: 'seven-seater', priceNew: [15000, 21000], used: [1200, 5000], accel: 10.8, power: [110, 146], top: 121, fuels: ['petrol', 'diesel'], mpg: 44, ev: null, seats: 7, doors: 5, boot: 112, len: 4505, kg: 1485, mpy: 6500, ncap: [5, 2005], onSale: false, halo: false,
      g: { build: 65, drive: 68, practicality: 89, value: 88, design: 56, running: 68 }, verdict: 'Sliding doors, seven seats and unusually tidy handling made this the driver’s compact MPV. Rust is the grim footnote.', issues: ['Sills and rear arches corrode badly', 'Diesel DPF and turbo issues'], buy: '2.0 petrol Sport with a lift inspection and smooth sliding doors.', tags: ['seven-seats', 'family-bus', 'van-with-windows', 'bargain-hero', 'drivers-car'], rivals: ['toyota-verso-ar20', 'ford-grand-c-max-mk2', 'vauxhall-zafira-b'] }
  ]
};
