// Mazda — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Mazda',
  cars: [
    { model: 'MX-5', gen: 'NC', years: [2005, 2015], bodies: ['convertible'], segment: 'roadster-classic',
      priceNew: [16000, 24000], used: [4000, 11000], accel: 7.6, power: [126, 160], top: 132,
      fuels: ['petrol'], mpg: 38, ev: null, seats: 2, doors: 2, boot: 150, len: 4020, kg: 1155,
      mpy: 5000, ncap: null, onSale: false, halo: false,
      g: { build: 76, drive: 88, practicality: 34, value: 86, design: 70, running: 78 },
      verdict: 'The affordable sports car answer, generation three: folding hardtop option, bulletproof drivetrain, endless smiles.',
      issues: ['Rust in rear arches/sills — inspect hard', 'Soft-top drains'],
      buy: '2.0 Sport Tech PRHT, rust-checked, budget for springs.',
      tags: ['drivers-car', 'analogue-joy', 'bargain-hero', 'b-road-hero', 'lightweight', 'first-car-friendly'],
      rivals: ['mazda-mx-5-nd', 'toyota-gt86-zn6', 'bmw-z4-e89'] },

    { model: 'MX-5', gen: 'ND', years: [2015, 0], bodies: ['convertible'], segment: 'sports',
      priceNew: [19000, 32000], used: [11000, 28000], accel: 6.5, power: [131, 184], top: 136,
      fuels: ['petrol'], mpg: 44, ev: null, seats: 2, doors: 2, boot: 130, len: 3915, kg: 1030,
      mpy: 5000, ncap: [4, 2015], onSale: true, halo: false,
      g: { build: 82, drive: 93, practicality: 32, value: 88, design: 82, running: 80 },
      verdict: 'A tonne of car, a hundred percent of the joy. The 184 revs to 7,500 and costs buttons — the purest fun per pound on sale.',
      issues: ['Cabin snug for the tall', 'Boot takes soft bags only'],
      buy: '2.0 184 Sport Tech manual, soft-top. The answer is always Miata.',
      tags: ['drivers-car', 'analogue-joy', 'lightweight', 'b-road-hero', 'rev-happy', 'bargain-hero', 'future-classic'],
      rivals: ['toyota-gr86-zn8', 'bmw-z4-g29', 'porsche-718-boxster-982'] },

    { model: 'Mazda2', gen: 'DJ', years: [2015, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [14000, 20000], used: [7000, 16000], accel: 8.7, power: [75, 115], top: 124,
      fuels: ['petrol', 'hybrid'], mpg: 56, ev: null, seats: 5, doors: 5, boot: 280, len: 4060, kg: 1045,
      mpy: 7500, ncap: [4, 2015], onSale: true, halo: false,
      g: { build: 78, drive: 74, practicality: 62, value: 78, design: 66, running: 88 },
      verdict: 'The supermini that treats you like an adult: real dials, keen steering, no turbo lag because no turbo.',
      issues: ['Road noise at pace', 'Rear seat tight'],
      buy: '1.5 Skyactiv-G 90 GT Sport — simple pleasures.',
      tags: ['first-car-friendly', 'drivers-car', 'cheap-to-run', 'analogue-joy'],
      rivals: ['ford-fiesta-mk8', 'toyota-yaris-xp210', 'suzuki-swift-a2l'] },

    { model: 'Mazda3', gen: 'BP', years: [2019, 0], bodies: ['hatch', 'saloon'], segment: 'family-hatch',
      priceNew: [24000, 34000], used: [13000, 27000], accel: 8.1, power: [116, 186], top: 127,
      fuels: ['petrol', 'hybrid'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 351, len: 4460, kg: 1395,
      mpy: 9000, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 86, drive: 78, practicality: 68, value: 78, design: 86, running: 82 },
      verdict: 'Concept-car looks straight to showroom, cabin from a class above. The premium hatch that skips the premium badge tax.',
      issues: ['Rear visibility pays for the C-pillar art', 'Skyactiv-X complexity underdelivers'],
      buy: 'e-Skyactiv G 2.0 GT Sport hatch — elegance on a budget.',
      tags: ['sleek', 'posh-interior', 'drivers-car', 'left-field', 'head-turner'],
      rivals: ['volkswagen-golf-mk8', 'honda-civic-fl1', 'toyota-corolla-e210'] },

    { model: 'Mazda6', gen: 'GJ', years: [2013, 2023], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [21000, 34000], used: [8000, 22000], accel: 7.8, power: [145, 194], top: 138,
      fuels: ['petrol', 'diesel'], mpg: 52, ev: null, seats: 5, doors: 4, boot: 480, len: 4870, kg: 1440,
      mpy: 10500, ncap: [5, 2013], onSale: false, halo: false,
      g: { build: 82, drive: 78, practicality: 80, value: 84, design: 80, running: 78 },
      verdict: 'The handsome underdog exec — steers sweetly, wears beautifully, costs Mondeo money. The estate is a quiet stunner.',
      issues: ['Diesel DPF wants motorway life', 'Infotainment dated by the end'],
      buy: '2.5 GT Sport Nav+ Tourer petrol — the connoisseur commuter.',
      tags: ['sleek', 'drivers-car', 'bargain-hero', 'motorway-muncher', 'left-field', 'dog-friendly'],
      rivals: ['ford-mondeo-mk5', 'volkswagen-passat-b8', 'bmw-3-series-f30'] },

    { model: 'CX-30', gen: 'DM', years: [2019, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [24000, 34000], used: [14000, 28000], accel: 8.3, power: [122, 186], top: 127,
      fuels: ['petrol', 'hybrid'], mpg: 48, ev: null, seats: 5, doors: 5, boot: 430, len: 4395, kg: 1395,
      mpy: 9000, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 86, drive: 76, practicality: 72, value: 76, design: 84, running: 80 },
      verdict: 'The Mazda3 in walking boots — same gorgeous cabin, sensible ride height. The premium-feel crossover bargain.',
      issues: ['Engines like revs, not lugging', 'Rear seat mid-pack'],
      buy: 'e-Skyactiv G GT Sport — feels £10k dearer than it is.',
      tags: ['posh-interior', 'sleek', 'school-run', 'left-field', 'crowd-pleaser'],
      rivals: ['volkswagen-t-roc-a11', 'toyota-c-hr-ax10', 'honda-hr-v-rv'] },

    { model: 'CX-5', gen: 'KF', years: [2017, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [26000, 40000], used: [14000, 32000], accel: 7.9, power: [150, 194], top: 129,
      fuels: ['petrol', 'diesel'], mpg: 45, ev: null, seats: 5, doors: 5, boot: 522, len: 4550, kg: 1565,
      mpy: 10000, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 86, drive: 78, practicality: 80, value: 80, design: 78, running: 74 },
      verdict: 'The family SUV for people who still like driving. No hybrid tricks, just balance, quality and honest money.',
      issues: ['No electrified option ages the fleet appeal', 'Infotainment behind the pack'],
      buy: '2.2d 184 GT Sport AWD — or petrol for town lives.',
      tags: ['drivers-car', 'school-run', 'dog-friendly', 'crowd-pleaser', 'bargain-hero'],
      rivals: ['toyota-rav4-xa50', 'honda-cr-v-rw', 'kia-sportage-nq5'] },

    { model: 'CX-60', gen: 'KH', years: [2022, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [45000, 58000], used: [28000, 45000], accel: 5.8, power: [200, 327], top: 124,
      fuels: ['diesel', 'phev'], mpg: 53, ev: 39, seats: 5, doors: 5, boot: 570, len: 4745, kg: 1980,
      mpy: 10000, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 82, drive: 70, practicality: 82, value: 74, design: 74, running: 72 },
      verdict: 'Mazda goes premium-RWD: a new straight-six diesel in 2023 was gloriously contrarian. Ride polish arrived with updates.',
      issues: ['Early cars rode harshly (updated)', 'PHEV refinement middling'],
      buy: 'e-Skyactiv D 254 Homura — the six-cylinder heretic’s choice.',
      tags: ['left-field', 'posh-interior', 'tow-car', 'motorway-muncher'],
      rivals: ['bmw-x3-g01', 'audi-q5-fy', 'lexus-nx-az20'] },

    { model: 'RX-8', gen: 'SE3P', years: [2003, 2010], bodies: ['coupe'], segment: 'sports',
      priceNew: [20000, 25000], used: [3000, 9000], accel: 6.4, power: [189, 231], top: 146,
      fuels: ['petrol'], mpg: 25, ev: null, seats: 4, doors: 4, boot: 290, len: 4425, kg: 1310,
      mpy: 4000, ncap: [4, 2004], onSale: false, halo: false,
      g: { build: 68, drive: 86, practicality: 56, value: 70, design: 78, running: 34 },
      verdict: 'A 9,000rpm rotary with suicide doors for used-Fiesta money. Running one is a hobby; driving one is a privilege.',
      issues: ['Rotary compression — test before buying, always', 'Oil consumption is a feature, not a bug'],
      buy: 'R3 with compression figures in writing, or a rebuilt engine.',
      tags: ['left-field', 'analogue-joy', 'rev-happy', 'modern-classic', 'money-pit-risk', 'drivers-car'],
      rivals: ['nissan-350z-z33', 'audi-tt-8j', 'toyota-gt86-zn6'] },

    { model: 'MX-30', gen: 'DR', years: [2020, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [28000, 35000], used: [11000, 20000], accel: 9.7, power: [145, 170], top: 87,
      fuels: ['ev'], mpg: null, ev: 124, seats: 5, doors: 4, boot: 366, len: 4395, kg: 1720,
      mpy: 6000, ncap: [5, 2020], onSale: true, halo: false,
      g: { build: 82, drive: 70, practicality: 56, value: 64, design: 80, running: 82 },
      verdict: 'Cork trim, RX-8 doors, 124-mile range — Mazda’s lovely wrong answer. As a used second car, oddly compelling.',
      issues: ['Range rules out road trips', 'Rear doors need the fronts open'],
      buy: 'Makoto used at half price — style-first city electric.',
      tags: ['left-field', 'city-darling', 'minimalist', 'retro-charm', 'depreciation-king'],
      rivals: ['honda-e-ze1', 'mini-electric-f56', 'fiat-500e-332'] }
  ]
};
