// MG — model-generations, UK market. Curated for Vroom.
export default {
  make: 'MG',
  cars: [
    { model: 'MG4', gen: 'Mk1', years: [2022, 0], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [27000, 37000], used: [14000, 28000], accel: 3.8, power: [170, 435], top: 121,
      fuels: ['ev'], mpg: null, ev: 323, seats: 5, doors: 5, boot: 363, len: 4287, kg: 1655,
      mpy: 9000, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 74, drive: 80, practicality: 74, value: 92, design: 74, running: 88 },
      verdict: 'The value bombshell: rear-drive balance, real range, £27k new. The XPower does 0-62 in 3.8 for hot-hatch money.',
      issues: ['Infotainment laggy', 'Interior plastics honest'],
      buy: 'Trophy Long Range — the people’s EV, sorted spec.',
      tags: ['bargain-hero', 'cheap-to-run', 'drivers-car', 'silent-cruiser', 'crowd-pleaser'],
      rivals: ['volkswagen-id-3-e11', 'cupra-born-k11', 'renault-megane-e-tech-bcb'] },

    { model: 'ZS EV', gen: 'ZS11', years: [2019, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [25000, 33000], used: [10000, 22000], accel: 8.4, power: [143, 156], top: 108,
      fuels: ['ev'], mpg: null, ev: 273, seats: 5, doors: 5, boot: 448, len: 4323, kg: 1610,
      mpy: 8500, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 72, drive: 60, practicality: 80, value: 88, design: 60, running: 88 },
      verdict: 'The fleet-and-family EV that undercut everyone — roomy, honest, warrantied seven years. Function over flourish.',
      issues: ['Unexciting everywhere', 'Early cars slower charging'],
      buy: 'Long Range Trophy used — space and volts for £14k.',
      tags: ['bargain-hero', 'cheap-to-run', 'school-run', 'crowd-pleaser'],
      rivals: ['kia-niro-sg2', 'hyundai-kona-sx2', 'byd-atto-3-ba3'] },

    { model: 'HS', gen: 'AS23', years: [2023, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [25000, 35000], used: [17000, 30000], accel: 8.4, power: [170, 272], top: 118,
      fuels: ['petrol', 'phev'], mpg: 40, ev: 75, seats: 5, doors: 5, boot: 507, len: 4655, kg: 1580,
      mpy: 10000, ncap: [5, 2024], onSale: true, halo: false,
      g: { build: 74, drive: 62, practicality: 84, value: 90, design: 68, running: 80 },
      verdict: 'A Qashqai-sized SUV at supermini money; the PHEV does 75 electric miles. The value case is simply unanswerable.',
      issues: ['Dynamics merely fine', 'Brand image still budget'],
      buy: 'PHEV Trophy — the 75-mile plug-in for £31k.',
      tags: ['bargain-hero', 'school-run', 'tardis', 'cheap-to-run', 'crowd-pleaser'],
      rivals: ['nissan-qashqai-j12', 'kia-sportage-nq5', 'hyundai-tucson-nx4'] },

    { model: 'MG5', gen: 'Mk1', years: [2020, 2025], bodies: ['estate'], segment: 'ev-native',
      priceNew: [25000, 32000], used: [10000, 20000], accel: 7.7, power: [156, 156], top: 115,
      fuels: ['ev'], mpg: null, ev: 250, seats: 5, doors: 5, boot: 479, len: 4600, kg: 1562,
      mpy: 10000, ncap: [3, 2022], onSale: false, halo: false,
      g: { build: 70, drive: 62, practicality: 84, value: 88, design: 54, running: 88 },
      verdict: 'For years the only affordable electric estate on Earth. Minicab fleets bought them all — that is the review.',
      issues: ['Three-star NCAP', 'Anonymous looks'],
      buy: 'Long Range Trophy used — the practical EV bargain.',
      tags: ['bargain-hero', 'tardis', 'cheap-to-run', 'dog-friendly', 'left-field'],
      rivals: ['mg-mg4-mk1', 'vauxhall-astra-l', 'peugeot-e-308-p52'] },

    { model: 'Cyberster', gen: 'CY01', years: [2024, 0], bodies: ['convertible'], segment: 'sports',
      priceNew: [55000, 60000], used: [42000, 55000], accel: 3.2, power: [340, 503], top: 125,
      fuels: ['ev'], mpg: null, ev: 316, seats: 2, doors: 2, boot: 249, len: 4535, kg: 1985,
      mpy: 5000, ncap: null, onSale: true, halo: false,
      g: { build: 78, drive: 74, practicality: 34, value: 72, design: 88, running: 78 },
      verdict: 'Scissor doors, MGB nostalgia, EV silence — the first electric roadster anyone actually built. Flawed and fabulous.',
      issues: ['Two tonnes of roadster', 'Screen ergonomics odd'],
      buy: 'Trophy RWD — lighter, purer, £7k cheaper than the GT.',
      tags: ['head-turner', 'left-field', 'retro-charm', 'future-classic', 'silent-cruiser'],
      rivals: ['bmw-z4-g29', 'mazda-mx-5-nd', 'porsche-718-boxster-982'] },

    { model: 'MGF / TF', gen: 'Classic', years: [1995, 2011], bodies: ['convertible'], segment: 'roadster-classic',
      priceNew: [16000, 20000], used: [1500, 6000], accel: 7.6, power: [118, 160], top: 131,
      fuels: ['petrol'], mpg: 38, ev: null, seats: 2, doors: 2, boot: 210, len: 3913, kg: 1075,
      mpy: 3000, ncap: null, onSale: false, halo: false,
      g: { build: 56, drive: 76, practicality: 30, value: 78, design: 66, running: 70 },
      verdict: 'Mid-engined British sunshine for the price of a holiday. Head gasket done? Then it’s the cheapest fun on four wheels.',
      issues: ['K-Series head gasket — the entire conversation', 'Hood and sill rust'],
      buy: 'TF 135 with the uprated gasket and a thick file.',
      tags: ['bargain-hero', 'analogue-joy', 'modern-classic', 'lightweight', 'first-car-friendly', 'left-field'],
      rivals: ['mazda-mx-5-nb', 'toyota-mr2-w30', 'fiat-barchetta-183'] }
  ]
};
