// MINI — model-generations, UK market. Curated for Vroom.
export default {
  make: 'MINI',
  cars: [
    { model: 'Hatch', gen: 'R56', years: [2006, 2013], bodies: ['hatch', 'convertible'], segment: 'supermini',
      priceNew: [12000, 22000], used: [2500, 9000], accel: 6.5, power: [75, 211], top: 148,
      fuels: ['petrol', 'diesel'], mpg: 48, ev: null, seats: 4, doors: 3, boot: 160, len: 3699, kg: 1090,
      mpy: 7500, ncap: [5, 2007], onSale: false, halo: false,
      g: { build: 72, drive: 84, practicality: 44, value: 78, design: 80, running: 64 },
      verdict: 'Go-kart steering and boutique charm for hot-hatch pennies. The N14 engine bites — buy on history, not on stripes.',
      issues: ['Timing-chain death rattle (N14)', 'Thermostat housings, oil leaks'],
      buy: 'Cooper S with chain done, or a late John Cooper Works.',
      tags: ['pocket-rocket', 'drivers-car', 'city-darling', 'head-turner', 'first-car-friendly', 'modern-classic'],
      rivals: ['ford-fiesta-mk7', 'audi-a1-8x', 'citroen-ds3-a55'] },

    { model: 'Hatch', gen: 'F56', years: [2014, 2024], bodies: ['hatch', 'convertible'], segment: 'supermini',
      priceNew: [16000, 32000], used: [7000, 24000], accel: 6.1, power: [75, 231], top: 153,
      fuels: ['petrol', 'diesel', 'ev'], mpg: 50, ev: 145, seats: 4, doors: 3, boot: 211, len: 3821, kg: 1160,
      mpy: 8000, ncap: [4, 2014], onSale: false, halo: false,
      g: { build: 82, drive: 84, practicality: 50, value: 76, design: 80, running: 74 },
      verdict: 'Grown-up build with the giggle intact. Cooper S is the sweet spot; the Electric is the best-value used city EV grin.',
      issues: ['Rear seats decorative', 'Runflat thump'],
      buy: 'Cooper S manual 5dr, or the Electric Level 2 at £11k used.',
      tags: ['pocket-rocket', 'drivers-car', 'city-darling', 'head-turner', 'crowd-pleaser', 'retro-charm'],
      rivals: ['audi-a1-gb', 'fiat-500-312', 'volkswagen-polo-mk6'] },

    { model: 'Cooper', gen: 'F66', years: [2024, 0], bodies: ['hatch', 'convertible'], segment: 'supermini',
      priceNew: [23000, 35000], used: [18000, 30000], accel: 6.3, power: [156, 231], top: 155,
      fuels: ['petrol', 'ev'], mpg: 47, ev: 250, seats: 4, doors: 3, boot: 210, len: 3858, kg: 1290,
      mpy: 8000, ncap: [5, 2025], onSale: true, halo: false,
      g: { build: 84, drive: 82, practicality: 52, value: 72, design: 84, running: 78 },
      verdict: 'The circular-OLED reinvention — minimalist cabin, maximalist charm. Electric versions finally have real range.',
      issues: ['Screen-first controls take a week', 'Petrol/EV split confusingly badged'],
      buy: 'Cooper E Classic — 250 miles of urban theatre.',
      tags: ['city-darling', 'retro-charm', 'head-turner', 'tech-fest', 'drivers-car'],
      rivals: ['fiat-500e-332', 'volvo-ex30-y1', 'renault-5-e-tech-bfb'] },

    { model: 'Clubman', gen: 'F54', years: [2015, 2024], bodies: ['estate'], segment: 'family-hatch',
      priceNew: [20000, 38000], used: [9000, 26000], accel: 4.9, power: [102, 306], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 47, ev: null, seats: 5, doors: 5, boot: 360, len: 4253, kg: 1375,
      mpy: 8500, ncap: [4, 2015], onSale: false, halo: false,
      g: { build: 82, drive: 78, practicality: 68, value: 74, design: 78, running: 70 },
      verdict: 'Barn doors and boutique tailoring — the MINI for grown-ups. JCW All4 is a 306bhp sleeper nobody expects.',
      issues: ['Boot access quirky in car parks', 'Options-dependent value'],
      buy: 'Cooper S Exclusive, or JCW for the stealth missile.',
      tags: ['left-field', 'head-turner', 'drivers-car', 'city-darling', 'discreet'],
      rivals: ['audi-a3-8v', 'bmw-1-series-f40', 'volkswagen-golf-mk7'] },

    { model: 'Countryman', gen: 'F60', years: [2017, 2023], bodies: ['suv'], segment: 'small-suv',
      priceNew: [24000, 40000], used: [12000, 30000], accel: 5.1, power: [102, 306], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 45, ev: 26, seats: 5, doors: 5, boot: 450, len: 4299, kg: 1440,
      mpy: 9500, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 82, drive: 76, practicality: 78, value: 72, design: 74, running: 68 },
      verdict: 'The MINI that fits a family — proper boot, PHEV option, kart DNA diluted but detectable. Style tax applies.',
      issues: ['Firm ride on big wheels', 'PHEV electric range modest'],
      buy: 'Cooper S E All4 PHEV Exclusive — town volts, weekend fizz.',
      tags: ['school-run', 'city-darling', 'head-turner', 'crowd-pleaser'],
      rivals: ['bmw-x1-f48', 'audi-q2-ga', 'volvo-xc40-p8'] },

    { model: 'Countryman', gen: 'U25', years: [2024, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [30000, 48000], used: [24000, 40000], accel: 5.6, power: [170, 313], top: 155,
      fuels: ['petrol', 'ev'], mpg: 47, ev: 287, seats: 5, doors: 5, boot: 505, len: 4444, kg: 1560,
      mpy: 9500, ncap: [5, 2024], onSale: true, halo: false,
      g: { build: 84, drive: 76, practicality: 82, value: 72, design: 80, running: 78 },
      verdict: 'Now X1-sized and knitted-dashboard cosy. The Electric SE ALL4 is the family MINI that finally makes total sense.',
      issues: ['It is not mini anymore', 'Price walks into premium territory'],
      buy: 'Countryman E Classic — 287 miles, maximum charm per watt.',
      tags: ['school-run', 'retro-charm', 'head-turner', 'tech-fest', 'crowd-pleaser'],
      rivals: ['bmw-x1-u11', 'volvo-ex40-p8', 'kia-niro-sg2'] },

    { model: 'GP', gen: 'F56 GP3', years: [2020, 2021], bodies: ['hatch'], segment: 'hot-hatch',
      priceNew: [34000, 35000], used: [26000, 33000], accel: 5.2, power: [306, 306], top: 164,
      fuels: ['petrol'], mpg: 38, ev: null, seats: 2, doors: 3, boot: 211, len: 3849, kg: 1255,
      mpy: 4000, ncap: [4, 2014], onSale: false, halo: false,
      g: { build: 82, drive: 86, practicality: 36, value: 70, design: 78, running: 62 },
      verdict: 'Two seats, carbon arches, 3,000 built. The maddest MINI — torque-steery, riotous, already a collector’s item.',
      issues: ['No back seats at all', 'Firm enough to rearrange vertebrae'],
      buy: 'Low-mileage numbered car, standard, stored well.',
      tags: ['track-day', 'future-classic', 'pocket-rocket', 'head-turner', 'left-field'],
      rivals: ['honda-civic-type-r-fk8', 'hyundai-i30-n-pd', 'toyota-gr-yaris-xp210'] }
  ]
};
