// Mitsubishi — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Mitsubishi',
  cars: [
    { model: 'Lancer Evolution X', gen: 'CZ4A', years: [2008, 2016], bodies: ['saloon'], segment: 'super-coupe',
      priceNew: [28000, 38000], used: [18000, 35000], accel: 4.4, power: [295, 440], top: 155,
      fuels: ['petrol'], mpg: 24, ev: null, seats: 5, doors: 4, boot: 252, len: 4495, kg: 1560,
      mpy: 5000, ncap: null, onSale: false, halo: false,
      g: { build: 70, drive: 88, practicality: 62, value: 72, design: 70, running: 36 },
      verdict: 'The last Evo — S-AWC witchcraft that shames supercars point-to-point. Clean FQ-360s are blue-chip modern classics.',
      issues: ['SST gearbox service critical', 'Mods and abuse rampant'],
      buy: 'FQ-300 manual, standard, service file like a phone book.',
      tags: ['go-anywhere', 'future-classic', 'modern-classic', 'track-day', 'b-road-hero', 'muscular'],
      rivals: ['subaru-impreza-wrx-sti-gr-gv', 'audi-rs3-8v', 'bmw-m2-f87'] },

    { model: 'Outlander PHEV', gen: 'GG', years: [2014, 2021], bodies: ['suv'], segment: 'family-suv',
      priceNew: [32000, 42000], used: [9000, 20000], accel: 10.5, power: [200, 224], top: 106,
      fuels: ['phev'], mpg: 45, ev: 28, seats: 5, doors: 5, boot: 463, len: 4695, kg: 1880,
      mpy: 9500, ncap: [5, 2014], onSale: false, halo: false,
      g: { build: 76, drive: 56, practicality: 82, value: 80, design: 54, running: 78 },
      verdict: 'Britain’s first mass plug-in SUV — company-car catnip of the 2010s. Dull as dishwater, useful as a Swiss knife.',
      issues: ['Battery health varies — test', 'Uninspiring everywhere'],
      buy: '2019-on 2.4 with the bigger battery, health report in hand.',
      tags: ['school-run', 'cheap-to-run', 'bargain-hero', 'tow-car', 'discreet'],
      rivals: ['toyota-rav4-xa50', 'kia-niro-de', 'ford-kuga-mk3'] },

    { model: 'Shogun', gen: 'V80', years: [2007, 2019], bodies: ['suv'], segment: 'off-roader',
      priceNew: [32000, 42000], used: [10000, 25000], accel: 11.1, power: [190, 200], top: 112,
      fuels: ['diesel'], mpg: 30, ev: null, seats: 7, doors: 5, boot: 663, len: 4900, kg: 2255,
      mpy: 9000, ncap: null, onSale: false, halo: false,
      g: { build: 84, drive: 48, practicality: 84, value: 76, design: 58, running: 50 },
      verdict: 'The farm-and-horsebox stalwart. Crude, unkillable, tows a house — the Land Cruiser’s blunt-instrument cousin.',
      issues: ['Agricultural manners', 'Check chassis for farm-life rust'],
      buy: 'LWB SG3 3.2 DI-DC — the workhorse spec.',
      tags: ['go-anywhere', 'bulletproof', 'tow-car', 'chunky-4x4', 'off-grid', 'seven-seats'],
      rivals: ['toyota-land-cruiser-j150', 'land-rover-discovery-l319', 'ssangyong-rexton-y400'] },

    { model: 'L200', gen: 'Mk5', years: [2015, 2021], bodies: ['pickup'], segment: 'pickup',
      priceNew: [22000, 33000], used: [12000, 24000], accel: 10.4, power: [150, 181], top: 111,
      fuels: ['diesel'], mpg: 37, ev: null, seats: 5, doors: 4, boot: 1000, len: 5305, kg: 1995,
      mpy: 12000, ncap: [4, 2015], onSale: false, halo: false,
      g: { build: 76, drive: 56, practicality: 82, value: 80, design: 58, running: 62 },
      verdict: 'The value pickup of its era — lighter and nimbler than rivals, happy on farm or drive. Honest tool, honest money.',
      issues: ['DPF on short runs', 'Interior plastics workmanlike'],
      buy: 'Series 6 Barbarian double cab — kit and capability.',
      tags: ['chunky-4x4', 'tow-car', 'go-anywhere', 'bargain-hero', 'adventure-ready'],
      rivals: ['nissan-navara-d23', 'toyota-hilux-an120', 'isuzu-d-max-rg'] },

    { model: 'i-MiEV', gen: 'HA', years: [2011, 2015], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [24000, 29000], used: [3000, 6000], accel: 15.9, power: [67, 67], top: 81,
      fuels: ['ev'], mpg: null, ev: 80, seats: 4, doors: 5, boot: 227, len: 3475, kg: 1080,
      mpy: 4000, ncap: [4, 2011], onSale: false, halo: false,
      g: { build: 66, drive: 50, practicality: 52, value: 66, design: 60, running: 92 },
      verdict: 'The pioneer nobody remembers — a jellybean EV before EVs were cool. £4k buys a piece of history and 60 real miles.',
      issues: ['Range tiny, battery old — test health', 'Parts patience'],
      buy: 'The tidiest one left, as a second car and conversation piece.',
      tags: ['left-field', 'city-darling', 'cheap-to-run', 'modern-classic', 'bargain-hero'],
      rivals: ['nissan-leaf-ze0', 'renault-zoe-ph1', 'smart-fortwo-ed-w451'] }
  ]
};
