// Nissan — older and extra model-generations, UK market. Curated for Vroom.
export default {
  make: 'Nissan',
  cars: [
    { model: 'Micra', gen: 'K11', years: [1993, 2003], bodies: ['hatch'], segment: 'supermini', priceNew: [7000, 11000], used: [800, 5000], accel: 11.9, power: [54, 81], top: 106, fuels: ['petrol', 'diesel'], mpg: 46, ev: null, seats: 5, doors: 5, boot: 206, len: 3745, kg: 835, mpy: 4500, ncap: [2, 1997], onSale: false, halo: false,
      g: { build: 77, drive: 63, practicality: 61, value: 92, design: 72, running: 95 }, verdict: 'Britain built millions of these friendly bubbles, and half appear to be running still. Featherweight, honest, lovable.', issues: ['Sills and crossmembers rust', 'Two-star safety is period-correct'], buy: 'Facelift 1.0 Celebration with a genuinely solid underside.', tags: ['retro-charm', 'first-car-friendly', 'cheap-to-run', 'bargain-hero', 'lightweight'], rivals: ['toyota-starlet-p90', 'ford-fiesta-mk4', 'volkswagen-polo-mk3'] },

    { model: 'Micra', gen: 'K12', years: [2003, 2010], bodies: ['hatch', 'convertible'], segment: 'supermini', priceNew: [8000, 15000], used: [1000, 4500], accel: 9.8, power: [65, 110], top: 114, fuels: ['petrol', 'diesel'], mpg: 49, ev: null, seats: 5, doors: 5, boot: 251, len: 3715, kg: 1040, mpy: 5500, ncap: [4, 2003], onSale: false, halo: false,
      g: { build: 69, drive: 60, practicality: 69, value: 89, design: 75, running: 88 }, verdict: 'The googly-eyed Micra remains charming and absurdly cheap. Sliding rear bench helps; French electronics occasionally do not.', issues: ['Timing chains stretch on neglected petrols', 'Keyless-entry faults are common'], buy: '1.4 manual with quiet cold start and two working keys.', tags: ['retro-charm', 'city-darling', 'first-car-friendly', 'bargain-hero', 'cheap-to-run'], rivals: ['toyota-yaris-xp90', 'honda-jazz-gd', 'ford-fiesta-mk6'] },

    { model: 'Micra', gen: 'K13', years: [2010, 2017], bodies: ['hatch'], segment: 'supermini', priceNew: [9000, 15000], used: [2500, 7000], accel: 11.3, power: [79, 97], top: 112, fuels: ['petrol'], mpg: 56, ev: null, seats: 5, doors: 5, boot: 265, len: 3825, kg: 980, mpy: 6000, ncap: [4, 2010], onSale: false, halo: false,
      g: { build: 65, drive: 50, practicality: 65, value: 84, design: 45, running: 90 }, verdict: 'Built to a price and visibly so. It is easy to park, cheap to fuel and almost aggressively forgettable.', issues: ['Thin paint and cabin materials', 'CVT can whine or fail expensively'], buy: '1.2 Acenta manual; low owners and service history matter more than trim.', tags: ['cheap-to-run', 'first-car-friendly', 'city-darling', 'bargain-hero'], rivals: ['toyota-yaris-xp130', 'honda-jazz-gk', 'suzuki-swift-zc72'] },

    { model: 'Juke', gen: 'F15', years: [2010, 2019], bodies: ['suv'], segment: 'small-suv', priceNew: [13000, 24000], used: [3500, 13000], accel: 7.8, power: [94, 218], top: 134, fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 354, len: 4135, kg: 1295, mpy: 7500, ncap: [5, 2011], onSale: false, halo: false,
      g: { build: 68, drive: 63, practicality: 59, value: 81, design: 73, running: 75 }, verdict: 'The frog-eyed crossover that launched a thousand imitators. Cramped, divisive and more fun than its reputation suggests.', issues: ['1.2 DIG-T timing-chain and oil issues', 'CVT failures can write cars off'], buy: '1.6 petrol manual N-Connecta; avoid questionable 1.2s and CVTs.', tags: ['head-turner', 'city-darling', 'crowd-pleaser', 'bargain-hero'], rivals: ['toyota-urban-cruiser-xp110', 'renault-captur-i', 'peugeot-2008-a94'] },

    { model: 'Qashqai', gen: 'J10', years: [2007, 2013], bodies: ['suv'], segment: 'family-suv', priceNew: [15000, 27000], used: [2500, 9000], accel: 9.9, power: [105, 150], top: 119, fuels: ['petrol', 'diesel'], mpg: 48, ev: null, seats: 7, doors: 5, boot: 410, len: 4330, kg: 1510, mpy: 8500, ncap: [5, 2007], onSale: false, halo: false,
      g: { build: 70, drive: 58, practicality: 80, value: 87, design: 59, running: 77 }, verdict: 'The Sunderland-built crossover that changed family-car history. Not great at anything, brilliantly acceptable at everything.', issues: ['Rear suspension bushes wear', 'DPFs and CVTs need careful history'], buy: 'Facelift 1.6 petrol manual; +2 only if occasional rear seats matter.', tags: ['school-run', 'crowd-pleaser', 'bargain-hero', 'family-bus'], rivals: ['toyota-rav4-xa30', 'honda-cr-v-re', 'ford-kuga-mk1'] },

    { model: 'X-Trail', gen: 'T30', years: [2001, 2007], bodies: ['suv'], segment: 'family-suv', priceNew: [16000, 24000], used: [1200, 6000], accel: 9.2, power: [114, 165], top: 119, fuels: ['petrol', 'diesel'], mpg: 37, ev: null, seats: 5, doors: 5, boot: 410, len: 4510, kg: 1490, mpy: 7000, ncap: [4, 2002], onSale: false, halo: false,
      g: { build: 75, drive: 58, practicality: 82, value: 88, design: 69, running: 68 }, verdict: 'A square, washable, genuinely useful SUV with dashboard instruments in the middle for reasons nobody remembers.', issues: ['Sills and rear arches corrode', '2.2 diesels suffer turbo and timing problems'], buy: '2.0 petrol Sport with solid shell and working four-wheel drive.', tags: ['boxy-icon', 'adventure-ready', 'dog-friendly', 'bargain-hero', 'go-anywhere'], rivals: ['honda-cr-v-rd', 'toyota-rav4-xa20', 'subaru-forester-sg'] },

    { model: 'X-Trail', gen: 'T31', years: [2007, 2014], bodies: ['suv'], segment: 'family-suv', priceNew: [19000, 30000], used: [3000, 10000], accel: 10.0, power: [150, 173], top: 124, fuels: ['petrol', 'diesel'], mpg: 42, ev: null, seats: 5, doors: 5, boot: 603, len: 4630, kg: 1660, mpy: 8500, ncap: [4, 2007], onSale: false, halo: false,
      g: { build: 76, drive: 57, practicality: 88, value: 86, design: 63, running: 68 }, verdict: 'The last boxy X-Trail: enormous boot, hose-clean practicality and real mud ability. Diesel complications temper the bargain.', issues: ['DPF and turbo failures on short-run diesels', 'Rear subframes can corrode'], buy: 'Late manual Tekna with DPF evidence, or rare 2.0 petrol.', tags: ['boxy-icon', 'dog-friendly', 'adventure-ready', 'tow-car', 'bargain-hero'], rivals: ['toyota-rav4-xa30', 'honda-cr-v-re', 'land-rover-freelander-l359'] },

    { model: 'X-Trail', gen: 'T32', years: [2014, 2022], bodies: ['suv'], segment: 'seven-seater', priceNew: [23000, 36000], used: [7000, 21000], accel: 9.4, power: [130, 177], top: 126, fuels: ['petrol', 'diesel'], mpg: 49, ev: null, seats: 7, doors: 5, boot: 550, len: 4640, kg: 1580, mpy: 9500, ncap: [5, 2014], onSale: false, halo: false,
      g: { build: 72, drive: 58, practicality: 87, value: 81, design: 58, running: 73 }, verdict: 'The X-Trail became a Qashqai XL and sold by the suburb-load. Seven seats help; personality left quietly.', issues: ['1.6 diesel DPF and turbo issues', 'CVT needs impeccable fluid history'], buy: '2019-on 1.7 dCi manual N-Connecta, used for regular long runs.', tags: ['seven-seats', 'family-bus', 'school-run', 'dog-friendly'], rivals: ['toyota-rav4-xa40', 'honda-cr-v-rm', 'skoda-kodiaq-ns7'] },

    { model: 'Leaf', gen: 'ZE0', years: [2011, 2017], bodies: ['hatch'], segment: 'ev-native', priceNew: [26000, 32000], used: [2500, 9000], accel: 11.5, power: [109, 109], top: 90, fuels: ['ev'], mpg: null, ev: 155, seats: 5, doors: 5, boot: 370, len: 4445, kg: 1525, mpy: 6000, ncap: [5, 2011], onSale: false, halo: false,
      g: { build: 72, drive: 57, practicality: 70, value: 82, design: 48, running: 94 }, verdict: 'The mass-market EV pioneer is now a cheap local runabout. Range aged badly; silent simplicity aged beautifully.', issues: ['Battery degradation varies sharply', 'CHAdeMO charging is fading away'], buy: '2016-on 30kWh Acenta with at least ten battery-health bars.', tags: ['bargain-hero', 'cheap-to-run', 'city-darling', 'silent-cruiser', 'future-classic'], rivals: ['renault-zoe-ph1', 'bmw-i3-i01', 'volkswagen-e-golf-mk7'] },

    { model: 'Note', gen: 'E11', years: [2006, 2013], bodies: ['mpv'], segment: 'supermini', priceNew: [11000, 17000], used: [1200, 5000], accel: 10.7, power: [86, 110], top: 114, fuels: ['petrol', 'diesel'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 437, len: 4083, kg: 1092, mpy: 6500, ncap: [4, 2006], onSale: false, halo: false,
      g: { build: 71, drive: 55, practicality: 86, value: 90, design: 49, running: 88 }, verdict: 'A tall supermini with a sliding bench and the spatial efficiency of a garden shed. Cheap, cheerful, magnificently uncool.', issues: ['Front subframes can corrode', 'Timing chains rattle when neglected'], buy: '1.6 petrol manual with a clean subframe and quiet cold start.', tags: ['tardis', 'bargain-hero', 'cheap-to-run', 'first-car-friendly'], rivals: ['honda-jazz-gd', 'toyota-yaris-xp90', 'ford-fusion-mk1'] },

    { model: 'Almera', gen: 'N16', years: [2000, 2006], bodies: ['hatch', 'saloon'], segment: 'family-hatch', priceNew: [11000, 17000], used: [700, 3000], accel: 10.4, power: [89, 134], top: 125, fuels: ['petrol', 'diesel'], mpg: 43, ev: null, seats: 5, doors: 5, boot: 355, len: 4185, kg: 1190, mpy: 6000, ncap: [4, 2001], onSale: false, halo: false,
      g: { build: 65, drive: 49, practicality: 70, value: 90, design: 35, running: 82 }, verdict: 'Transport stripped of aspiration: dowdy, spacious and now almost free. Its greatest feature is persistent forward motion.', issues: ['Timing chains stretch', 'Front crossmembers rust badly'], buy: '1.5 petrol manual with a replaced crossmember and quiet chain.', tags: ['bargain-hero', 'discreet', 'cheap-to-run', 'first-car-friendly'], rivals: ['toyota-corolla-e120', 'honda-civic-ep', 'ford-focus-mk1'] },

    { model: 'Primera', gen: 'P12', years: [2002, 2008], bodies: ['saloon', 'hatch', 'estate'], segment: 'exec', priceNew: [15000, 24000], used: [700, 3500], accel: 9.6, power: [115, 204], top: 146, fuels: ['petrol', 'diesel'], mpg: 43, ev: null, seats: 5, doors: 5, boot: 460, len: 4567, kg: 1390, mpy: 6500, ncap: [4, 2002], onSale: false, halo: false,
      g: { build: 61, drive: 55, practicality: 77, value: 86, design: 58, running: 68 }, verdict: 'Avant-garde cabin meets fleet-car hardware. Vast and cheap, but electrical gremlins explain why survivors feel archaeological.', issues: ['Dashboard and camera electronics fail', 'Diesel reliability is poor'], buy: '1.8 petrol manual estate with every screen and switch working.', tags: ['left-field', 'bargain-hero', 'dog-friendly', 'money-pit-risk'], rivals: ['toyota-avensis-t250', 'honda-accord-cl', 'mazda-mazda6-gg'] },

    { model: 'Pulsar', gen: 'C13', years: [2014, 2018], bodies: ['hatch'], segment: 'family-hatch', priceNew: [16000, 23000], used: [4500, 9500], accel: 7.7, power: [110, 190], top: 135, fuels: ['petrol', 'diesel'], mpg: 56, ev: null, seats: 5, doors: 5, boot: 385, len: 4387, kg: 1270, mpy: 7500, ncap: [5, 2014], onSale: false, halo: false,
      g: { build: 68, drive: 54, practicality: 82, value: 87, design: 45, running: 81 }, verdict: 'Nissan briefly remembered hatchbacks, created enormous rear legroom, then forgot again. Blandness makes used prices excellent.', issues: ['1.2 DIG-T can consume oil', 'Interior feels budget-built'], buy: '1.5 dCi Tekna for motorway use, or carefully checked 1.2 manual.', tags: ['bargain-hero', 'tardis', 'discreet', 'motorway-muncher'], rivals: ['toyota-auris-e180', 'honda-civic-fk2', 'skoda-rapid-spaceback-nh'] },

    { model: '350Z', gen: 'Z33', years: [2003, 2009], bodies: ['coupe', 'convertible'], segment: 'sports', priceNew: [24000, 32000], used: [5000, 16000], accel: 5.7, power: [276, 313], top: 155, fuels: ['petrol'], mpg: 24, ev: null, seats: 2, doors: 2, boot: 235, len: 4310, kg: 1545, mpy: 4500, ncap: null, onSale: false, halo: false,
      g: { build: 73, drive: 84, practicality: 37, value: 90, design: 81, running: 39 }, verdict: 'A big-hearted V6 coupe with rear drive, a manual and no interest in delicacy. Proper sports-car theatre for hatchback money.', issues: ['Oil consumption on some engines', 'Rear arches and W-brace corrode'], buy: '2007-on HR manual coupe with healthy oil pressure and solid underside.', tags: ['muscular', 'analogue-joy', 'bargain-hero', 'modern-classic', 'drivers-car'], rivals: ['mazda-rx-8-se3p', 'toyota-gt86-zn6', 'bmw-z4-e85'] },

    { model: '200SX', gen: 'S14', years: [1994, 1999], bodies: ['coupe'], segment: 'sports', priceNew: [20000, 24000], used: [12000, 35000], accel: 6.9, power: [197, 197], top: 146, fuels: ['petrol'], mpg: 27, ev: null, seats: 4, doors: 2, boot: 307, len: 4520, kg: 1265, mpy: 3000, ncap: null, onSale: false, halo: false,
      g: { build: 70, drive: 90, practicality: 49, value: 60, design: 84, running: 44 }, verdict: 'Turbo, rear drive and endlessly tuneable: the drift-tax poster child. Standard UK cars are now rarer than supercars.', issues: ['Rust attacks sills and chassis rails', 'Most cars are heavily modified'], buy: 'Original Touring with solid shell; pay for history, not shiny paint.', tags: ['future-classic', 'analogue-joy', 'drivers-car', 'money-pit-risk', 'sleek'], rivals: ['toyota-supra-a80', 'mazda-rx-7-fd', 'bmw-3-series-e36'] },

    { model: '300ZX', gen: 'Z32', years: [1989, 2000], bodies: ['coupe', 'convertible'], segment: 'super-coupe', priceNew: [33000, 40000], used: [9000, 30000], accel: 5.6, power: [222, 300], top: 155, fuels: ['petrol'], mpg: 21, ev: null, seats: 4, doors: 2, boot: 326, len: 4520, kg: 1580, mpy: 2500, ncap: null, onSale: false, halo: false,
      g: { build: 76, drive: 82, practicality: 43, value: 69, design: 90, running: 28 }, verdict: 'A low, wide techno-GT from Japan’s bubble era. Twin turbos thrill; the packed engine bay terrifies ordinary mechanics.', issues: ['Cooling and turbo work is labour-intensive', 'Rust hides beneath trim'], buy: 'Specialist-inspected UK twin-turbo with cooling overhaul receipts.', tags: ['grand-tourer', 'future-classic', 'sleek', 'money-pit-risk', 'head-turner'], rivals: ['toyota-supra-a80', 'mitsubishi-3000gt-z16a', 'porsche-928-gts'] },

    { model: 'Skyline GT-R', gen: 'R32', years: [1989, 1994], bodies: ['coupe'], segment: 'super-coupe', priceNew: [33000, 38000], used: [35000, 100000], accel: 4.7, power: [276, 276], top: 155, fuels: ['petrol'], mpg: 20, ev: null, seats: 4, doors: 2, boot: 240, len: 4545, kg: 1430, mpy: 2500, ncap: null, onSale: false, halo: false,
      g: { build: 86, drive: 96, practicality: 48, value: 48, design: 93, running: 30 }, verdict: 'Godzilla earned its name by destroying touring-car grids. Compact, mechanical and far more special than the numbers admit.', issues: ['Rust and accident repairs are endemic', 'Attesa system needs specialist care'], buy: 'Documented, standard-bodied car with compression test and rust inspection.', tags: ['boxy-icon', 'future-classic', 'track-day', 'drivers-car', 'tech-fest', 'money-pit-risk'], rivals: ['porsche-911-964', 'bmw-m3-e30', 'toyota-supra-a80'] },

    { model: 'Skyline GT-R', gen: 'R34', years: [1999, 2002], bodies: ['coupe'], segment: 'super-coupe', priceNew: [50000, 55000], used: [100000, 300000], accel: 4.9, power: [276, 276], top: 155, fuels: ['petrol'], mpg: 20, ev: null, seats: 4, doors: 2, boot: 180, len: 4600, kg: 1560, mpy: 2000, ncap: null, onSale: false, halo: true,
      g: { build: 88, drive: 94, practicality: 42, value: 28, design: 99, running: 22 }, verdict: 'The video-game Skyline became a blue-chip asset. Monumental presence and clever chassis remain; market prices escaped reality.', issues: ['Counterfeit or rebodied cars exist', 'Parts and insurance costs are extreme'], buy: 'Only with marque-specialist authentication, original identity and exhaustive records.', tags: ['boxy-icon', 'future-classic', 'head-turner', 'tech-fest', 'money-pit-risk', 'track-day'], rivals: ['toyota-supra-a80', 'porsche-911-996-turbo', 'mitsubishi-lancer-evo-vi'] },

    { model: 'Navara', gen: 'D40', years: [2005, 2015], bodies: ['pickup'], segment: 'pickup', priceNew: [19000, 32000], used: [3500, 14000], accel: 11.1, power: [144, 231], top: 121, fuels: ['diesel'], mpg: 34, ev: null, seats: 5, doors: 4, boot: 1100, len: 5300, kg: 2085, mpy: 10000, ncap: [3, 2008], onSale: false, halo: false,
      g: { build: 51, drive: 56, practicality: 84, value: 67, design: 62, running: 39 }, verdict: 'Strong, handsome and useful, but the chassis-corrosion scandal is impossible to ignore. Buy with eyes underneath, not on paint.', issues: ['Chassis can corrode and snap', 'Timing chains and clutches wear'], buy: 'Only a post-inspection truck with documented chassis campaign or replacement.', tags: ['tow-car', 'chunky-4x4', 'money-pit-risk', 'adventure-ready'], rivals: ['toyota-hilux-an10', 'mitsubishi-l200-mk4', 'ford-ranger-t6'] },

    { model: 'Pathfinder', gen: 'R51', years: [2005, 2014], bodies: ['suv'], segment: 'off-roader', priceNew: [27000, 42000], used: [3500, 14000], accel: 11.0, power: [171, 231], top: 124, fuels: ['diesel'], mpg: 33, ev: null, seats: 7, doors: 5, boot: 515, len: 4740, kg: 2210, mpy: 8500, ncap: [4, 2006], onSale: false, halo: false,
      g: { build: 61, drive: 50, practicality: 88, value: 72, design: 65, running: 39 }, verdict: 'A seven-seat Navara wagon with low range and genuine towing muscle. Capability is real; corrosion anxiety is equally real.', issues: ['Chassis corrosion can be structural', 'Timing-chain replacement is costly'], buy: '2010-on with independent chassis inspection and chain evidence.', tags: ['seven-seats', 'tow-car', 'go-anywhere', 'money-pit-risk', 'chunky-4x4'], rivals: ['toyota-land-cruiser-j120', 'mitsubishi-shogun-v80', 'land-rover-discovery-l319'] },

    { model: 'Murano', gen: 'Z51', years: [2008, 2014], bodies: ['suv'], segment: 'large-suv', priceNew: [33000, 40000], used: [3500, 10000], accel: 8.0, power: [187, 252], top: 130, fuels: ['petrol', 'diesel'], mpg: 28, ev: null, seats: 5, doors: 5, boot: 402, len: 4835, kg: 1870, mpy: 7000, ncap: null, onSale: false, halo: false,
      g: { build: 70, drive: 58, practicality: 73, value: 79, design: 72, running: 26 }, verdict: 'A plush American-style crossover with a creamy V6 and catastrophic thirst. Rare diesel makes more sense, barely.', issues: ['CVT failure is ruinously expensive', 'Road tax and fuel costs sting'], buy: 'Diesel automatic with full history; V6 only as a low-mile indulgence.', tags: ['wafty', 'left-field', 'depreciation-king', 'money-pit-risk', 'posh-interior'], rivals: ['lexus-rx-al10', 'volvo-xc60-p3', 'infiniti-fx-s51'] },

    { model: 'Cube', gen: 'Z12', years: [2010, 2011], bodies: ['mpv'], segment: 'city', priceNew: [14000, 17000], used: [4500, 10000], accel: 11.3, power: [110, 110], top: 109, fuels: ['petrol'], mpg: 42, ev: null, seats: 5, doors: 5, boot: 255, len: 3980, kg: 1250, mpy: 5500, ncap: [4, 2010], onSale: false, halo: false,
      g: { build: 72, drive: 51, practicality: 79, value: 76, design: 94, running: 75 }, verdict: 'An asymmetric Japanese living room on wheels. Official UK sales flopped; its weirdness has only become more desirable.', issues: ['CVT needs regular fluid changes', 'Body and trim parts are scarce'], buy: 'UK manual Kaizen with complete trim and corrosion-free rear floor.', tags: ['boxy-icon', 'retro-charm', 'left-field', 'future-classic', 'tardis', 'head-turner'], rivals: ['kia-soul-am', 'toyota-iq-aj10', 'honda-jazz-ge4'] }
  ]
};
