// Nissan — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Nissan',
  cars: [
    { model: 'Micra', gen: 'K14', years: [2017, 2023], bodies: ['hatch'], segment: 'supermini',
      priceNew: [13000, 19000], used: [7000, 14000], accel: 9.9, power: [71, 117], top: 121,
      fuels: ['petrol'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 300, len: 3999, kg: 1015,
      mpy: 7000, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 72, drive: 66, practicality: 66, value: 78, design: 68, running: 86 },
      verdict: 'The Micra that finally grew out of the granny image — sharp lines, tidy manners, forgettable but faultless.',
      issues: ['Rear headroom under the swoosh', 'CVT best avoided'],
      buy: '1.0 IG-T 92 Acenta manual — honest miles for pennies.',
      tags: ['first-car-friendly', 'cheap-to-run', 'city-darling', 'bargain-hero'],
      rivals: ['renault-clio-v', 'ford-fiesta-mk8', 'volkswagen-polo-mk6'] },

    { model: 'Juke', gen: 'F16', years: [2019, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [21000, 30000], used: [12000, 25000], accel: 8.7, power: [114, 143], top: 124,
      fuels: ['petrol', 'hybrid'], mpg: 49, ev: null, seats: 5, doors: 5, boot: 422, len: 4210, kg: 1220,
      mpy: 8500, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 74, drive: 66, practicality: 74, value: 76, design: 70, running: 82 },
      verdict: 'The odd duck that grew up handsome-ish. Gen two fixed the boot and back seats; hybrid fixed the bills.',
      issues: ['DCT low-speed shuffle', 'Firm on big alloys'],
      buy: 'Hybrid N-Connecta — city frugality, motorway calm.',
      tags: ['city-darling', 'crowd-pleaser', 'cheap-to-run', 'school-run'],
      rivals: ['ford-puma-mk1', 'toyota-c-hr-ax10', 'renault-captur-ii'] },

    { model: 'Qashqai', gen: 'J11', years: [2014, 2021], bodies: ['suv'], segment: 'family-suv',
      priceNew: [19000, 32000], used: [8000, 20000], accel: 8.9, power: [110, 163], top: 124,
      fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 430, len: 4394, kg: 1390,
      mpy: 10000, ncap: [5, 2014], onSale: false, halo: false,
      g: { build: 74, drive: 64, practicality: 80, value: 80, design: 62, running: 80 },
      verdict: 'The car that invented the crossover school run, iteration two. Ubiquitous for a reason: easy, roomy, cheap to keep.',
      issues: ['1.2 DIG-T chain rattle — check history', 'CVT reliability patchy'],
      buy: '1.3 DIG-T 140 N-Connecta manual, 2019-on.',
      tags: ['school-run', 'crowd-pleaser', 'cheap-to-run', 'bargain-hero'],
      rivals: ['kia-sportage-ql', 'seat-ateca-5fp', 'skoda-karoq-nu7'] },

    { model: 'Qashqai', gen: 'J12', years: [2021, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [27000, 43000], used: [16000, 34000], accel: 7.9, power: [140, 190], top: 105,
      fuels: ['petrol', 'hybrid'], mpg: 53, ev: null, seats: 5, doors: 5, boot: 504, len: 4425, kg: 1415,
      mpy: 10000, ncap: [5, 2021], onSale: true, halo: false,
      g: { build: 80, drive: 66, practicality: 84, value: 78, design: 70, running: 84 },
      verdict: 'Britain’s default family car, refined again. e-Power hybrid drives electric-smooth without ever plugging in.',
      issues: ['e-Power thirstier on motorways', 'Light steering'],
      buy: 'e-Power N-Connecta — the town-heavy family pick.',
      tags: ['school-run', 'crowd-pleaser', 'cheap-to-run', 'tardis'],
      rivals: ['kia-sportage-nq5', 'hyundai-tucson-nx4', 'toyota-rav4-xa50'] },

    { model: 'X-Trail', gen: 'T33', years: [2022, 0], bodies: ['suv'], segment: 'seven-seater',
      priceNew: [36000, 50000], used: [24000, 42000], accel: 7.0, power: [163, 213], top: 111,
      fuels: ['hybrid'], mpg: 48, ev: null, seats: 7, doors: 5, boot: 585, len: 4680, kg: 1830,
      mpy: 10500, ncap: [5, 2021], onSale: true, halo: false,
      g: { build: 80, drive: 66, practicality: 88, value: 76, design: 66, running: 80 },
      verdict: 'The Qashqai XL: seven seats, e-Power calm, zero drama. The family wagon that flies under every radar.',
      issues: ['Row three occasional-use only', 'e-Power motorway thirst'],
      buy: 'e-Power e-4orce N-Connecta 7-seat.',
      tags: ['seven-seats', 'family-bus', 'school-run', 'cheap-to-run', 'dog-friendly'],
      rivals: ['kia-sorento-mq4', 'hyundai-santa-fe-tm', 'skoda-kodiaq-ns7'] },

    { model: 'Leaf', gen: 'ZE1', years: [2018, 2024], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [26000, 36000], used: [8000, 18000], accel: 6.9, power: [150, 217], top: 98,
      fuels: ['ev'], mpg: null, ev: 239, seats: 5, doors: 5, boot: 435, len: 4490, kg: 1580,
      mpy: 7500, ncap: [5, 2018], onSale: false, halo: false,
      g: { build: 76, drive: 64, practicality: 76, value: 80, design: 58, running: 88 },
      verdict: 'The EV pioneer’s second act — CHAdeMO plug aged it, prices collapsed it, which makes it a used-town-car steal.',
      issues: ['CHAdeMO rapid plug is legacy tech', 'No battery thermal management — check health'],
      buy: 'e+ 62kWh Tekna, battery report in hand, for city duty.',
      tags: ['cheap-to-run', 'city-darling', 'bargain-hero', 'silent-cruiser', 'depreciation-king'],
      rivals: ['volkswagen-id-3-e11', 'renault-zoe-ph2', 'hyundai-kona-os'] },

    { model: 'Ariya', gen: 'FE0', years: [2022, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [40000, 55000], used: [20000, 38000], accel: 5.1, power: [217, 394], top: 124,
      fuels: ['ev'], mpg: null, ev: 329, seats: 5, doors: 5, boot: 466, len: 4595, kg: 1980,
      mpy: 9000, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 82, drive: 70, practicality: 80, value: 76, design: 78, running: 84 },
      verdict: 'Nissan’s lounge-on-wheels EV — lovely cabin, calm manners, oddly overlooked. Used prices are quietly superb.',
      issues: ['Infotainment a step behind', 'Brand EV mindshare stolen by rivals'],
      buy: '87kWh Evolve used — luxury-car feel for £26k.',
      tags: ['silent-cruiser', 'posh-interior', 'left-field', 'depreciation-king', 'school-run'],
      rivals: ['volkswagen-id-4-id-5-e21', 'toyota-bz4x-ea10', 'tesla-model-y-juniper'] },

    { model: '370Z', gen: 'Z34', years: [2009, 2020], bodies: ['coupe', 'convertible'], segment: 'sports',
      priceNew: [27000, 40000], used: [12000, 26000], accel: 5.2, power: [328, 344], top: 155,
      fuels: ['petrol'], mpg: 27, ev: null, seats: 2, doors: 2, boot: 235, len: 4250, kg: 1496,
      mpy: 5000, ncap: null, onSale: false, halo: false,
      g: { build: 74, drive: 80, practicality: 38, value: 80, design: 72, running: 44 },
      verdict: 'Old-school muscle coupé: big atmo V6, proper manual, zero pretence. Nismo versions will be remembered fondly.',
      issues: ['Thirsty and firm', 'Interior aged a decade early'],
      buy: 'GT manual with the SynchroRev box — analogue theatre.',
      tags: ['muscular', 'analogue-joy', 'v8-soundtrack', 'bargain-hero', 'modern-classic', 'rev-happy'],
      rivals: ['ford-mustang-s550', 'toyota-gt86-zn6', 'bmw-2-series-coupe-f22'] },

    { model: 'GT-R', gen: 'R35', years: [2009, 2022], bodies: ['coupe'], segment: 'super-coupe',
      priceNew: [60000, 100000], used: [45000, 90000], accel: 2.8, power: [480, 570], top: 196,
      fuels: ['petrol'], mpg: 23, ev: null, seats: 4, doors: 2, boot: 315, len: 4710, kg: 1740,
      mpy: 4000, ncap: null, onSale: false, halo: true,
      g: { build: 84, drive: 90, practicality: 52, value: 74, design: 76, running: 30 },
      verdict: 'Godzilla: the giant-killer that humbled supercars for 911 money. Servicing is a religion — join it or don’t buy.',
      issues: ['Gearbox and consumables cost supercar money', 'Modified cars everywhere — stock is king'],
      buy: '2017-on with the nicer cabin, standard, obsessive history.',
      tags: ['autobahn-stormer', 'track-day', 'tech-fest', 'future-classic', 'muscular', 'head-turner'],
      rivals: ['porsche-911-991', 'audi-r8-4s', 'bmw-m5-f90'] },

    { model: 'Navara', gen: 'D23', years: [2016, 2022], bodies: ['pickup'], segment: 'pickup',
      priceNew: [24000, 38000], used: [14000, 28000], accel: 10.8, power: [163, 190], top: 114,
      fuels: ['diesel'], mpg: 40, ev: null, seats: 5, doors: 4, boot: 1000, len: 5330, kg: 2075,
      mpy: 12000, ncap: [5, 2015], onSale: false, halo: false,
      g: { build: 76, drive: 60, practicality: 84, value: 78, design: 60, running: 60 },
      verdict: 'The coil-sprung pickup that rode like a car — well, closer than the rest. Honest tool, sensible money used.',
      issues: ['Earlier D40 chassis-rust saga tainted the name (D23 fine)', 'DPF wants long runs'],
      buy: 'Tekna double cab 190 auto — the family-friendly farm truck.',
      tags: ['chunky-4x4', 'tow-car', 'go-anywhere', 'bargain-hero', 'adventure-ready'],
      rivals: ['ford-ranger-t6-2', 'toyota-hilux-an120', 'mitsubishi-l200-mk5'] },

    { model: 'Note', gen: 'E12', years: [2013, 2017], bodies: ['mpv'], segment: 'supermini',
      priceNew: [12000, 18000], used: [4000, 9000], accel: 11.9, power: [80, 98], top: 112,
      fuels: ['petrol', 'diesel'], mpg: 55, ev: null, seats: 5, doors: 5, boot: 325, len: 4100, kg: 1055,
      mpy: 7000, ncap: [4, 2013], onSale: false, halo: false,
      g: { build: 72, drive: 56, practicality: 82, value: 82, design: 48, running: 88 },
      verdict: 'A supermini-MPV with sliding-bench cleverness and pensioner-proof reliability. Deeply uncool, deeply useful.',
      issues: ['Style went missing', 'CVT drone'],
      buy: '1.2 Acenta Premium — the golf-club car park special.',
      tags: ['tardis', 'cheap-to-run', 'bargain-hero', 'first-car-friendly'],
      rivals: ['honda-jazz-ge4', 'toyota-yaris-xp130', 'suzuki-swift-zc72'] }
  ]
};
