// Peugeot — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Peugeot',
  cars: [
    { model: '208', gen: 'P21', years: [2019, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [18000, 27000], used: [9000, 22000], accel: 8.1, power: [75, 156], top: 119,
      fuels: ['petrol', 'ev'], mpg: 54, ev: 248, seats: 5, doors: 5, boot: 311, len: 4055, kg: 1158,
      mpy: 8000, ncap: [4, 2019], onSale: true, halo: false,
      g: { build: 78, drive: 70, practicality: 66, value: 78, design: 84, running: 86 },
      verdict: 'The best-dressed supermini — fang DRLs, tiny wheel, i-Cockpit drama. e-208 twin makes the same case on volts.',
      issues: ['Small wheel blocks dials for some', 'Rear space tight'],
      buy: 'PureTech 100 GT, or e-208 51kWh used at bargain rates.',
      tags: ['head-turner', 'city-darling', 'sleek', 'cheap-to-run', 'first-car-friendly'],
      rivals: ['renault-clio-v', 'volkswagen-polo-mk6', 'ford-fiesta-mk8'] },

    { model: '308', gen: 'P52', years: [2022, 0], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [25000, 38000], used: [14000, 30000], accel: 7.5, power: [110, 225], top: 130,
      fuels: ['petrol', 'diesel', 'phev', 'ev'], mpg: 55, ev: 40, seats: 5, doors: 5, boot: 412, len: 4367, kg: 1264,
      mpy: 9000, ncap: [4, 2022], onSale: true, halo: false,
      g: { build: 82, drive: 72, practicality: 76, value: 76, design: 86, running: 82 },
      verdict: 'Lion-fanged looks and a cabin from a concept sketch. The SW estate is the stylish family wagon few consider.',
      issues: ['i-Cockpit ergonomics divide', 'PureTech belt history — check'],
      buy: 'Hybrid 180 GT SW — French flair, sensible bills.',
      tags: ['sleek', 'head-turner', 'school-run', 'posh-interior', 'left-field'],
      rivals: ['volkswagen-golf-mk8', 'skoda-octavia-mk4', 'renault-megane-e-tech-bcb'] },

    { model: '3008', gen: 'P84', years: [2016, 2023], bodies: ['suv'], segment: 'family-suv',
      priceNew: [24000, 40000], used: [11000, 28000], accel: 8.9, power: [130, 300], top: 135,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 50, ev: 36, seats: 5, doors: 5, boot: 520, len: 4447, kg: 1375,
      mpy: 10000, ncap: [5, 2016], onSale: false, halo: false,
      g: { build: 80, drive: 68, practicality: 82, value: 80, design: 84, running: 78 },
      verdict: 'The crossover that made mainstream interesting again — sculpted cabin, sharp suit, honest money used.',
      issues: ['PureTech 1.2 wet-belt — service history vital', 'Infotainment sluggish'],
      buy: '1.5 BlueHDi GT Line — the sweet-running sensible one.',
      tags: ['head-turner', 'school-run', 'posh-interior', 'crowd-pleaser', 'bargain-hero'],
      rivals: ['nissan-qashqai-j11', 'kia-sportage-ql', 'seat-ateca-5fp'] },

    { model: 'e-3008', gen: 'P64', years: [2024, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [46000, 55000], used: [34000, 46000], accel: 6.4, power: [210, 325], top: 105,
      fuels: ['ev'], mpg: null, ev: 435, seats: 5, doors: 5, boot: 520, len: 4542, kg: 2108,
      mpy: 9500, ncap: null, onSale: true, halo: false,
      g: { build: 82, drive: 68, practicality: 80, value: 74, design: 86, running: 84 },
      verdict: 'The 435-mile family EV with the panoramic-screen fastback swagger. Long Range spec out-distances Teslas.',
      issues: ['Priced above the badge’s comfort zone', 'Heavier than it feels'],
      buy: 'Long Range 98kWh Allure — the range champion.',
      tags: ['sleek', 'silent-cruiser', 'tech-fest', 'school-run', 'head-turner'],
      rivals: ['renault-scenic-e-tech-bcm', 'skoda-enyaq-5az', 'tesla-model-y-juniper'] },

    { model: '5008', gen: 'P87', years: [2017, 2024], bodies: ['suv'], segment: 'seven-seater',
      priceNew: [27000, 42000], used: [13000, 32000], accel: 8.9, power: [130, 180], top: 130,
      fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 7, doors: 5, boot: 780, len: 4641, kg: 1450,
      mpy: 10500, ncap: [5, 2016], onSale: false, halo: false,
      g: { build: 80, drive: 66, practicality: 90, value: 82, design: 82, running: 78 },
      verdict: 'Seven seats with actual style — three individual middle chairs, concept cabin, sensible bills. Family design done.',
      issues: ['PureTech wet-belt saga — insist on records', 'Row three snug'],
      buy: '1.5 BlueHDi 130 GT — the elegant school bus.',
      tags: ['seven-seats', 'family-bus', 'head-turner', 'tardis', 'bargain-hero', 'school-run'],
      rivals: ['skoda-kodiaq-ns7', 'kia-sorento-mq4', 'nissan-x-trail-t33'] },

    { model: '508', gen: 'R8', years: [2019, 2024], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [28000, 45000], used: [13000, 30000], accel: 5.2, power: [130, 360], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 52, ev: 33, seats: 5, doors: 5, boot: 487, len: 4750, kg: 1420,
      mpy: 10000, ncap: [5, 2018], onSale: false, halo: false,
      g: { build: 80, drive: 72, practicality: 76, value: 80, design: 88, running: 76 },
      verdict: 'The fastback that out-styled the Germans and got ignored for it. PSE version is a 360bhp curiosity. Used = design bargain.',
      issues: ['Frameless doors need seal care', 'Badge snobbery hurts resale (your gain)'],
      buy: 'GT BlueHDi 180 SW — the beautiful contrarian estate.',
      tags: ['sleek', 'head-turner', 'left-field', 'bargain-hero', 'grand-tourer'],
      rivals: ['volkswagen-arteon-3h', 'mazda-6-gj', 'bmw-3-series-g20'] },

    { model: '2008', gen: 'P24', years: [2019, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [21000, 32000], used: [11000, 25000], accel: 8.2, power: [100, 156], top: 119,
      fuels: ['petrol', 'diesel', 'ev'], mpg: 52, ev: 250, seats: 5, doors: 5, boot: 434, len: 4300, kg: 1263,
      mpy: 8500, ncap: [4, 2019], onSale: true, halo: false,
      g: { build: 78, drive: 66, practicality: 78, value: 78, design: 82, running: 84 },
      verdict: 'Sharp-suited small crossover; the e-2008 does the same look with 250 quiet miles. Style per pound leader.',
      issues: ['PureTech belt — records again', 'i-Cockpit fit varies by driver'],
      buy: 'e-2008 54kWh GT used — the stylish silent school-runner.',
      tags: ['head-turner', 'city-darling', 'school-run', 'cheap-to-run'],
      rivals: ['renault-captur-ii', 'ford-puma-mk1', 'vauxhall-mokka-b'] },

    { model: 'RCZ', gen: 'T75', years: [2010, 2015], bodies: ['coupe'], segment: 'sports',
      priceNew: [22000, 32000], used: [5000, 12000], accel: 5.9, power: [156, 270], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 42, ev: null, seats: 4, doors: 2, boot: 384, len: 4287, kg: 1297,
      mpy: 6000, ncap: null, onSale: false, halo: false,
      g: { build: 76, drive: 76, practicality: 52, value: 82, design: 88, running: 70 },
      verdict: 'The double-bubble beauty that outshone the TT on looks and undercuts it used. RCZ R is a proper 270bhp send-off.',
      issues: ['THP engine chain/carbon history needed', 'Rear seats for coats'],
      buy: 'RCZ R Coupé — the collectible; 1.6 THP 156 for the style alone.',
      tags: ['head-turner', 'sleek', 'left-field', 'bargain-hero', 'modern-classic', 'future-classic'],
      rivals: ['audi-tt-8j', 'volkswagen-scirocco-mk3', 'toyota-gt86-zn6'] },

    { model: '205 GTI', gen: 'Classic', years: [1984, 1994], bodies: ['hatch'], segment: 'hot-hatch',
      priceNew: [8000, 12000], used: [12000, 35000], accel: 7.8, power: [105, 130], top: 122,
      fuels: ['petrol'], mpg: 36, ev: null, seats: 4, doors: 3, boot: 216, len: 3705, kg: 880,
      mpy: 3000, ncap: null, onSale: false, halo: false,
      g: { build: 60, drive: 94, practicality: 46, value: 60, design: 90, running: 66 },
      verdict: 'The greatest hot hatch of all time, now blue-chip. Lift-off oversteer as a personality trait. Investment with a throttle.',
      issues: ['Rust everywhere — sills, arches, scuttle', 'Values reward originality only'],
      buy: '1.9 GTI, original, documented, garaged. Pay the strong money.',
      tags: ['modern-classic', 'analogue-joy', 'lightweight', 'b-road-hero', 'future-classic', 'head-turner'],
      rivals: ['volkswagen-golf-gti-mk2', 'renault-5-gt-turbo-classic', 'ford-fiesta-xr2-classic'] },

    { model: 'e-208', gen: 'P21e', years: [2020, 0], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [28000, 34000], used: [10000, 22000], accel: 8.1, power: [136, 156], top: 93,
      fuels: ['ev'], mpg: null, ev: 248, seats: 5, doors: 5, boot: 311, len: 4055, kg: 1455,
      mpy: 7500, ncap: [4, 2019], onSale: true, halo: false,
      g: { build: 78, drive: 68, practicality: 64, value: 80, design: 84, running: 88 },
      verdict: 'The pretty EV supermini at properly tempting used money — same fangs, zero fuel, city-perfect.',
      issues: ['Real range nearer 190 in winter', 'Rear seat tight'],
      buy: '51kWh GT used — style and volts for Fiesta money.',
      tags: ['city-darling', 'head-turner', 'cheap-to-run', 'silent-cruiser', 'bargain-hero'],
      rivals: ['renault-zoe-ph2', 'fiat-500e-332', 'mini-electric-f56'] }
  ]
};
