// Porsche — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Porsche',
  cars: [
    { model: 'Boxster', gen: '987', years: [2005, 2012], bodies: ['convertible'], segment: 'roadster-classic',
      priceNew: [34000, 46000], used: [12000, 25000], accel: 5.2, power: [240, 320], top: 170,
      fuels: ['petrol'], mpg: 30, ev: null, seats: 2, doors: 2, boot: 280, len: 4329, kg: 1355,
      mpy: 5000, ncap: null, onSale: false, halo: false,
      g: { build: 82, drive: 92, practicality: 40, value: 84, design: 78, running: 52 },
      verdict: 'Mid-engined flat-six magic from £12k — the great affordable Porsche. Spyder aside, the S is all you need.',
      issues: ['IMS/bore-score fear on early 2.7s (check done)', 'Roof drains and hood wear'],
      buy: '987.2 Boxster S PDK or manual, 2009-on — the sorted engines.',
      tags: ['drivers-car', 'modern-classic', 'analogue-joy', 'b-road-hero', 'bargain-hero', 'rev-happy'],
      rivals: ['bmw-z4-e89', 'mercedes-benz-slk-r172', 'audi-tt-8j'] },

    { model: '718 Cayman', gen: '982', years: [2016, 0], bodies: ['coupe'], segment: 'sports',
      priceNew: [45000, 85000], used: [32000, 75000], accel: 4.0, power: [300, 420], top: 180,
      fuels: ['petrol'], mpg: 32, ev: null, seats: 2, doors: 2, boot: 425, len: 4379, kg: 1365,
      mpy: 5000, ncap: null, onSale: true, halo: false,
      g: { build: 88, drive: 96, practicality: 44, value: 78, design: 84, running: 50 },
      verdict: 'The best-handling car money can sensibly buy. Four-pot versions sound flat; the GTS 4.0 is automotive perfection.',
      issues: ['Four-cylinder soundtrack divides', 'Options inflate — buy used, spec done'],
      buy: 'GTS 4.0 manual. If budget bites, a 2.5 S — never regret it.',
      tags: ['drivers-car', 'future-classic', 'b-road-hero', 'track-day', 'head-turner', 'rev-happy'],
      rivals: ['bmw-m2-g87', 'toyota-gr-supra-a90', 'alpine-a110-as1'] },

    { model: '911', gen: '997', years: [2004, 2012], bodies: ['coupe', 'convertible'], segment: 'super-coupe',
      priceNew: [60000, 100000], used: [28000, 70000], accel: 4.3, power: [325, 480], top: 188,
      fuels: ['petrol'], mpg: 26, ev: null, seats: 4, doors: 2, boot: 135, len: 4427, kg: 1425,
      mpy: 4500, ncap: null, onSale: false, halo: false,
      g: { build: 84, drive: 94, practicality: 44, value: 78, design: 88, running: 44 },
      verdict: 'The modern-classic 911 sweet spot: hydraulic steering, compact body, values done falling. Gen2 is the keeper.',
      issues: ['Gen1 IMS/bore score — buy inspected', 'Coil packs, RMS weeps'],
      buy: '997.2 Carrera S manual, sports exhaust, full OPC history.',
      tags: ['modern-classic', 'drivers-car', 'future-classic', 'analogue-joy', 'head-turner', 'rev-happy'],
      rivals: ['bmw-m3-e92', 'audi-r8-42', 'jaguar-xkr-x150'] },

    { model: '911', gen: '991', years: [2011, 2019], bodies: ['coupe', 'convertible'], segment: 'super-coupe',
      priceNew: [73000, 130000], used: [45000, 100000], accel: 3.4, power: [350, 580], top: 196,
      fuels: ['petrol'], mpg: 30, ev: null, seats: 4, doors: 2, boot: 145, len: 4491, kg: 1430,
      mpy: 4500, ncap: null, onSale: false, halo: true,
      g: { build: 88, drive: 92, practicality: 46, value: 72, design: 86, running: 42 },
      verdict: 'Bigger, calmer, still telepathic. The 991.1 kept atmo engines; the .2 turbos brought everyday thump. No wrong answers.',
      issues: ['Big-spec cars hide tired suspensions', 'PDK service history essential'],
      buy: '991.2 Carrera GTS manual — the modern 911 distilled.',
      tags: ['drivers-car', 'grand-tourer', 'head-turner', 'future-classic', 'autobahn-stormer'],
      rivals: ['audi-r8-4s', 'mercedes-amg-gt-c190', 'aston-martin-vantage-am6'] },

    { model: '911', gen: '992', years: [2019, 0], bodies: ['coupe', 'convertible'], segment: 'super-coupe',
      priceNew: [90000, 170000], used: [72000, 150000], accel: 2.7, power: [385, 650], top: 199,
      fuels: ['petrol', 'hybrid'], mpg: 28, ev: null, seats: 4, doors: 2, boot: 132, len: 4519, kg: 1505,
      mpy: 4500, ncap: null, onSale: true, halo: true,
      g: { build: 92, drive: 94, practicality: 48, value: 66, design: 84, running: 40 },
      verdict: 'The everything sports car, now digital-widescreen and hybrid-tinged. Still the one every rival is measured against.',
      issues: ['Wide body fills UK lanes', 'Options gouge continues'],
      buy: 'Carrera T manual — purity spec at the “affordable” end.',
      tags: ['drivers-car', 'head-turner', 'grand-tourer', 'autobahn-stormer', 'tech-fest'],
      rivals: ['mercedes-amg-gt-c192', 'aston-martin-vantage-am6', 'bmw-m3-g80'] },

    { model: 'Macan', gen: '95B', years: [2014, 2024], bodies: ['suv'], segment: 'family-suv',
      priceNew: [46000, 75000], used: [20000, 62000], accel: 4.3, power: [245, 440], top: 169,
      fuels: ['petrol', 'diesel'], mpg: 33, ev: null, seats: 5, doors: 5, boot: 500, len: 4696, kg: 1845,
      mpy: 8500, ncap: [5, 2014], onSale: false, halo: false,
      g: { build: 88, drive: 86, practicality: 74, value: 72, design: 78, running: 44 },
      verdict: 'The SUV that drives like a hot hatch — the class benchmark for a decade straight. Diesel-era cars are used gold.',
      issues: ['Options decide value — buy the right spec', 'Transfer-case wear on early cars'],
      buy: 'Macan S 2019-on, air suspension, Sport Chrono, PASM.',
      tags: ['drivers-car', 'school-run', 'posh-interior', 'head-turner', 'crowd-pleaser'],
      rivals: ['bmw-x3-g01', 'range-rover-velar-l560', 'audi-q5-fy'] },

    { model: 'Macan Electric', gen: 'XAB', years: [2024, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [69000, 95000], used: [55000, 85000], accel: 3.3, power: [340, 639], top: 162,
      fuels: ['ev'], mpg: null, ev: 380, seats: 5, doors: 5, boot: 540, len: 4784, kg: 2405,
      mpy: 8500, ncap: [5, 2024], onSale: true, halo: true,
      g: { build: 90, drive: 86, practicality: 78, value: 64, design: 80, running: 74 },
      verdict: 'The electric Macan kept the chassis brilliance and added 380 miles of range. Expensive; excellent; inevitable.',
      issues: ['Price walks into Cayenne country', 'Weight masked, not absent'],
      buy: 'Macan 4 with air suspension — the balanced one.',
      tags: ['silent-cruiser', 'drivers-car', 'tech-fest', 'posh-interior', 'head-turner'],
      rivals: ['audi-q6-e-tron-f5', 'bmw-ix-i20', 'tesla-model-y-juniper'] },

    { model: 'Cayenne', gen: 'E3', years: [2018, 0], bodies: ['suv', 'coupe'], segment: 'large-suv',
      priceNew: [58000, 130000], used: [32000, 100000], accel: 3.9, power: [340, 680], top: 183,
      fuels: ['petrol', 'phev'], mpg: 25, ev: 45, seats: 5, doors: 5, boot: 772, len: 4918, kg: 2055,
      mpy: 8500, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 90, drive: 86, practicality: 84, value: 68, design: 76, running: 36 },
      verdict: 'The sports car of big SUVs, generation three: absurdly capable, properly plush. E-Hybrid blends tax and thunder.',
      issues: ['Thirst without the plug', 'Options mean £30k spread between similar cars'],
      buy: 'E-Hybrid with air suspension and rear-axle steer.',
      tags: ['muscular', 'drivers-car', 'posh-interior', 'tow-car', 'autobahn-stormer'],
      rivals: ['bmw-x5-g05', 'range-rover-sport-l461', 'audi-q7-4m'] },

    { model: 'Panamera', gen: '971', years: [2016, 2024], bodies: ['saloon', 'estate'], segment: 'luxury',
      priceNew: [70000, 140000], used: [30000, 90000], accel: 3.1, power: [330, 700], top: 196,
      fuels: ['petrol', 'phev'], mpg: 28, ev: 32, seats: 4, doors: 5, boot: 495, len: 5049, kg: 1995,
      mpy: 7500, ncap: null, onSale: false, halo: false,
      g: { build: 90, drive: 86, practicality: 74, value: 70, design: 80, running: 36 },
      verdict: 'A 911 for four adults and their luggage. Sport Turismo estate is peak want; used Turbos are savage value.',
      issues: ['Complex PHEV systems age — history vital', 'Coolant pipes on early V8s'],
      buy: '4S Diesel or Turbo Sport Turismo — the sublime absurdity.',
      tags: ['grand-tourer', 'autobahn-stormer', 'posh-interior', 'sleek', 'depreciation-king'],
      rivals: ['mercedes-benz-cls-c257', 'bmw-m5-f90', 'audi-rs7-c8'] },

    { model: 'Taycan', gen: 'Y1A', years: [2020, 0], bodies: ['saloon', 'estate'], segment: 'ev-native',
      priceNew: [75000, 160000], used: [35000, 110000], accel: 2.8, power: [408, 761], top: 162,
      fuels: ['ev'], mpg: null, ev: 315, seats: 4, doors: 4, boot: 407, len: 4963, kg: 2205,
      mpy: 7500, ncap: [5, 2019], onSale: true, halo: true,
      g: { build: 92, drive: 90, practicality: 64, value: 68, design: 88, running: 62 },
      verdict: 'The EV that made electric feel like Porsche. Two-year-old cars at half price are the used bargain of the decade.',
      issues: ['Range modest vs rivals (efficiency good)', 'Early software recalls — updates done?'],
      buy: 'Used 4S with Performance Battery Plus; Sport Turismo for dogs.',
      tags: ['silent-cruiser', 'drivers-car', 'head-turner', 'depreciation-king', 'sleek', 'tech-fest'],
      rivals: ['audi-e-tron-gt-f83', 'tesla-model-s-refresh', 'bmw-i5-g60'] },

    { model: 'Cayman', gen: '987C', years: [2006, 2013], bodies: ['coupe'], segment: 'roadster-classic',
      priceNew: [37000, 45000], used: [13000, 26000], accel: 4.9, power: [245, 330], top: 172,
      fuels: ['petrol'], mpg: 30, ev: null, seats: 2, doors: 2, boot: 410, len: 4347, kg: 1330,
      mpy: 5000, ncap: null, onSale: false, halo: false,
      g: { build: 82, drive: 93, practicality: 42, value: 82, design: 80, running: 52 },
      verdict: 'The coupé Boxster that out-handles 911s of its era. Gen2 cars fixed the engines; prices now creep upward.',
      issues: ['Early 2.7/3.4 bore-score checks advised', 'Tired suspension bushings common'],
      buy: '987.2 Cayman S manual with LSD — the analogue keeper.',
      tags: ['drivers-car', 'modern-classic', 'analogue-joy', 'future-classic', 'b-road-hero', 'lightweight'],
      rivals: ['porsche-boxster-987', 'bmw-m3-e92', 'nissan-370z-z34'] }
  ]
};
