// Renault — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Renault',
  cars: [
    { model: 'Clio', gen: 'IV', years: [2013, 2019], bodies: ['hatch'], segment: 'supermini',
      priceNew: [11000, 18000], used: [4000, 10000], accel: 6.6, power: [75, 220], top: 146,
      fuels: ['petrol', 'diesel'], mpg: 55, ev: null, seats: 5, doors: 5, boot: 300, len: 4063, kg: 1070,
      mpy: 7500, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 70, drive: 70, practicality: 66, value: 80, design: 74, running: 86 },
      verdict: 'Pretty, frugal French pop — and the RS 220 Trophy hiding in the range is a genuine firecracker.',
      issues: ['EDC gearbox history matters', 'Interior plastics scratch'],
      buy: '0.9 TCe Dynamique for sense; RS Trophy for the B-road.',
      tags: ['city-darling', 'cheap-to-run', 'first-car-friendly', 'bargain-hero'],
      rivals: ['ford-fiesta-mk7', 'peugeot-208-a9', 'volkswagen-polo-mk5'] },

    { model: 'Clio', gen: 'V', years: [2019, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [17000, 25000], used: [9000, 20000], accel: 9.0, power: [65, 145], top: 124,
      fuels: ['petrol', 'hybrid'], mpg: 60, ev: null, seats: 5, doors: 5, boot: 391, len: 4050, kg: 1178,
      mpy: 8000, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 80, drive: 72, practicality: 74, value: 84, design: 78, running: 88 },
      verdict: 'The class valedictorian: hybrid at 60mpg, cabin above its station, biggest boot of the small cars. Quietly brilliant.',
      issues: ['Hybrid gearbox pauses at times', 'Rear space average'],
      buy: 'E-Tech Hybrid Techno — city sipper, motorway grown-up.',
      tags: ['cheap-to-run', 'city-darling', 'crowd-pleaser', 'first-car-friendly', 'bargain-hero'],
      rivals: ['toyota-yaris-xp210', 'volkswagen-polo-mk6', 'honda-jazz-gr'] },

    { model: 'Captur', gen: 'II', years: [2020, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [20000, 30000], used: [11000, 24000], accel: 8.6, power: [90, 160], top: 113,
      fuels: ['petrol', 'hybrid', 'phev'], mpg: 55, ev: 30, seats: 5, doors: 5, boot: 484, len: 4227, kg: 1234,
      mpy: 8500, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 78, drive: 66, practicality: 80, value: 80, design: 74, running: 86 },
      verdict: 'Sliding rear bench, hybrid thrift, Gallic style — the small crossover with actual clever bits.',
      issues: ['E-Tech shuffle at low speed', 'Light steering'],
      buy: 'E-Tech Hybrid Techno — the town family’s friend.',
      tags: ['city-darling', 'school-run', 'cheap-to-run', 'crowd-pleaser'],
      rivals: ['nissan-juke-f16', 'peugeot-2008-p24', 'toyota-yaris-cross-xp210'] },

    { model: 'Megane E-Tech', gen: 'BCB', years: [2022, 0], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [34000, 42000], used: [16000, 30000], accel: 7.4, power: [130, 220], top: 99,
      fuels: ['ev'], mpg: null, ev: 280, seats: 5, doors: 5, boot: 440, len: 4199, kg: 1636,
      mpy: 8500, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 82, drive: 74, practicality: 74, value: 80, design: 82, running: 86 },
      verdict: 'The chic French EV hatch — Google-native cabin, lovely to sit in, light on its feet. Used prices are a gift.',
      issues: ['Rear window slot-like', 'Ride firm on 20s'],
      buy: 'EV60 Techno used — design-led electrics for ID.3 money.',
      tags: ['sleek', 'city-darling', 'tech-fest', 'silent-cruiser', 'head-turner', 'cheap-to-run'],
      rivals: ['volkswagen-id-3-e11', 'cupra-born-k11', 'peugeot-e-308-p52'] },

    { model: '5 E-Tech', gen: 'BFB', years: [2024, 0], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [23000, 31000], used: [18000, 27000], accel: 8.0, power: [95, 150], top: 93,
      fuels: ['ev'], mpg: null, ev: 249, seats: 5, doors: 5, boot: 326, len: 3922, kg: 1449,
      mpy: 7500, ncap: [4, 2024], onSale: true, halo: false,
      g: { build: 82, drive: 78, practicality: 64, value: 86, design: 94, running: 88 },
      verdict: 'Car of the year, heart of the decade: retro-pop perfection at petrol-supermini money. The EV that makes you smile first.',
      issues: ['Boot modest', 'Waiting lists say everyone agrees'],
      buy: 'Comfort Range Techno in yellow. Obviously yellow.',
      tags: ['retro-charm', 'city-darling', 'head-turner', 'future-classic', 'cheap-to-run', 'bargain-hero'],
      rivals: ['mini-cooper-f66', 'fiat-500e-332', 'citroen-e-c3-cc21'] },

    { model: 'Zoe', gen: 'PH2', years: [2019, 2024], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [27000, 32000], used: [7000, 14000], accel: 9.5, power: [110, 135], top: 87,
      fuels: ['ev'], mpg: null, ev: 239, seats: 5, doors: 5, boot: 338, len: 4087, kg: 1502,
      mpy: 7000, ncap: null, onSale: false, halo: false,
      g: { build: 74, drive: 64, practicality: 68, value: 78, design: 62, running: 90 },
      verdict: '239 miles for eight grand used — the volume EV bargain. The zero-star 2021 NCAP retest stings, mind.',
      issues: ['2021 NCAP zero-star (removed side airbag)', 'CCS rapid optional — check fitted'],
      buy: 'R135 GT Line with CCS — the used city-EV value king.',
      tags: ['cheap-to-run', 'city-darling', 'bargain-hero', 'depreciation-king'],
      rivals: ['nissan-leaf-ze1', 'peugeot-e-208-p21', 'volkswagen-id-3-e11'] },

    { model: 'Scenic E-Tech', gen: 'BCM', years: [2024, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [37000, 46000], used: [28000, 40000], accel: 7.9, power: [170, 220], top: 105,
      fuels: ['ev'], mpg: null, ev: 379, seats: 5, doors: 5, boot: 545, len: 4470, kg: 1842,
      mpy: 9500, ncap: [5, 2024], onSale: true, halo: false,
      g: { build: 82, drive: 70, practicality: 84, value: 82, design: 78, running: 88 },
      verdict: 'The MPV name reborn as a 379-mile family EV — huge inside, sharp value. Another quiet Renault bullseye.',
      issues: ['Name confuses the school gate', 'No frunk'],
      buy: 'Long Range Techno — the family-EV spreadsheet winner.',
      tags: ['school-run', 'tardis', 'silent-cruiser', 'cheap-to-run', 'crowd-pleaser'],
      rivals: ['skoda-enyaq-5az', 'peugeot-e-3008-p64', 'volkswagen-id-4-id-5-e21'] },

    { model: 'Megane RS', gen: 'III', years: [2010, 2016], bodies: ['coupe'], segment: 'hot-hatch',
      priceNew: [24000, 30000], used: [10000, 22000], accel: 5.8, power: [250, 275], top: 158,
      fuels: ['petrol'], mpg: 34, ev: null, seats: 5, doors: 3, boot: 344, len: 4299, kg: 1387,
      mpy: 6000, ncap: [5, 2008], onSale: false, halo: false,
      g: { build: 70, drive: 92, practicality: 56, value: 80, design: 70, running: 62 },
      verdict: 'The benchmark front-driver of its decade — Cup chassis, hydraulic-feel steering, Trophy-R legend. Petrolhead catnip.',
      issues: ['Track use common — inspect', 'Clutch and gearbox wear'],
      buy: '265 Cup or 275 Trophy, standard, with the folder of receipts.',
      tags: ['drivers-car', 'track-day', 'b-road-hero', 'modern-classic', 'analogue-joy', 'bargain-hero'],
      rivals: ['honda-civic-type-r-fk2', 'volkswagen-golf-gti-mk7', 'ford-focus-st-mk3'] },

    { model: 'Twingo', gen: 'III', years: [2014, 2024], bodies: ['hatch'], segment: 'city',
      priceNew: [10000, 15000], used: [4500, 10000], accel: 10.8, power: [70, 110], top: 113,
      fuels: ['petrol', 'ev'], mpg: 52, ev: 118, seats: 4, doors: 5, boot: 188, len: 3595, kg: 940,
      mpy: 6000, ncap: [4, 2014], onSale: false, halo: false,
      g: { build: 68, drive: 68, practicality: 52, value: 74, design: 76, running: 88 },
      verdict: 'Rear-engined, rear-drive city car with a 4.3m turning circle — the 911 of postman’s rounds. Quirk done right.',
      issues: ['Boot is a glovebox', 'GT never came to UK officially in volume'],
      buy: 'TCe 90 Dynamique — town-carving charm for pennies.',
      tags: ['city-darling', 'left-field', 'retro-charm', 'cheap-to-run', 'first-car-friendly'],
      rivals: ['volkswagen-up-aa', 'fiat-500-312', 'smart-forfour-w453'] },

    { model: 'Espace', gen: 'IV', years: [2003, 2014], bodies: ['mpv'], segment: 'mpv-van',
      priceNew: [24000, 35000], used: [2000, 6000], accel: 8.9, power: [120, 240], top: 130,
      fuels: ['petrol', 'diesel'], mpg: 40, ev: null, seats: 7, doors: 5, boot: 800, len: 4661, kg: 1745,
      mpy: 9000, ncap: [5, 2003], onSale: false, halo: false,
      g: { build: 62, drive: 60, practicality: 90, value: 74, design: 66, running: 52 },
      verdict: 'The original MPV’s last true generation — glass everywhere, seats like armchairs, electronics like fireworks.',
      issues: ['Electrical gremlins galore', 'DPF and turbo age'],
      buy: 'Grand Espace 2.0 dCi Dynamique, cheap enough to forgive.',
      tags: ['van-with-windows', 'seven-seats', 'tardis', 'left-field', 'money-pit-risk', 'bargain-hero'],
      rivals: ['citroen-c4-grand-picasso-b78', 'ford-galaxy-mk3', 'seat-alhambra-7n'] }
  ]
};
