// SEAT — model-generations, UK market. Curated for Vroom. (Cupra in cupra.mjs)
export default {
  make: 'SEAT',
  cars: [
    { model: 'Ibiza', gen: '6F', years: [2017, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [16000, 24000], used: [9000, 19000], accel: 8.0, power: [80, 150], top: 134,
      fuels: ['petrol'], mpg: 53, ev: null, seats: 5, doors: 5, boot: 355, len: 4059, kg: 1091,
      mpy: 8000, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 78, drive: 74, practicality: 74, value: 84, design: 68, running: 84 },
      verdict: 'A Polo with more zest for less cash — roomy, tidy-handling, quietly one of the best small-car buys going.',
      issues: ['Interior plastics hard', 'No hybrid option'],
      buy: '1.0 TSI 110 FR — the fun-per-pound pick.',
      tags: ['first-car-friendly', 'bargain-hero', 'cheap-to-run', 'drivers-car', 'crowd-pleaser'],
      rivals: ['volkswagen-polo-mk6', 'skoda-fabia-pj', 'ford-fiesta-mk8'] },

    { model: 'Leon', gen: '5F', years: [2013, 2020], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [17000, 32000], used: [7000, 19000], accel: 4.9, power: [86, 300], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 54, ev: null, seats: 5, doors: 5, boot: 380, len: 4263, kg: 1220,
      mpy: 9000, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 78, drive: 76, practicality: 76, value: 86, design: 74, running: 82 },
      verdict: 'Golf mechanicals in sharper clothes at friendlier prices. Cupra 300 ST 4Drive was the family rocket bargain.',
      issues: ['DSG history', '1.4 TSI ACT sensible pick'],
      buy: '1.4 TSI 150 FR — or Cupra 290 for the budget R.',
      tags: ['bargain-hero', 'drivers-car', 'crowd-pleaser', 'cheap-to-run', 'discreet'],
      rivals: ['volkswagen-golf-mk7', 'skoda-octavia-mk3', 'ford-focus-mk4'] },

    { model: 'Leon', gen: 'K1', years: [2020, 0], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [22000, 35000], used: [13000, 27000], accel: 6.7, power: [90, 245], top: 155,
      fuels: ['petrol', 'phev'], mpg: 52, ev: 40, seats: 5, doors: 5, boot: 380, len: 4368, kg: 1245,
      mpy: 9000, ncap: [5, 2020], onSale: true, halo: false,
      g: { build: 78, drive: 74, practicality: 78, value: 82, design: 74, running: 82 },
      verdict: 'Handsome, keen and slightly forgotten as SEAT fades — which makes used ones the smart Golf-family buy.',
      issues: ['Touch-slider era ergonomics', 'Brand future uncertainty'],
      buy: 'e-Hybrid FR Sport estate — style, space, tax sense.',
      tags: ['bargain-hero', 'sleek', 'crowd-pleaser', 'cheap-to-run', 'discreet'],
      rivals: ['volkswagen-golf-mk8', 'skoda-octavia-mk4', 'cupra-leon-k1'] },

    { model: 'Arona', gen: 'KJ7', years: [2017, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [19000, 28000], used: [11000, 22000], accel: 8.2, power: [95, 150], top: 132,
      fuels: ['petrol'], mpg: 51, ev: null, seats: 5, doors: 5, boot: 400, len: 4138, kg: 1165,
      mpy: 8500, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 76, drive: 70, practicality: 76, value: 82, design: 66, running: 84 },
      verdict: 'An Ibiza on stilts and none the worse for it — light, willing, honest money. The small crossover without the flab.',
      issues: ['Firm-ish ride', 'Cabin plastics basic'],
      buy: '1.0 TSI 110 FR — the sensible cheerful choice.',
      tags: ['city-darling', 'cheap-to-run', 'first-car-friendly', 'bargain-hero'],
      rivals: ['volkswagen-t-cross-c11', 'ford-puma-mk1', 'renault-captur-ii'] },

    { model: 'Ateca', gen: '5FP', years: [2016, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [24000, 38000], used: [11000, 28000], accel: 5.2, power: [110, 300], top: 152,
      fuels: ['petrol', 'diesel'], mpg: 48, ev: null, seats: 5, doors: 5, boot: 510, len: 4363, kg: 1335,
      mpy: 10000, ncap: [5, 2016], onSale: true, halo: false,
      g: { build: 78, drive: 76, practicality: 82, value: 84, design: 66, running: 78 },
      verdict: 'The family SUV that steers like a hatch — the segment’s quiet dynamic champion at church-fête prices used.',
      issues: ['DSG shunt', 'Firm on 19s'],
      buy: '1.5 TSI 150 FR manual — the driver’s family crossover.',
      tags: ['drivers-car', 'school-run', 'bargain-hero', 'crowd-pleaser', 'dog-friendly'],
      rivals: ['skoda-karoq-nu7', 'nissan-qashqai-j12', 'volkswagen-tiguan-ad'] },

    { model: 'Alhambra', gen: '7N', years: [2010, 2020], bodies: ['mpv'], segment: 'seven-seater',
      priceNew: [25000, 38000], used: [8000, 22000], accel: 8.9, power: [115, 220], top: 136,
      fuels: ['petrol', 'diesel'], mpg: 48, ev: null, seats: 7, doors: 5, boot: 809, len: 4854, kg: 1795,
      mpy: 10500, ncap: [5, 2010], onSale: false, halo: false,
      g: { build: 78, drive: 62, practicality: 96, value: 86, design: 54, running: 74 },
      verdict: 'Sliding doors, seven adult seats, van-sized boot — the family logistics GOAT. Sharan twin, SEAT price.',
      issues: ['Sliding-door motors age', 'DSG at big miles'],
      buy: '2.0 TDI 150 SE Lux — the last great honest MPV.',
      tags: ['seven-seats', 'van-with-windows', 'tardis', 'family-bus', 'bargain-hero', 'dog-friendly'],
      rivals: ['ford-galaxy-mk3', 'volkswagen-touran-5t', 'citroen-grand-c4-spacetourer-b78'] }
  ]
};
