// Škoda — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Skoda',
  cars: [
    { model: 'Fabia', gen: 'PJ', years: [2021, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [16000, 24000], used: [10000, 20000], accel: 8.0, power: [65, 150], top: 139,
      fuels: ['petrol'], mpg: 54, ev: null, seats: 5, doors: 5, boot: 380, len: 4108, kg: 1107,
      mpy: 8000, ncap: [5, 2021], onSale: true, halo: false,
      g: { build: 80, drive: 68, practicality: 80, value: 84, design: 62, running: 86 },
      verdict: 'The biggest boot in supermini-land and VW bones for less. Zero excitement, total competence — Škoda in miniature.',
      issues: ['Base 65PS glacial', 'No hybrid option'],
      buy: '1.0 TSI 110 SE Comfort — the rational pick of the class.',
      tags: ['bargain-hero', 'cheap-to-run', 'first-car-friendly', 'tardis', 'crowd-pleaser'],
      rivals: ['volkswagen-polo-mk6', 'renault-clio-v', 'hyundai-i20-bc3'] },

    { model: 'Octavia', gen: 'Mk3', years: [2013, 2020], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [17000, 31000], used: [6000, 18000], accel: 6.7, power: [86, 245], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 55, ev: null, seats: 5, doors: 5, boot: 590, len: 4659, kg: 1300,
      mpy: 10500, ncap: [5, 2013], onSale: false, halo: false,
      g: { build: 80, drive: 70, practicality: 90, value: 88, design: 62, running: 82 },
      verdict: 'The minicab and the family holiday, both nailed. Golf mechanicals, limo legroom, estate boot like a lock-up garage.',
      issues: ['DSG service history matters', '1.5 TSI kangaroo (updated)'],
      buy: '2.0 TDI 150 SE L Estate — the million-mile family tool. vRS 245 for the fun one.',
      tags: ['tardis', 'bargain-hero', 'motorway-muncher', 'cheap-to-run', 'dog-friendly', 'bulletproof'],
      rivals: ['volkswagen-golf-mk7', 'ford-focus-mk4', 'seat-leon-5f'] },

    { model: 'Octavia', gen: 'Mk4', years: [2020, 0], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [22000, 38000], used: [13000, 30000], accel: 6.4, power: [110, 265], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 55, ev: 43, seats: 5, doors: 5, boot: 600, len: 4689, kg: 1330,
      mpy: 10500, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 82, drive: 72, practicality: 90, value: 84, design: 68, running: 82 },
      verdict: 'Still the answer to most car questions. vRS iV pays company-car tax like a saint and hauls like a sinner.',
      issues: ['Touch-heavy cabin (facelift improved)', 'Early software gremlins'],
      buy: 'Estate 1.5 TSI e-TEC SE L — or vRS TDI for the mile-eaters.',
      tags: ['tardis', 'bargain-hero', 'motorway-muncher', 'company-car-hero', 'dog-friendly', 'crowd-pleaser'],
      rivals: ['volkswagen-golf-mk8', 'toyota-corolla-e210', 'ford-focus-mk4'] },

    { model: 'Superb', gen: 'B8', years: [2015, 2024], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [24000, 42000], used: [9000, 32000], accel: 5.5, power: [125, 280], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 53, ev: 35, seats: 5, doors: 5, boot: 660, len: 4869, kg: 1505,
      mpy: 11500, ncap: [5, 2015], onSale: false, halo: false,
      g: { build: 84, drive: 70, practicality: 94, value: 90, design: 68, running: 80 },
      verdict: 'More rear legroom than a 7 Series, a boot like a studio flat, £15k used. The smartest big-car buy in Britain, full stop.',
      issues: ['DSG mechatronics at big miles', 'iV battery health check'],
      buy: 'Estate 2.0 TDI 190 SportLine — chauffeur space, taxi bills.',
      tags: ['tardis', 'bargain-hero', 'wafty', 'motorway-muncher', 'company-car-hero', 'dog-friendly'],
      rivals: ['volkswagen-passat-b8', 'ford-mondeo-mk5', 'bmw-5-series-g30'] },

    { model: 'Kamiq', gen: 'NW4', years: [2019, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [21000, 30000], used: [13000, 25000], accel: 8.3, power: [95, 150], top: 132,
      fuels: ['petrol'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 400, len: 4241, kg: 1240,
      mpy: 9000, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 80, drive: 68, practicality: 80, value: 82, design: 64, running: 84 },
      verdict: 'The sensible small crossover perfected: airy, honest, umbrella in the door. Family life’s quiet enabler.',
      issues: ['No AWD option', 'Firm-ish on 18s'],
      buy: '1.0 TSI 110 SE Drive — everything needed, nothing more.',
      tags: ['school-run', 'crowd-pleaser', 'cheap-to-run', 'bargain-hero'],
      rivals: ['volkswagen-t-roc-a11', 'ford-puma-mk1', 'kia-xceed-cd'] },

    { model: 'Karoq', gen: 'NU7', years: [2017, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [25000, 38000], used: [13000, 30000], accel: 6.9, power: [110, 190], top: 131,
      fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 521, len: 4382, kg: 1395,
      mpy: 10000, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 82, drive: 68, practicality: 86, value: 82, design: 60, running: 80 },
      verdict: 'VarioFlex seats slide, recline and leave entirely. The Yeti’s spirit in a straighter suit — family utility mastered.',
      issues: ['Yeti fans still mourn', 'Diesel choice thinning'],
      buy: '1.5 TSI SE L with VarioFlex — the clever family default.',
      tags: ['school-run', 'tardis', 'crowd-pleaser', 'dog-friendly', 'bargain-hero'],
      rivals: ['volkswagen-tiguan-ad', 'nissan-qashqai-j12', 'kia-sportage-nq5'] },

    { model: 'Kodiaq', gen: 'NS7', years: [2016, 2024], bodies: ['suv'], segment: 'seven-seater',
      priceNew: [27000, 44000], used: [14000, 36000], accel: 6.8, power: [125, 245], top: 137,
      fuels: ['petrol', 'diesel'], mpg: 47, ev: null, seats: 7, doors: 5, boot: 720, len: 4697, kg: 1610,
      mpy: 10500, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 82, drive: 70, practicality: 92, value: 86, design: 68, running: 76 },
      verdict: 'Seven seats, one sensible price, zero nonsense. The Kodiaq quietly ended the people-carrier and most premium rivals.',
      issues: ['Row three for under-12s', 'DSG shunt when cold'],
      buy: '2.0 TDI 150 SE L 7-seat — the great family all-rounder. vRS if you must smile.',
      tags: ['seven-seats', 'family-bus', 'tardis', 'bargain-hero', 'tow-car', 'dog-friendly', 'crowd-pleaser'],
      rivals: ['kia-sorento-mq4', 'hyundai-santa-fe-tm', 'peugeot-5008-p87'] },

    { model: 'Kodiaq', gen: 'NS8', years: [2024, 0], bodies: ['suv'], segment: 'seven-seater',
      priceNew: [37000, 50000], used: [30000, 45000], accel: 6.4, power: [150, 265], top: 141,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 48, ev: 62, seats: 7, doors: 5, boot: 745, len: 4758, kg: 1685,
      mpy: 10500, ncap: [5, 2024], onSale: true, halo: false,
      g: { build: 84, drive: 72, practicality: 94, value: 82, design: 70, running: 80 },
      verdict: 'Even bigger, now with a 62-mile PHEV. Smart dials return, boot grows again — the family flagship of common sense.',
      issues: ['PHEV only five seats', 'Waiting lists build'],
      buy: 'iV PHEV SE L for commuters; 2.0 TDI 7-seat for the road-trippers.',
      tags: ['seven-seats', 'family-bus', 'tardis', 'crowd-pleaser', 'tow-car'],
      rivals: ['hyundai-santa-fe-mx5', 'kia-sorento-mq4', 'nissan-x-trail-t33'] },

    { model: 'Enyaq', gen: '5AZ', years: [2021, 0], bodies: ['suv', 'coupe'], segment: 'ev-native',
      priceNew: [37000, 52000], used: [18000, 40000], accel: 5.5, power: [148, 340], top: 111,
      fuels: ['ev'], mpg: null, ev: 348, seats: 5, doors: 5, boot: 585, len: 4649, kg: 2020,
      mpy: 9500, ncap: [5, 2021], onSale: true, halo: false,
      g: { build: 82, drive: 70, practicality: 88, value: 82, design: 70, running: 84 },
      verdict: 'The ID.4 with the sensible head screwed on — bigger boot, nicer cabin, better value. The family EV to beat.',
      issues: ['Early software patchy (updated)', 'Heat pump was optional — check'],
      buy: '85 SportLine used — 330 real miles, hot-hatch shove.',
      tags: ['tardis', 'silent-cruiser', 'school-run', 'bargain-hero', 'crowd-pleaser', 'cheap-to-run'],
      rivals: ['volkswagen-id-4-id-5-e21', 'tesla-model-y-juniper', 'kia-ev6-cv'] },

    { model: 'Yeti', gen: '5L', years: [2009, 2017], bodies: ['suv'], segment: 'small-suv',
      priceNew: [15000, 26000], used: [4000, 12000], accel: 8.4, power: [105, 170], top: 124,
      fuels: ['petrol', 'diesel'], mpg: 47, ev: null, seats: 5, doors: 5, boot: 416, len: 4223, kg: 1315,
      mpy: 8500, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 78, drive: 74, practicality: 84, value: 84, design: 72, running: 78 },
      verdict: 'The boxy little genius everyone still misses. Upright, chuckable, seats out in seconds — cult classic status earned.',
      issues: ['1.2 TSI chain tensioner (early)', 'DSG history check'],
      buy: '2.0 TDI 140 SE 4x4 — the do-anything box at its best.',
      tags: ['boxy-icon', 'tardis', 'modern-classic', 'dog-friendly', 'go-anywhere', 'bargain-hero'],
      rivals: ['skoda-karoq-nu7', 'nissan-qashqai-j11', 'suzuki-vitara-ly'] },

    { model: 'Scala', gen: 'NW1', years: [2019, 0], bodies: ['hatch'], segment: 'family-hatch',
      priceNew: [19000, 27000], used: [11000, 22000], accel: 8.2, power: [95, 150], top: 134,
      fuels: ['petrol'], mpg: 53, ev: null, seats: 5, doors: 5, boot: 467, len: 4362, kg: 1180,
      mpy: 9000, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 78, drive: 66, practicality: 84, value: 86, design: 60, running: 86 },
      verdict: 'A Golf-sized car at Polo money with a near-estate boot. The best-value family hatch nobody remembers to consider.',
      issues: ['Interior plain', 'Image invisible'],
      buy: '1.0 TSI 110 SE L — the quiet bargain of the class.',
      tags: ['bargain-hero', 'tardis', 'cheap-to-run', 'first-car-friendly', 'discreet'],
      rivals: ['skoda-octavia-mk4', 'kia-ceed-cd', 'seat-leon-k1'] }
  ]
};
