// Suzuki — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Suzuki',
  cars: [
    { model: 'Jimny', gen: 'JB74', years: [2018, 2021], bodies: ['suv'], segment: 'off-roader',
      priceNew: [16000, 20000], used: [16000, 24000], accel: 12.8, power: [102, 102], top: 90,
      fuels: ['petrol'], mpg: 36, ev: null, seats: 4, doors: 3, boot: 85, len: 3480, kg: 1135,
      mpy: 6000, ncap: [3, 2018], onSale: false, halo: false,
      g: { build: 80, drive: 52, practicality: 46, value: 74, design: 94, running: 78 },
      verdict: 'A shrunken G-Wagen that climbs like a goat and sold out forever. Worth more used than new — icon economics.',
      issues: ['85-litre boot (yes, really)', 'Motorway crosswinds are an event'],
      buy: 'SZ5 manual, unmodified. It will never lose you money.',
      tags: ['boxy-icon', 'go-anywhere', 'future-classic', 'retro-charm', 'off-grid', 'head-turner', 'analogue-joy'],
      rivals: ['jeep-wrangler-jl', 'land-rover-defender-classic', 'fiat-panda-319'] },

    { model: 'Swift', gen: 'A2L', years: [2017, 2024], bodies: ['hatch'], segment: 'supermini',
      priceNew: [13000, 22000], used: [7000, 16000], accel: 8.1, power: [83, 140], top: 130,
      fuels: ['petrol', 'hybrid'], mpg: 55, ev: null, seats: 5, doors: 5, boot: 265, len: 3840, kg: 890,
      mpy: 7500, ncap: [3, 2017], onSale: false, halo: false,
      g: { build: 74, drive: 80, practicality: 60, value: 82, design: 68, running: 88 },
      verdict: 'Under 900kg of fizzy honesty — the Swift Sport is the featherweight hot hatch the industry forgot to make.',
      issues: ['Light-touch interior', 'Road noise'],
      buy: 'Swift Sport 1.4 Boosterjet — lightweight joy, sensible bills.',
      tags: ['lightweight', 'drivers-car', 'cheap-to-run', 'first-car-friendly', 'b-road-hero', 'bargain-hero'],
      rivals: ['ford-fiesta-mk8', 'mazda-2-dj', 'volkswagen-up-aa'] },

    { model: 'Vitara', gen: 'LY', years: [2015, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [17000, 27000], used: [8000, 20000], accel: 8.9, power: [111, 140], top: 118,
      fuels: ['petrol', 'hybrid'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 375, len: 4175, kg: 1160,
      mpy: 8500, ncap: [5, 2015], onSale: true, halo: false,
      g: { build: 74, drive: 68, practicality: 74, value: 82, design: 62, running: 86 },
      verdict: 'Light, honest, AllGrip-capable — the small SUV that still remembers Suzukis should be simple and tough.',
      issues: ['Interior dated', 'Boosterjet oil use — check level habitually'],
      buy: '1.4 Boosterjet AllGrip SZ5 — the mountain-road bargain.',
      tags: ['go-anywhere', 'bargain-hero', 'cheap-to-run', 'lightweight', 'discreet'],
      rivals: ['dacia-duster-hm', 'skoda-kamiq-nw4', 'seat-arona-kj7'] },

    { model: 'Ignis', gen: 'MF', years: [2017, 0], bodies: ['hatch'], segment: 'city',
      priceNew: [12000, 17000], used: [7000, 14000], accel: 11.8, power: [83, 90], top: 103,
      fuels: ['petrol', 'hybrid'], mpg: 55, ev: null, seats: 4, doors: 5, boot: 267, len: 3700, kg: 865,
      mpy: 6000, ncap: [3, 2016], onSale: true, halo: false,
      g: { build: 74, drive: 66, practicality: 64, value: 84, design: 82, running: 90 },
      verdict: 'A kei-car superhero for the UK: 865kg, SUV cosplay, optional 4x4. The most charming cheap car on sale.',
      issues: ['Thin doors, light build', 'Motorway buzz'],
      buy: 'SZ5 AllGrip — micro-adventure machine.',
      tags: ['city-darling', 'retro-charm', 'lightweight', 'go-anywhere', 'cheap-to-run', 'left-field'],
      rivals: ['fiat-panda-319', 'dacia-sandero-stepway-bji', 'toyota-aygo-x-ab70'] },

    { model: 'S-Cross', gen: 'JYB', years: [2022, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [23000, 30000], used: [14000, 24000], accel: 9.5, power: [115, 140], top: 112,
      fuels: ['petrol', 'hybrid'], mpg: 53, ev: null, seats: 5, doors: 5, boot: 430, len: 4300, kg: 1250,
      mpy: 9000, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 74, drive: 64, practicality: 76, value: 80, design: 56, running: 88 },
      verdict: 'Deeply unfashionable, quietly excellent value — light, frugal, AllGrip 4x4 available. Rational to a fault.',
      issues: ['Design by committee', 'Infotainment basic'],
      buy: 'Full Hybrid AllGrip Ultra — the anonymous overachiever.',
      tags: ['bargain-hero', 'cheap-to-run', 'discreet', 'go-anywhere'],
      rivals: ['dacia-duster-dr3', 'skoda-karoq-nu7', 'toyota-c-hr-ax10'] }
  ]
};
