// Tesla — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Tesla',
  cars: [
    { model: 'Model S', gen: 'Classic', years: [2014, 2021], bodies: ['saloon'], segment: 'ev-native',
      priceNew: [58000, 100000], used: [16000, 40000], accel: 2.5, power: [332, 795], top: 155,
      fuels: ['ev'], mpg: null, ev: 340, seats: 5, doors: 5, boot: 745, len: 4979, kg: 2100,
      mpy: 10000, ncap: [5, 2014], onSale: false, halo: false,
      g: { build: 62, drive: 74, practicality: 84, value: 78, design: 76, running: 78 },
      verdict: 'The car that made EVs desirable, now at shocking used prices. Check the battery report, then enjoy the spaceship.',
      issues: ['Build quality lottery — panel gaps, MCU failures', 'Air suspension and door handles age'],
      buy: '2019-on Long Range with battery/motor warranty remaining.',
      tags: ['tech-fest', 'depreciation-king', 'silent-cruiser', 'bargain-hero', 'tardis', 'future-classic'],
      rivals: ['porsche-taycan-y1a', 'bmw-i4-g26', 'mercedes-benz-eqe-v295'] },

    { model: 'Model 3', gen: 'Pre-facelift', years: [2019, 2023], bodies: ['saloon'], segment: 'ev-native',
      priceNew: [40000, 60000], used: [14000, 28000], accel: 3.1, power: [283, 513], top: 162,
      fuels: ['ev'], mpg: null, ev: 360, seats: 5, doors: 4, boot: 425, len: 4694, kg: 1765,
      mpy: 10500, ncap: [5, 2019], onSale: false, halo: false,
      g: { build: 68, drive: 78, practicality: 76, value: 88, design: 72, running: 90 },
      verdict: 'The EV that ate the company-car market. Supercharger access and £15k used prices make it stupidly rational.',
      issues: ['Interior rattles', 'Paint thin — check stone chips'],
      buy: 'Long Range 2021-on with heat pump; battery report always.',
      tags: ['tech-fest', 'cheap-to-run', 'bargain-hero', 'silent-cruiser', 'company-car-hero', 'minimalist'],
      rivals: ['polestar-2-p2', 'hyundai-ioniq-6-ce', 'bmw-i4-g26'] },

    { model: 'Model 3', gen: 'Highland', years: [2023, 0], bodies: ['saloon'], segment: 'ev-native',
      priceNew: [40000, 60000], used: [25000, 45000], accel: 2.9, power: [283, 618], top: 163,
      fuels: ['ev'], mpg: null, ev: 390, seats: 5, doors: 4, boot: 425, len: 4720, kg: 1765,
      mpy: 10500, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 78, drive: 80, practicality: 76, value: 86, design: 76, running: 90 },
      verdict: 'Highland fixed the ride, the noise and the cabin. Indicator stalks died for it. The rational EV benchmark, refined.',
      issues: ['Stalkless indicators infuriate', 'No rear wiper still'],
      buy: 'Long Range RWD — 390 miles, sweet ride, sane money.',
      tags: ['tech-fest', 'cheap-to-run', 'silent-cruiser', 'company-car-hero', 'minimalist', 'crowd-pleaser'],
      rivals: ['hyundai-ioniq-6-ce', 'polestar-2-p2', 'bmw-i4-g26'] },

    { model: 'Model Y', gen: 'Juniper', years: [2025, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [45000, 60000], used: [35000, 52000], accel: 3.5, power: [299, 460], top: 155,
      fuels: ['ev'], mpg: null, ev: 387, seats: 5, doors: 5, boot: 854, len: 4790, kg: 1920,
      mpy: 10500, ncap: [5, 2025], onSale: true, halo: false,
      g: { build: 80, drive: 76, practicality: 90, value: 82, design: 74, running: 90 },
      verdict: 'The world’s best-seller, properly sorted: quieter, comfier, still the practicality king with the charging network.',
      issues: ['Ubiquity — you will not stand out', 'Brand politics now part of ownership'],
      buy: 'Long Range RWD — the family default, refreshed.',
      tags: ['tardis', 'tech-fest', 'cheap-to-run', 'school-run', 'silent-cruiser', 'crowd-pleaser'],
      rivals: ['skoda-enyaq-5az', 'kia-ev6-cv', 'hyundai-ioniq-5-ne'] },

    { model: 'Model Y', gen: 'Classic', years: [2021, 2025], bodies: ['suv'], segment: 'ev-native',
      priceNew: [45000, 65000], used: [20000, 35000], accel: 3.5, power: [299, 534], top: 155,
      fuels: ['ev'], mpg: null, ev: 331, seats: 5, doors: 5, boot: 854, len: 4750, kg: 1930,
      mpy: 10500, ncap: [5, 2022], onSale: false, halo: false,
      g: { build: 70, drive: 68, practicality: 90, value: 84, design: 68, running: 90 },
      verdict: 'Firm-riding, big-booted, everywhere. The used ones are now cheap enough to forgive the jiggle entirely.',
      issues: ['Ride crashy on 20s', 'Road noise'],
      buy: 'Long Range AWD 2022-on used — peak space per pound in EVs.',
      tags: ['tardis', 'cheap-to-run', 'school-run', 'depreciation-king', 'crowd-pleaser'],
      rivals: ['skoda-enyaq-5az', 'volkswagen-id-4-id-5-e21', 'ford-mustang-mach-e-cx727'] },

    { model: 'Model S', gen: 'Refresh', years: [2021, 0], bodies: ['saloon'], segment: 'ev-native',
      priceNew: [90000, 130000], used: [55000, 90000], accel: 2.1, power: [670, 1020], top: 200,
      fuels: ['ev'], mpg: null, ev: 394, seats: 5, doors: 5, boot: 745, len: 5021, kg: 2170,
      mpy: 9000, ncap: null, onSale: true, halo: false,
      g: { build: 74, drive: 80, practicality: 84, value: 68, design: 74, running: 84 },
      verdict: 'Plaid: 1,020bhp, faster than physics should allow, yoke optional. The family saloon that humbles hypercars.',
      issues: ['Yoke steering an acquired taste', 'UK cars are LHD-only-era leftovers — check spec'],
      buy: 'Long Range with the round wheel retrofit.',
      tags: ['autobahn-stormer', 'tech-fest', 'silent-cruiser', 'left-field', 'head-turner'],
      rivals: ['porsche-taycan-y1a', 'audi-e-tron-gt-f83', 'bmw-i7-g70'] },

    { model: 'Model X', gen: 'Refresh', years: [2021, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [100000, 130000], used: [60000, 95000], accel: 2.6, power: [670, 1020], top: 163,
      fuels: ['ev'], mpg: null, ev: 348, seats: 7, doors: 5, boot: 800, len: 5057, kg: 2455,
      mpy: 9000, ncap: null, onSale: true, halo: false,
      g: { build: 70, drive: 72, practicality: 88, value: 62, design: 74, running: 82 },
      verdict: 'Falcon doors still stop pavements. Seven seats, silly speed, theatrical everything — reliability interesting.',
      issues: ['Falcon doors: complexity tax', 'Size on UK roads'],
      buy: 'Long Range 6-seat if the doors have behaved (get history).',
      tags: ['tech-fest', 'head-turner', 'seven-seats', 'family-bus', 'left-field'],
      rivals: ['bmw-ix-i20', 'volvo-ex90-p3', 'mercedes-benz-eqs-suv-x296'] }
  ]
};
