// Toyota — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Toyota',
  cars: [
    { model: 'Aygo', gen: 'AB40', years: [2014, 2021], bodies: ['hatch'], segment: 'city',
      priceNew: [9000, 14000], used: [4500, 10000], accel: 13.8, power: [69, 72], top: 99,
      fuels: ['petrol'], mpg: 56, ev: null, seats: 4, doors: 5, boot: 168, len: 3455, kg: 840,
      mpy: 6000, ncap: [4, 2014], onSale: false, halo: false,
      g: { build: 74, drive: 62, practicality: 46, value: 84, design: 66, running: 94 },
      verdict: 'X-faced city runabout that costs pennies and simply never breaks. First-car royalty, insurance-group hero.',
      issues: ['Tiny boot', 'Motorway hum'],
      buy: 'x-play with the reversing camera; any year, they all just work.',
      tags: ['city-darling', 'first-car-friendly', 'cheap-to-run', 'bulletproof', 'bargain-hero'],
      rivals: ['volkswagen-up-aa', 'hyundai-i10-ac3', 'kia-picanto-ja'] },

    { model: 'Aygo X', gen: 'AB70', years: [2022, 0], bodies: ['hatch'], segment: 'city',
      priceNew: [16000, 20000], used: [10000, 17000], accel: 14.9, power: [72, 72], top: 94,
      fuels: ['petrol'], mpg: 58, ev: null, seats: 4, doors: 5, boot: 231, len: 3700, kg: 940,
      mpy: 6000, ncap: [4, 2022], onSale: true, halo: false,
      g: { build: 78, drive: 60, practicality: 52, value: 74, design: 74, running: 92 },
      verdict: 'A city car in crossover fancy dress. Slow as a canal boat, cheap as chips to run, weirdly charming with it.',
      issues: ['Glacial overtaking', 'Rear seats snug'],
      buy: 'Edge trim, canvas roof, funky colour — lean into it.',
      tags: ['city-darling', 'cheap-to-run', 'first-car-friendly', 'crowd-pleaser'],
      rivals: ['hyundai-i10-ac3', 'kia-picanto-ja', 'fiat-panda-319'] },

    { model: 'Yaris', gen: 'XP210', years: [2020, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [20000, 28000], used: [12000, 24000], accel: 9.7, power: [116, 130], top: 109,
      fuels: ['hybrid'], mpg: 65, ev: null, seats: 5, doors: 5, boot: 286, len: 3940, kg: 1085,
      mpy: 8000, ncap: [5, 2020], onSale: true, halo: false,
      g: { build: 82, drive: 72, practicality: 60, value: 78, design: 70, running: 94 },
      verdict: '70mpg in town without plugging anything in. The hybrid supermini perfected — and the reliability is legend.',
      issues: ['Tight rear seat', 'Boot merely adequate'],
      buy: 'Design grade hybrid 115 — everything you need, nothing you don’t.',
      tags: ['cheap-to-run', 'bulletproof', 'city-darling', 'crowd-pleaser', 'first-car-friendly'],
      rivals: ['renault-clio-v', 'honda-jazz-ge4', 'volkswagen-polo-mk6'] },

    { model: 'GR Yaris', gen: 'XP210', years: [2020, 0], bodies: ['hatch'], segment: 'hot-hatch',
      priceNew: [30000, 46000], used: [24000, 42000], accel: 5.2, power: [261, 280], top: 143,
      fuels: ['petrol'], mpg: 34, ev: null, seats: 4, doors: 3, boot: 174, len: 3995, kg: 1280,
      mpy: 6000, ncap: [5, 2020], onSale: true, halo: false,
      g: { build: 84, drive: 95, practicality: 44, value: 78, design: 78, running: 60 },
      verdict: 'A homologation special in a world that stopped making them. Rally-bred, riotous, already collectible. Just buy it.',
      issues: ['Rear seats vestigial', 'Good ones get tracked — check history'],
      buy: 'Circuit Pack manual, standard, stamps intact. Keep forever.',
      tags: ['future-classic', 'pocket-rocket', 'drivers-car', 'b-road-hero', 'track-day', 'analogue-joy', 'go-anywhere'],
      rivals: ['honda-civic-type-r-fl5', 'hyundai-i20-n-bc3', 'volkswagen-golf-r-mk8'] },

    { model: 'Corolla', gen: 'E210', years: [2019, 0], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [25000, 35000], used: [13000, 30000], accel: 7.5, power: [122, 196], top: 112,
      fuels: ['hybrid'], mpg: 60, ev: null, seats: 5, doors: 5, boot: 361, len: 4370, kg: 1370,
      mpy: 9500, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 84, drive: 74, practicality: 74, value: 80, design: 72, running: 92 },
      verdict: 'The sensible decision that no longer feels like one — sharp looks, 60mpg, ten-year warranty potential. Adult excellence.',
      issues: ['CVT drone when rushed', 'Touring boot beats the hatch — choose wisely'],
      buy: 'Touring Sports 2.0 Design — the estate that ends arguments.',
      tags: ['bulletproof', 'cheap-to-run', 'crowd-pleaser', 'motorway-muncher', 'dog-friendly'],
      rivals: ['volkswagen-golf-mk8', 'honda-civic-fl1', 'mazda-3-bp'] },

    { model: 'Prius', gen: 'XW30', years: [2009, 2015], bodies: ['hatch'], segment: 'family-hatch',
      priceNew: [21000, 28000], used: [5000, 11000], accel: 10.4, power: [136, 136], top: 112,
      fuels: ['hybrid'], mpg: 60, ev: null, seats: 5, doors: 5, boot: 445, len: 4460, kg: 1380,
      mpy: 12000, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 80, drive: 56, practicality: 76, value: 82, design: 56, running: 92 },
      verdict: 'The 300,000-mile taxi legend. Zero glamour, total dependability, hybrid running costs before it was cool.',
      issues: ['Check hybrid battery health (cheap to refurb)', 'Uber history common'],
      buy: 'Private-owner T-Spirit with low miles — they exist, hunt one.',
      tags: ['bulletproof', 'cheap-to-run', 'bargain-hero', 'discreet'],
      rivals: ['toyota-corolla-e210', 'honda-insight-ze2', 'hyundai-ioniq-ae'] },

    { model: 'C-HR', gen: 'AX10', years: [2016, 2023], bodies: ['suv'], segment: 'small-suv',
      priceNew: [23000, 33000], used: [12000, 26000], accel: 8.2, power: [122, 184], top: 112,
      fuels: ['hybrid'], mpg: 57, ev: null, seats: 5, doors: 5, boot: 377, len: 4360, kg: 1460,
      mpy: 9000, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 82, drive: 70, practicality: 64, value: 76, design: 78, running: 90 },
      verdict: 'Concept-car looks that made hybrid cool-ish. Dark back seats, bright ownership — nothing this striking is this easy.',
      issues: ['Rear visibility', 'Back seat feels like a cave'],
      buy: '2.0 Hybrid Design, 2020-on, for the extra shove.',
      tags: ['head-turner', 'cheap-to-run', 'bulletproof', 'city-darling', 'crowd-pleaser'],
      rivals: ['nissan-juke-f16', 'honda-hr-v-ru', 'mazda-cx-30-dm'] },

    { model: 'RAV4', gen: 'XA50', years: [2019, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [32000, 48000], used: [20000, 40000], accel: 6.0, power: [218, 306], top: 112,
      fuels: ['hybrid', 'phev'], mpg: 50, ev: 46, seats: 5, doors: 5, boot: 580, len: 4600, kg: 1650,
      mpy: 10500, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 84, drive: 70, practicality: 86, value: 80, design: 72, running: 86 },
      verdict: 'The family SUV as a Swiss watch: 50mpg self-charging or a 46-mile-EV plug-in, and it will simply never let you down.',
      issues: ['Catalytic-converter theft on early cars (guards available)', 'Road noise on 19s'],
      buy: 'PHEV Dynamic — hot-hatch pace, milk-float bills.',
      tags: ['bulletproof', 'school-run', 'tow-car', 'cheap-to-run', 'adventure-ready', 'crowd-pleaser'],
      rivals: ['honda-cr-v-rw', 'hyundai-tucson-nx4', 'ford-kuga-mk3'] },

    { model: 'Highlander', gen: 'XU70', years: [2021, 2024], bodies: ['suv'], segment: 'seven-seater',
      priceNew: [50000, 58000], used: [32000, 48000], accel: 8.3, power: [248, 248], top: 111,
      fuels: ['hybrid'], mpg: 43, ev: null, seats: 7, doors: 5, boot: 658, len: 4950, kg: 2015,
      mpy: 10500, ncap: [5, 2021], onSale: false, halo: false,
      g: { build: 84, drive: 64, practicality: 90, value: 72, design: 62, running: 80 },
      verdict: 'Seven seats, 43mpg, Toyota dependability — the XC90 alternative nobody thought to consider. America’s default, our secret.',
      issues: ['Third row tighter than a Kodiaq', 'Rare — little choice used'],
      buy: 'Excel grade with tow pack — the family lugger perfected.',
      tags: ['seven-seats', 'family-bus', 'bulletproof', 'cheap-to-run', 'left-field'],
      rivals: ['kia-sorento-mq4', 'hyundai-santa-fe-tm', 'skoda-kodiaq-ns7'] },

    { model: 'Land Cruiser', gen: 'J150', years: [2009, 2023], bodies: ['suv'], segment: 'off-roader',
      priceNew: [38000, 60000], used: [20000, 55000], accel: 9.9, power: [173, 204], top: 109,
      fuels: ['diesel'], mpg: 32, ev: null, seats: 7, doors: 5, boot: 620, len: 4840, kg: 2455,
      mpy: 9000, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 94, drive: 56, practicality: 86, value: 76, design: 62, running: 56 },
      verdict: 'The UN’s favourite vehicle for a reason: it cannot be killed. Agricultural on tarmac, immortal off it. 400k miles is midlife.',
      issues: ['DPF wants motorway runs', 'Utility trims spartan'],
      buy: 'Invincible 2.8 D-4D, 7 seats — buy once, keep for decades.',
      tags: ['bulletproof', 'go-anywhere', 'off-grid', 'chunky-4x4', 'seven-seats', 'tow-car', 'adventure-ready'],
      rivals: ['land-rover-discovery-l462', 'mitsubishi-shogun-v80', 'ford-ranger-t6-2'] },

    { model: 'Land Cruiser', gen: 'J250', years: [2024, 0], bodies: ['suv'], segment: 'off-roader',
      priceNew: [75000, 87000], used: [60000, 80000], accel: 10.9, power: [204, 204], top: 103,
      fuels: ['diesel'], mpg: 33, ev: null, seats: 7, doors: 5, boot: 566, len: 4925, kg: 2520,
      mpy: 9000, ncap: [5, 2024], onSale: true, halo: false,
      g: { build: 92, drive: 60, practicality: 86, value: 60, design: 86, running: 52 },
      verdict: 'Retro-boxy reboot with the immortal bones intact. Suddenly the Land Cruiser is a style object — prices noticed.',
      issues: ['UK allocation tiny', 'Price crept into Defender country'],
      buy: 'Invincible in beige. Yes, beige. Trust the process.',
      tags: ['boxy-icon', 'go-anywhere', 'bulletproof', 'head-turner', 'off-grid', 'chunky-4x4', 'future-classic'],
      rivals: ['land-rover-defender-l663', 'ineos-grenadier-b52', 'mercedes-benz-g-class-w463a'] },

    { model: 'Hilux', gen: 'AN120', years: [2016, 0], bodies: ['pickup'], segment: 'pickup',
      priceNew: [28000, 45000], used: [16000, 38000], accel: 10.7, power: [150, 204], top: 109,
      fuels: ['diesel'], mpg: 33, ev: null, seats: 5, doors: 4, boot: 1100, len: 5325, kg: 2110,
      mpy: 13000, ncap: [5, 2016], onSale: true, halo: false,
      g: { build: 92, drive: 56, practicality: 84, value: 76, design: 64, running: 58 },
      verdict: 'Top Gear tried to kill one and failed. The indestructible workhorse — farm tool first, lifestyle accessory second.',
      issues: ['Leaf-sprung ride unladen', 'Tax maths changed for private use'],
      buy: 'Invincible X double cab 2.8 — the forever truck.',
      tags: ['bulletproof', 'go-anywhere', 'tow-car', 'chunky-4x4', 'adventure-ready', 'off-grid'],
      rivals: ['ford-ranger-t6-2', 'isuzu-d-max-rg', 'volkswagen-amarok-nf'] },

    { model: 'GT86', gen: 'ZN6', years: [2012, 2021], bodies: ['coupe'], segment: 'sports',
      priceNew: [25000, 30000], used: [11000, 22000], accel: 7.6, power: [200, 200], top: 140,
      fuels: ['petrol'], mpg: 36, ev: null, seats: 4, doors: 2, boot: 237, len: 4240, kg: 1275,
      mpy: 6000, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 80, drive: 90, practicality: 48, value: 82, design: 74, running: 66 },
      verdict: 'Slow-car-fast perfection: skinny tyres, rear drive, telepathic balance. The purist’s bargain — learn car control here.',
      issues: ['Valve-spring recall — confirm done', 'Cabin plastics from 2005'],
      buy: 'Manual, standard, post-recall. Fit good tyres only when ready.',
      tags: ['drivers-car', 'analogue-joy', 'b-road-hero', 'future-classic', 'lightweight', 'first-car-friendly', 'rev-happy'],
      rivals: ['mazda-mx-5-nd', 'subaru-brz-zc6', 'ford-fiesta-mk8'] },

    { model: 'GR86', gen: 'ZN8', years: [2022, 2024], bodies: ['coupe'], segment: 'sports',
      priceNew: [30000, 32000], used: [27000, 34000], accel: 6.3, power: [234, 234], top: 140,
      fuels: ['petrol'], mpg: 32, ev: null, seats: 4, doors: 2, boot: 226, len: 4265, kg: 1275,
      mpy: 6000, ncap: null, onSale: false, halo: false,
      g: { build: 82, drive: 93, practicality: 46, value: 80, design: 76, running: 62 },
      verdict: 'The GT86 with the torque it always begged for. Two-year UK run, sold out instantly — a guaranteed future classic.',
      issues: ['Values holding above list', 'Two years of supply only'],
      buy: 'Any manual you can find at sane money. It will not depreciate.',
      tags: ['drivers-car', 'future-classic', 'analogue-joy', 'b-road-hero', 'lightweight', 'rev-happy'],
      rivals: ['mazda-mx-5-nd', 'toyota-gr-yaris-xp210', 'bmw-2-series-coupe-g42'] },

    { model: 'GR Supra', gen: 'A90', years: [2019, 0], bodies: ['coupe'], segment: 'sports',
      priceNew: [46000, 57000], used: [28000, 48000], accel: 4.1, power: [258, 340], top: 155,
      fuels: ['petrol'], mpg: 34, ev: null, seats: 2, doors: 2, boot: 290, len: 4379, kg: 1495,
      mpy: 6000, ncap: null, onSale: true, halo: false,
      g: { build: 84, drive: 86, practicality: 42, value: 76, design: 82, running: 56 },
      verdict: 'A Z4 in Toyota drag, and better for it. B58 straight-six muscle, GT usability, manual option — the legend wears it well.',
      issues: ['BMW servicing costs', 'Blind spots like postboxes'],
      buy: '3.0 Pro manual — the collector spec already.',
      tags: ['drivers-car', 'grand-tourer', 'head-turner', 'future-classic', 'sleek'],
      rivals: ['bmw-z4-g29', 'porsche-718-cayman-982', 'nissan-z-rz34'] },

    { model: 'bZ4X', gen: 'EA10', years: [2022, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [42000, 52000], used: [20000, 38000], accel: 6.9, power: [204, 218], top: 100,
      fuels: ['ev'], mpg: null, ev: 318, seats: 5, doors: 5, boot: 452, len: 4690, kg: 2005,
      mpy: 9000, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 82, drive: 64, practicality: 80, value: 72, design: 66, running: 84 },
      verdict: 'Toyota’s cautious first EV — wobbly launch, quietly fixed. Not exciting, but the ownership will be effortless.',
      issues: ['Early wheel-bolt recall (done)', 'Charging speed mid-pack'],
      buy: 'Motion grade used after the big depreciation bite.',
      tags: ['silent-cruiser', 'bulletproof', 'school-run', 'depreciation-king'],
      rivals: ['volkswagen-id-4-id-5-e21', 'nissan-ariya-fe0', 'hyundai-ioniq-5-ne'] },

    { model: 'Camry', gen: 'XV70', years: [2019, 2024], bodies: ['saloon'], segment: 'exec',
      priceNew: [30000, 38000], used: [17000, 30000], accel: 8.3, power: [218, 218], top: 112,
      fuels: ['hybrid'], mpg: 53, ev: null, seats: 5, doors: 4, boot: 524, len: 4885, kg: 1595,
      mpy: 11000, ncap: [5, 2019], onSale: false, halo: false,
      g: { build: 86, drive: 62, practicality: 80, value: 80, design: 60, running: 88 },
      verdict: 'The world’s default saloon, briefly back in Britain. Utterly dependable, deeply comfortable, invisible to everyone.',
      issues: ['Anonymity terminal', 'CVT drone at full throttle'],
      buy: 'Excel — minicab spec is the correct spec.',
      tags: ['bulletproof', 'cheap-to-run', 'motorway-muncher', 'discreet', 'left-field', 'wafty'],
      rivals: ['lexus-es-xz10', 'skoda-superb-b8', 'volkswagen-passat-b8'] }
  ]
};
