// Toyota — older and extra model-generations, UK market. Curated for Vroom.
export default {
  make: 'Toyota',
  cars: [
    { model: 'Aygo', gen: 'AB10', years: [2005, 2014], bodies: ['hatch'], segment: 'city',
      priceNew: [7500, 11000], used: [1200, 5000], accel: 14.2, power: [54, 68], top: 98, fuels: ['petrol', 'diesel'], mpg: 59, ev: null,
      seats: 4, doors: 5, boot: 139, len: 3410, kg: 805, mpy: 5500, ncap: [4, 2005], onSale: false, halo: false,
      g: { build: 70, drive: 58, practicality: 42, value: 91, design: 62, running: 96 },
      verdict: 'The original joint-venture city bug: crude, cheerful and almost impossible to financially regret. It runs on fumes.',
      issues: ['Clutches wear in town', 'Water can enter the rear lamps'], buy: 'Facelift 1.0 manual with dry carpets and a recent clutch.',
      tags: ['city-darling', 'first-car-friendly', 'cheap-to-run', 'bulletproof', 'bargain-hero'], rivals: ['citroen-c1-mk1', 'peugeot-107-t1', 'volkswagen-up-aa'] },

    { model: 'iQ', gen: 'AJ10', years: [2009, 2015], bodies: ['hatch'], segment: 'city',
      priceNew: [10000, 16000], used: [3000, 8500], accel: 11.6, power: [68, 97], top: 106, fuels: ['petrol'], mpg: 58, ev: null,
      seats: 4, doors: 3, boot: 32, len: 2985, kg: 860, mpy: 5000, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 82, drive: 64, practicality: 45, value: 76, design: 86, running: 92 },
      verdict: 'A three-metre packaging masterclass with four seatbelts and proper big-car engineering. Tiny outside, unexpectedly grown-up within.',
      issues: ['Boot vanishes with rear seats up', 'Rear tyres are an uncommon size'], buy: '1.33 manual in iQ3 trim; avoid the slow CVT unless city-only.',
      tags: ['city-darling', 'tardis', 'left-field', 'future-classic', 'cheap-to-run'], rivals: ['smart-fortwo-w451', 'fiat-500-312', 'volkswagen-up-aa'] },

    { model: 'Yaris', gen: 'XP90', years: [2006, 2011], bodies: ['hatch'], segment: 'supermini',
      priceNew: [9000, 16000], used: [1500, 5500], accel: 10.7, power: [69, 132], top: 121, fuels: ['petrol', 'diesel'], mpg: 52, ev: null,
      seats: 5, doors: 5, boot: 272, len: 3750, kg: 980, mpy: 6500, ncap: [5, 2005], onSale: false, halo: false,
      g: { build: 79, drive: 57, practicality: 73, value: 89, design: 52, running: 92 },
      verdict: 'A washing machine with number plates, meant affectionately: roomy, simple and still starting after everybody else gives up.',
      issues: ['M-MT automated manual is best avoided', 'Cabin plastics scratch easily'], buy: '1.3 TR manual with evidence of basic annual servicing.',
      tags: ['bulletproof', 'bargain-hero', 'cheap-to-run', 'first-car-friendly', 'tardis'], rivals: ['honda-jazz-gd', 'ford-fiesta-mk6', 'nissan-micra-k12'] },

    { model: 'Yaris', gen: 'XP130', years: [2011, 2020], bodies: ['hatch'], segment: 'supermini',
      priceNew: [12000, 20000], used: [3500, 12000], accel: 11.8, power: [69, 114], top: 109, fuels: ['petrol', 'diesel', 'hybrid'], mpg: 62, ev: null,
      seats: 5, doors: 5, boot: 286, len: 3950, kg: 1055, mpy: 7000, ncap: [5, 2011], onSale: false, halo: false,
      g: { build: 81, drive: 59, practicality: 69, value: 86, design: 58, running: 95 },
      verdict: 'The hybrid minicab in supermini form. Charisma is rationed, but fuel, tax and repair bills barely trouble the diary.',
      issues: ['Hybrid battery fan needs cleaning', 'Road noise at motorway speed'], buy: '2017-on 1.5 Hybrid Icon with a clean battery-health check.',
      tags: ['bulletproof', 'cheap-to-run', 'city-darling', 'first-car-friendly', 'bargain-hero'], rivals: ['honda-jazz-gk', 'ford-fiesta-mk7', 'renault-clio-iv'] },

    { model: 'Starlet', gen: 'P90', years: [1996, 1999], bodies: ['hatch'], segment: 'supermini',
      priceNew: [8500, 11000], used: [1200, 5500], accel: 10.3, power: [74, 74], top: 106, fuels: ['petrol'], mpg: 43, ev: null,
      seats: 5, doors: 5, boot: 214, len: 3740, kg: 865, mpy: 4500, ncap: [3, 1998], onSale: false, halo: false,
      g: { build: 78, drive: 61, practicality: 60, value: 84, design: 48, running: 90 },
      verdict: 'Nineties Toyota at its purest: featherweight, unpretentious and absurdly durable. Survivors now have accidental retro charm.',
      issues: ['Rust around sills and arches', 'Safety belongs to another era'], buy: 'Standard 1.3 manual with solid metal; condition beats mileage.',
      tags: ['retro-charm', 'bulletproof', 'lightweight', 'first-car-friendly', 'cheap-to-run'], rivals: ['nissan-micra-k11', 'mazda-mazda2-dy', 'honda-jazz-gd'] },

    { model: 'Corolla', gen: 'E120', years: [2002, 2007], bodies: ['hatch', 'saloon', 'estate'], segment: 'family-hatch',
      priceNew: [11000, 20000], used: [1200, 5500], accel: 8.4, power: [89, 189], top: 140, fuels: ['petrol', 'diesel'], mpg: 45, ev: null,
      seats: 5, doors: 5, boot: 289, len: 4180, kg: 1165, mpy: 7500, ncap: [4, 2002], onSale: false, halo: false,
      g: { build: 82, drive: 60, practicality: 75, value: 91, design: 47, running: 91 },
      verdict: 'The anonymous Corolla that quietly outlived its rivals. T Sport adds a frantic 8,200rpm punch beneath the beige cardigan.',
      issues: ['Rear subframes can corrode', '1.8 oil consumption on neglected cars'], buy: '1.6 VVT-i manual for sense; T Sport only with thick history.',
      tags: ['bulletproof', 'bargain-hero', 'cheap-to-run', 'discreet', 'rev-happy'], rivals: ['honda-civic-ep', 'ford-focus-mk1', 'volkswagen-golf-mk4'] },

    { model: 'Corolla', gen: 'E150', years: [2007, 2013], bodies: ['saloon'], segment: 'family-hatch',
      priceNew: [14000, 20000], used: [2200, 7500], accel: 10.4, power: [97, 132], top: 124, fuels: ['petrol', 'diesel'], mpg: 48, ev: null,
      seats: 5, doors: 4, boot: 450, len: 4540, kg: 1270, mpy: 8500, ncap: [5, 2007], onSale: false, halo: false,
      g: { build: 83, drive: 56, practicality: 76, value: 86, design: 49, running: 89 },
      verdict: 'A rare UK saloon shaped entirely by the brief: start every morning, swallow luggage, attract absolutely no attention.',
      issues: ['Diesel DPF dislikes short trips', 'MMT transmission can be troublesome'], buy: '1.6 petrol manual, privately owned, with clean MOT history.',
      tags: ['bulletproof', 'discreet', 'bargain-hero', 'motorway-muncher'], rivals: ['honda-civic-fn2', 'skoda-octavia-mk2', 'mazda-mazda3-bl'] },

    { model: 'Auris', gen: 'E150', years: [2007, 2012], bodies: ['hatch'], segment: 'family-hatch',
      priceNew: [12000, 22000], used: [1800, 7000], accel: 10.4, power: [89, 177], top: 130, fuels: ['petrol', 'diesel', 'hybrid'], mpg: 59, ev: null,
      seats: 5, doors: 5, boot: 354, len: 4220, kg: 1320, mpy: 8000, ncap: [5, 2006], onSale: false, halo: false,
      g: { build: 79, drive: 52, practicality: 72, value: 88, design: 43, running: 91 },
      verdict: 'Toyota replaced Corolla certainty with a strange name and a tall dashboard. Still dependable, deeply dull, wonderfully cheap.',
      issues: ['Electric parking brake faults', 'Diesel head-gasket concerns'], buy: '1.8 Hybrid T Spirit; reject patchy taxi-history examples.',
      tags: ['bulletproof', 'cheap-to-run', 'bargain-hero', 'discreet'], rivals: ['honda-civic-fn2', 'ford-focus-mk2', 'volkswagen-golf-mk6'] },

    { model: 'Auris', gen: 'E180', years: [2012, 2019], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [15000, 26000], used: [4500, 13000], accel: 10.9, power: [90, 136], top: 118, fuels: ['petrol', 'diesel', 'hybrid'], mpg: 66, ev: null,
      seats: 5, doors: 5, boot: 360, len: 4330, kg: 1310, mpy: 8500, ncap: [5, 2013], onSale: false, halo: false,
      g: { build: 82, drive: 58, practicality: 77, value: 86, design: 60, running: 94 },
      verdict: 'The Corolla Touring Sports before the badge returned. Hybrid estate form is a near-indestructible, 60mpg dog carrier.',
      issues: ['CVT drones when hurried', 'Cabin ambience resolutely grey'], buy: 'Touring Sports 1.8 Hybrid Excel, preferably non-taxi.',
      tags: ['bulletproof', 'cheap-to-run', 'dog-friendly', 'bargain-hero', 'motorway-muncher'], rivals: ['honda-civic-fk2', 'skoda-octavia-mk3', 'ford-focus-mk3'] },

    { model: 'Avensis', gen: 'T250', years: [2003, 2009], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [15000, 25000], used: [1000, 5000], accel: 9.1, power: [109, 175], top: 137, fuels: ['petrol', 'diesel'], mpg: 44, ev: null,
      seats: 5, doors: 4, boot: 520, len: 4630, kg: 1370, mpy: 9000, ncap: [5, 2003], onSale: false, halo: false,
      g: { build: 82, drive: 53, practicality: 82, value: 91, design: 45, running: 84 },
      verdict: 'A British-built fleet saloon engineered to make drama impossible. Estate versions are vast; petrol versions may be immortal.',
      issues: ['2.2 diesel head-gasket failures', 'Rear brake calipers can seize'], buy: '1.8 petrol estate manual; boring specification is a virtue.',
      tags: ['bulletproof', 'bargain-hero', 'dog-friendly', 'motorway-muncher', 'discreet'], rivals: ['honda-accord-cl', 'ford-mondeo-mk3', 'mazda-mazda6-gg'] },

    { model: 'Avensis', gen: 'T270', years: [2009, 2018], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [18000, 30000], used: [3000, 11000], accel: 9.4, power: [124, 177], top: 130, fuels: ['petrol', 'diesel'], mpg: 53, ev: null,
      seats: 5, doors: 4, boot: 543, len: 4780, kg: 1505, mpy: 10000, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 84, drive: 56, practicality: 84, value: 88, design: 50, running: 83 },
      verdict: 'The final Avensis: magnificently unmemorable transport with a huge estate boot and the emotional range of office carpet.',
      issues: ['Diesel DPF and EGR need long runs', 'Electronic parking-brake niggles'], buy: 'Facelift 1.8 Valvematic Tourer manual for low-drama miles.',
      tags: ['motorway-muncher', 'dog-friendly', 'bargain-hero', 'discreet', 'bulletproof'], rivals: ['honda-accord-cu', 'ford-mondeo-mk4', 'mazda-mazda6-gh'] },

    { model: 'Corolla Verso', gen: 'AR10', years: [2004, 2009], bodies: ['mpv'], segment: 'seven-seater',
      priceNew: [15000, 23000], used: [1500, 6000], accel: 10.8, power: [127, 175], top: 128, fuels: ['petrol', 'diesel'], mpg: 43, ev: null,
      seats: 7, doors: 5, boot: 63, len: 4360, kg: 1450, mpy: 7500, ncap: [5, 2004], onSale: false, halo: false,
      g: { build: 80, drive: 51, practicality: 86, value: 89, design: 44, running: 82 },
      verdict: 'Seven seats folded into a Corolla footprint, complete with Toyota durability. Glamour-free family logistics at shed money.',
      issues: ['Boot tiny with all seven seats raised', '2.2 diesel can suffer head-gasket failure'], buy: '1.8 petrol T Spirit with clean folding-seat mechanisms.',
      tags: ['seven-seats', 'family-bus', 'tardis', 'bargain-hero', 'bulletproof'], rivals: ['honda-fr-v-be', 'ford-c-max-mk1', 'vauxhall-zafira-b'] },

    { model: 'Verso', gen: 'AR20', years: [2009, 2018], bodies: ['mpv'], segment: 'seven-seater',
      priceNew: [17000, 27000], used: [3000, 11000], accel: 11.7, power: [112, 147], top: 118, fuels: ['petrol', 'diesel'], mpg: 47, ev: null,
      seats: 7, doors: 5, boot: 155, len: 4460, kg: 1505, mpy: 8000, ncap: [5, 2010], onSale: false, halo: false,
      g: { build: 82, drive: 52, practicality: 88, value: 87, design: 48, running: 84 },
      verdict: 'An honest seven-seat appliance from the last great MPV age. Seats disappear neatly; reliability anxieties disappear entirely.',
      issues: ['Third row suits children', 'BMW-sourced 1.6 diesel adds complexity'], buy: '1.8 Valvematic Icon petrol; simplicity wins the long game.',
      tags: ['seven-seats', 'family-bus', 'tardis', 'bulletproof', 'bargain-hero'], rivals: ['ford-grand-c-max-mk2', 'vauxhall-zafira-c', 'citroen-grand-c4-picasso-mk2'] },

    { model: 'Prius', gen: 'XW20', years: [2004, 2009], bodies: ['hatch'], segment: 'family-hatch',
      priceNew: [18000, 21000], used: [1500, 6000], accel: 10.9, power: [110, 110], top: 106, fuels: ['hybrid'], mpg: 65, ev: null,
      seats: 5, doors: 5, boot: 408, len: 4450, kg: 1325, mpy: 10000, ncap: [5, 2004], onSale: false, halo: false,
      g: { build: 83, drive: 48, practicality: 77, value: 90, design: 58, running: 95 },
      verdict: 'The hybrid that became a verb, a taxi and a Hollywood accessory. Awkward to drive, eerily hard to kill.',
      issues: ['Traction batteries are now elderly', 'Catalytic-converter theft risk'], buy: 'Late T Spirit with battery report and converter shield.',
      tags: ['bulletproof', 'cheap-to-run', 'bargain-hero', 'future-classic', 'discreet'], rivals: ['honda-insight-ze2', 'lexus-ct-zwa10', 'toyota-auris-e150'] },

    { model: 'Prius', gen: 'XW50', years: [2016, 2022], bodies: ['hatch'], segment: 'family-hatch',
      priceNew: [24000, 34000], used: [10000, 22000], accel: 10.6, power: [122, 122], top: 112, fuels: ['hybrid', 'phev'], mpg: 69, ev: 39,
      seats: 5, doors: 5, boot: 502, len: 4540, kg: 1375, mpy: 10500, ncap: [5, 2016], onSale: false, halo: false,
      g: { build: 85, drive: 63, practicality: 80, value: 82, design: 50, running: 96 },
      verdict: 'Technically brilliant, visually challenging and capable of genuine 70mpg. The plug-in adds useful silent commuting.',
      issues: ['Styling requires commitment', 'Plug-in loses boot space'], buy: '2019-on Business Edition Plus; plug-in only if charging nightly.',
      tags: ['cheap-to-run', 'bulletproof', 'tech-fest', 'motorway-muncher', 'left-field'], rivals: ['hyundai-ioniq-ae', 'honda-insight-ze2', 'lexus-ct-zwa10'] },

    { model: 'RAV4', gen: 'XA30', years: [2006, 2012], bodies: ['suv'], segment: 'family-suv',
      priceNew: [18000, 29000], used: [3000, 9000], accel: 10.5, power: [134, 175], top: 124, fuels: ['petrol', 'diesel'], mpg: 40, ev: null,
      seats: 5, doors: 5, boot: 586, len: 4395, kg: 1560, mpy: 8500, ncap: [4, 2006], onSale: false, halo: false,
      g: { build: 83, drive: 57, practicality: 84, value: 86, design: 52, running: 75 },
      verdict: 'Before crossovers became fashion, this was simply a useful Toyota with four-wheel drive and a side-hinged door.',
      issues: ['2.2 diesel head-gasket risk', 'Rear door awkward in tight parking'], buy: '2.0 petrol XT-R with clean underside and full service file.',
      tags: ['bulletproof', 'dog-friendly', 'adventure-ready', 'bargain-hero', 'school-run'], rivals: ['honda-cr-v-re', 'nissan-x-trail-t31', 'suzuki-grand-vitara-jt'] },

    { model: 'RAV4', gen: 'XA40', years: [2013, 2019], bodies: ['suv'], segment: 'family-suv',
      priceNew: [23000, 38000], used: [9000, 21000], accel: 8.1, power: [143, 197], top: 124, fuels: ['petrol', 'diesel', 'hybrid'], mpg: 55, ev: null,
      seats: 5, doors: 5, boot: 547, len: 4605, kg: 1625, mpy: 9500, ncap: [5, 2013], onSale: false, halo: false,
      g: { build: 85, drive: 62, practicality: 86, value: 84, design: 57, running: 87 },
      verdict: 'The RAV4 discovered hybrid power and became the dependable family crossover blueprint. Huge, frugal and resolutely beige-minded.',
      issues: ['CVT drones on steep climbs', 'Tailgate motors can weaken'], buy: '2016-on 2.5 Hybrid Icon AWD with annual hybrid checks.',
      tags: ['bulletproof', 'school-run', 'dog-friendly', 'cheap-to-run', 'tow-car'], rivals: ['honda-cr-v-rm', 'nissan-x-trail-t32', 'mazda-cx-5-ke'] },

    { model: 'Land Cruiser', gen: 'J120', years: [2003, 2009], bodies: ['suv'], segment: 'off-roader',
      priceNew: [28000, 46000], used: [6000, 20000], accel: 11.2, power: [161, 249], top: 112, fuels: ['petrol', 'diesel'], mpg: 28, ev: null,
      seats: 8, doors: 5, boot: 620, len: 4715, kg: 2075, mpy: 8500, ncap: [4, 2003], onSale: false, halo: false,
      g: { build: 94, drive: 48, practicality: 86, value: 83, design: 62, running: 46 },
      verdict: 'The cockroach of premium off-roaders: thirsty, ponderous and built to cross continents long after the finance SUVs expire.',
      issues: ['Chassis corrosion needs inspection', 'Injectors and suspension can be costly'], buy: 'Late LC5 3.0 D-4D with rust-free frame and injector records.',
      tags: ['bulletproof', 'go-anywhere', 'chunky-4x4', 'tow-car', 'off-grid', 'seven-seats'], rivals: ['mitsubishi-shogun-v80', 'land-rover-discovery-l319', 'nissan-pathfinder-r51'] },

    { model: 'Land Cruiser V8', gen: 'J200', years: [2008, 2015], bodies: ['suv'], segment: 'off-roader',
      priceNew: [55000, 67000], used: [18000, 45000], accel: 8.2, power: [286, 286], top: 130, fuels: ['diesel'], mpg: 27, ev: null,
      seats: 7, doors: 5, boot: 701, len: 4950, kg: 2660, mpy: 8000, ncap: null, onSale: false, halo: false,
      g: { build: 97, drive: 55, practicality: 91, value: 77, design: 68, running: 34 },
      verdict: 'A bank vault with a diesel V8 and low-range gearing. Imperial thirst, planetary durability, astonishing used-car presence.',
      issues: ['Fuel bills are industrial', 'Hydraulic suspension repairs cost dearly'], buy: 'Full Toyota history, rust-free underside and proof of cambelt work.',
      tags: ['bulletproof', 'go-anywhere', 'wafty', 'tow-car', 'seven-seats', 'money-pit-risk'], rivals: ['range-rover-l322', 'mercedes-benz-gl-class-x164', 'lexus-lx-j200'] },

    { model: 'Hilux', gen: 'AN10', years: [2005, 2015], bodies: ['pickup'], segment: 'pickup',
      priceNew: [17000, 30000], used: [5000, 20000], accel: 12.0, power: [102, 171], top: 109, fuels: ['diesel'], mpg: 34, ev: null,
      seats: 5, doors: 4, boot: 1100, len: 5260, kg: 1885, mpy: 11000, ncap: [4, 2006], onSale: false, halo: false,
      g: { build: 93, drive: 45, practicality: 87, value: 83, design: 57, running: 60 },
      verdict: 'A proper work truck from before pickups became lifestyle jewellery. Unladen ride punishes; durability rewards for decades.',
      issues: ['Chassis corrosion on hard-worked trucks', 'Injectors can rattle when worn'], buy: 'Invincible 3.0 double cab with clean frame and no tuning box.',
      tags: ['bulletproof', 'go-anywhere', 'tow-car', 'off-grid', 'chunky-4x4'], rivals: ['nissan-navara-d40', 'mitsubishi-l200-mk4', 'ford-ranger-t6'] },

    { model: 'MR2', gen: 'W30', years: [2000, 2006], bodies: ['convertible'], segment: 'roadster-classic',
      priceNew: [16000, 19000], used: [2500, 9000], accel: 7.9, power: [138, 138], top: 130, fuels: ['petrol'], mpg: 38, ev: null,
      seats: 2, doors: 2, boot: 90, len: 3895, kg: 975, mpy: 4000, ncap: null, onSale: false, halo: false,
      g: { build: 76, drive: 91, practicality: 24, value: 90, design: 72, running: 76 },
      verdict: 'Mid-engined, under a tonne and cheaper than a tired hatchback. No luggage space; enormous steering purity.',
      issues: ['Pre-catalyst failure can damage engines', 'No conventional boot at all'], buy: '2003-on manual with healthy oil level and documented precat check.',
      tags: ['analogue-joy', 'drivers-car', 'lightweight', 'b-road-hero', 'bargain-hero', 'modern-classic'], rivals: ['mazda-mx-5-nb', 'mg-tf-mk2', 'porsche-boxster-986'] },

    { model: 'Celica', gen: 'T230', years: [1999, 2006], bodies: ['coupe'], segment: 'sports',
      priceNew: [17000, 23000], used: [2000, 9000], accel: 7.2, power: [140, 189], top: 140, fuels: ['petrol'], mpg: 36, ev: null,
      seats: 4, doors: 3, boot: 365, len: 4335, kg: 1175, mpy: 4500, ncap: null, onSale: false, halo: false,
      g: { build: 79, drive: 78, practicality: 61, value: 88, design: 78, running: 73 },
      verdict: 'A razor-edged coupé from Toyota’s rev-happy phase. The 190 sings above 6,000rpm and still carries weekend luggage.',
      issues: ['Early 140 engines can consume oil', 'Rear subframes corrode'], buy: '190 T Sport manual, post-2003, standard and rust-free.',
      tags: ['rev-happy', 'analogue-joy', 'modern-classic', 'bargain-hero', 'sleek'], rivals: ['honda-integra-type-r-dc5', 'hyundai-coupe-gk', 'mazda-rx-8-se3p'] },

    { model: 'Supra', gen: 'A80', years: [1993, 2002], bodies: ['coupe'], segment: 'super-coupe',
      priceNew: [32000, 41000], used: [35000, 100000], accel: 4.9, power: [220, 326], top: 155, fuels: ['petrol'], mpg: 24, ev: null,
      seats: 4, doors: 3, boot: 185, len: 4520, kg: 1615, mpy: 3000, ncap: null, onSale: false, halo: false,
      g: { build: 91, drive: 89, practicality: 43, value: 51, design: 94, running: 38 },
      verdict: 'The tuner-age hero whose indestructible straight-six became internet mythology. Great cars remain great; prices became fantasy.',
      issues: ['Modified histories obscure abuse', 'Turbo and gearbox parts are expensive'], buy: 'UK twin-turbo manual if wealthy; condition and originality beat colour.',
      tags: ['boxy-icon', 'future-classic', 'head-turner', 'autobahn-stormer', 'money-pit-risk', 'grand-tourer'], rivals: ['nissan-skyline-gt-r-r34', 'mazda-rx-7-fd', 'porsche-911-993'] },

    { model: 'Previa', gen: 'XR30', years: [2000, 2006], bodies: ['mpv'], segment: 'mpv-van',
      priceNew: [23000, 32000], used: [1500, 6500], accel: 11.2, power: [114, 154], top: 115, fuels: ['petrol', 'diesel'], mpg: 31, ev: null,
      seats: 7, doors: 5, boot: 495, len: 4750, kg: 1740, mpy: 7000, ncap: [4, 2003], onSale: false, halo: false,
      g: { build: 82, drive: 49, practicality: 92, value: 85, design: 61, running: 56 },
      verdict: 'A vast egg-shaped people carrier with captain’s chairs and sliding doors. Drinks petrol, carries an entire childhood.',
      issues: ['Petrol economy is painful', 'Diesel can suffer head-gasket trouble'], buy: '2.4 petrol automatic with working air-con and solid sliding doors.',
      tags: ['family-bus', 'seven-seats', 'tardis', 'van-with-windows', 'retro-charm'], rivals: ['nissan-serena-c24', 'chrysler-grand-voyager-rg', 'volkswagen-sharan-7m'] },

    { model: 'Urban Cruiser', gen: 'XP110', years: [2009, 2013], bodies: ['suv'], segment: 'small-suv',
      priceNew: [14500, 19000], used: [3000, 7500], accel: 12.5, power: [89, 100], top: 109, fuels: ['petrol', 'diesel'], mpg: 51, ev: null,
      seats: 5, doors: 5, boot: 314, len: 3930, kg: 1200, mpy: 6500, ncap: [3, 2009], onSale: false, halo: false,
      g: { build: 75, drive: 49, practicality: 67, value: 78, design: 55, running: 83 },
      verdict: 'A Yaris in hiking boots, launched before small SUVs took over. Rare, slow and usefully narrow for country lanes.',
      issues: ['Three-star safety result', 'Diesel has DPF and head-gasket concerns'], buy: 'Front-drive 1.33 petrol; four-wheel drive is unnecessary complexity.',
      tags: ['left-field', 'city-darling', 'cheap-to-run', 'adventure-ready'], rivals: ['suzuki-sx4-gy', 'nissan-juke-f15', 'dacia-duster-hs'] }
  ]
};
