// Vauxhall — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Vauxhall',
  cars: [
    { model: 'Corsa', gen: 'D', years: [2006, 2014], bodies: ['hatch'], segment: 'supermini',
      priceNew: [9000, 16000], used: [1500, 5000], accel: 6.8, power: [60, 205], top: 140,
      fuels: ['petrol', 'diesel'], mpg: 48, ev: null, seats: 5, doors: 5, boot: 285, len: 3999, kg: 1080,
      mpy: 7000, ncap: [5, 2006], onSale: false, halo: false,
      g: { build: 62, drive: 58, practicality: 64, value: 78, design: 54, running: 82 },
      verdict: 'The learner-driver’s Britain in car form. Unremarkable everywhere except the price — and the VXR’s giggles.',
      issues: ['Timing chains on 1.2/1.4 petrols', 'Electric PAS faults'],
      buy: '1.4 SXi with a fat history file. VXR Nürburgring if feeling spicy.',
      tags: ['first-car-friendly', 'bargain-hero', 'cheap-to-run', 'crowd-pleaser'],
      rivals: ['ford-fiesta-mk7', 'renault-clio-iv', 'volkswagen-polo-mk5'] },

    { model: 'Corsa', gen: 'F', years: [2019, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [17000, 26000], used: [8000, 20000], accel: 8.1, power: [75, 156], top: 129,
      fuels: ['petrol', 'ev'], mpg: 54, ev: 246, seats: 5, doors: 5, boot: 309, len: 4060, kg: 1090,
      mpy: 8000, ncap: [4, 2019], onSale: true, halo: false,
      g: { build: 76, drive: 66, practicality: 66, value: 78, design: 70, running: 86 },
      verdict: 'A 208 in a Griffin blazer — Britain’s best-seller by fleet default. Corsa Electric used is genuine value.',
      issues: ['PureTech belt history', 'Cabin plainer than the 208'],
      buy: '1.2 Turbo 100 GS Line; Corsa-e at £9k used is a smart city buy.',
      tags: ['first-car-friendly', 'cheap-to-run', 'crowd-pleaser', 'discreet'],
      rivals: ['peugeot-208-p21', 'ford-fiesta-mk8', 'renault-clio-v'] },

    { model: 'Astra', gen: 'K', years: [2015, 2021], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [16000, 26000], used: [6000, 15000], accel: 6.6, power: [100, 200], top: 140,
      fuels: ['petrol', 'diesel'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 370, len: 4370, kg: 1220,
      mpy: 9000, ncap: [5, 2015], onSale: false, halo: false,
      g: { build: 72, drive: 70, practicality: 76, value: 82, design: 62, running: 82 },
      verdict: 'Lighter, sharper, better than its reputation — the Astra that deserved more credit and now costs buttons.',
      issues: ['Interior plastics budget', 'Some 1.0/1.4 coolant leaks'],
      buy: '1.4T 150 SRi Sports Tourer — honest family value.',
      tags: ['bargain-hero', 'cheap-to-run', 'discreet', 'dog-friendly'],
      rivals: ['ford-focus-mk4', 'volkswagen-golf-mk7', 'kia-ceed-cd'] },

    { model: 'Astra', gen: 'L', years: [2022, 0], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [25000, 40000], used: [14000, 30000], accel: 7.3, power: [110, 225], top: 130,
      fuels: ['petrol', 'phev', 'ev'], mpg: 54, ev: 41, seats: 5, doors: 5, boot: 422, len: 4374, kg: 1300,
      mpy: 9000, ncap: [4, 2022], onSale: true, halo: false,
      g: { build: 80, drive: 70, practicality: 76, value: 76, design: 80, running: 82 },
      verdict: 'The Vizor face finally made Vauxhall sharp. Sports Tourer Electric is a rare thing: an affordable EV estate.',
      issues: ['Rear seat mid-pack', 'PHEV boot loses depth'],
      buy: 'Sports Tourer Electric GS — the quiet estate bargain.',
      tags: ['sleek', 'discreet', 'school-run', 'cheap-to-run', 'crowd-pleaser'],
      rivals: ['peugeot-308-p52', 'volkswagen-golf-mk8', 'kia-ceed-cd'] },

    { model: 'Mokka', gen: 'B', years: [2021, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [23000, 32000], used: [12000, 25000], accel: 8.2, power: [100, 156], top: 124,
      fuels: ['petrol', 'ev'], mpg: 51, ev: 250, seats: 5, doors: 5, boot: 350, len: 4151, kg: 1240,
      mpy: 8500, ncap: [4, 2021], onSale: true, halo: false,
      g: { build: 76, drive: 64, practicality: 66, value: 76, design: 80, running: 84 },
      verdict: 'The design-led rebrand in miniature — genuinely handsome, sensibly priced, e version silences the school run.',
      issues: ['Boot small for the class', 'Rear legroom snug'],
      buy: 'Mokka Electric GS used — style, volts, value.',
      tags: ['city-darling', 'head-turner', 'cheap-to-run', 'school-run'],
      rivals: ['peugeot-2008-p24', 'renault-captur-ii', 'ford-puma-mk1'] },

    { model: 'Grandland', gen: 'B', years: [2024, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [34000, 46000], used: [26000, 40000], accel: 6.2, power: [136, 325], top: 118,
      fuels: ['petrol', 'hybrid', 'ev'], mpg: 51, ev: 435, seats: 5, doors: 5, boot: 550, len: 4650, kg: 1725,
      mpy: 10000, ncap: null, onSale: true, halo: false,
      g: { build: 78, drive: 66, practicality: 82, value: 76, design: 76, running: 82 },
      verdict: 'Sharp-suited family SUV on the new STLA platform; the Electric’s 435-mile option rewrites the badge’s ambitions.',
      issues: ['New platform — long-term unknowns', 'Brand image still catching up to the car'],
      buy: 'Grandland Electric 98kWh Design — range for days.',
      tags: ['school-run', 'silent-cruiser', 'discreet', 'crowd-pleaser'],
      rivals: ['peugeot-e-3008-p64', 'renault-scenic-e-tech-bcm', 'skoda-enyaq-5az'] },

    { model: 'Insignia', gen: 'B', years: [2017, 2022], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [19000, 33000], used: [8000, 18000], accel: 6.9, power: [110, 230], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 5, doors: 5, boot: 490, len: 4897, kg: 1500,
      mpy: 11000, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 74, drive: 68, practicality: 84, value: 84, design: 68, running: 76 },
      verdict: 'Vast, handsome-enough, forever undervalued. The Sports Tourer is half-price Passat practicality with GSi spice available.',
      issues: ['Fleet histories — check thrash factor', 'Infotainment ages'],
      buy: '2.0 Turbo D SRi Nav Sports Tourer — mile-eater on a budget.',
      tags: ['bargain-hero', 'motorway-muncher', 'tardis', 'discreet', 'dog-friendly'],
      rivals: ['ford-mondeo-mk5', 'skoda-superb-b8', 'mazda-6-gj'] },

    { model: 'Monaro', gen: 'V2', years: [2004, 2007], bodies: ['coupe'], segment: 'super-coupe',
      priceNew: [28000, 37000], used: [14000, 28000], accel: 5.3, power: [329, 398], top: 165,
      fuels: ['petrol'], mpg: 20, ev: null, seats: 4, doors: 2, boot: 370, len: 4789, kg: 1677,
      mpy: 4000, ncap: null, onSale: false, halo: false,
      g: { build: 68, drive: 78, practicality: 58, value: 74, design: 66, running: 30 },
      verdict: 'An Aussie V8 muscle coupé wearing a Griffin. VXR 6.0 is a cult classic with values waking — the people’s M car.',
      issues: ['Thirst measured in gallons per smile', 'Rust underneath — inspect'],
      buy: 'VXR 6.0 manual, unmodified, garaged. Join the club.',
      tags: ['v8-soundtrack', 'muscular', 'left-field', 'modern-classic', 'future-classic', 'analogue-joy'],
      rivals: ['ford-mustang-s550', 'bmw-m3-e92', 'chrysler-300c-lx'] },

    { model: 'Zafira Tourer', gen: 'C', years: [2012, 2018], bodies: ['mpv'], segment: 'seven-seater',
      priceNew: [18000, 28000], used: [4500, 11000], accel: 8.9, power: [120, 200], top: 129,
      fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 7, doors: 5, boot: 710, len: 4656, kg: 1628,
      mpy: 9500, ncap: [5, 2011], onSale: false, halo: false,
      g: { build: 70, drive: 60, practicality: 88, value: 84, design: 58, running: 74 },
      verdict: 'Flex7 seating and panoramic glass for peanuts. The forgotten people-mover that still does the job brilliantly.',
      issues: ['Earlier Zafira B heater scandal tainted the name (C unaffected)', 'Diesel EGR age'],
      buy: '2.0 CDTi 165 SRi — seven seats for £6k, job done.',
      tags: ['seven-seats', 'family-bus', 'bargain-hero', 'tardis', 'discreet'],
      rivals: ['ford-s-max-mk2', 'volkswagen-touran-5t', 'citroen-grand-c4-spacetourer-b78'] },

    { model: 'VX220', gen: 'Z22', years: [2000, 2005], bodies: ['convertible'], segment: 'roadster-classic',
      priceNew: [23000, 30000], used: [14000, 26000], accel: 4.7, power: [147, 220], top: 151,
      fuels: ['petrol'], mpg: 34, ev: null, seats: 2, doors: 2, boot: 206, len: 3786, kg: 875,
      mpy: 3000, ncap: null, onSale: false, halo: false,
      g: { build: 66, drive: 92, practicality: 24, value: 76, design: 78, running: 62 },
      verdict: 'An Elise with a Griffin badge and a warmer heart. The Turbo is savage; all are appreciating. The secret Lotus.',
      issues: ['Sill damage from clumsy entries', 'Cam-follower checks on Turbo'],
      buy: 'VX220 Turbo, standard, with the roof panel intact.',
      tags: ['lightweight', 'analogue-joy', 'modern-classic', 'future-classic', 'track-day', 'left-field', 'drivers-car'],
      rivals: ['lotus-elise-s2', 'mazda-mx-5-nb', 'toyota-mr2-w30'] }
  ]
};
