// Volkswagen — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Volkswagen',
  cars: [
    { model: 'Up!', gen: 'AA', years: [2011, 2023], bodies: ['hatch'], segment: 'city',
      priceNew: [9000, 17000], used: [3500, 12000], accel: 8.8, power: [60, 115], top: 116,
      fuels: ['petrol'], mpg: 55, ev: null, seats: 4, doors: 5, boot: 251, len: 3600, kg: 940,
      mpy: 6000, ncap: [5, 2011], onSale: false, halo: false,
      g: { build: 76, drive: 74, practicality: 56, value: 88, design: 78, running: 92 },
      verdict: 'The best small car of its generation, full stop. Tiny outside, honest inside — and the GTI is a giggling riot.',
      issues: ['Three-pot thrum (charming or not)', 'Basic kit on early cars'],
      buy: 'Up! GTI — the modern Mk1 Golf GTI. Or any 1.0 75 for pennies.',
      tags: ['city-darling', 'first-car-friendly', 'cheap-to-run', 'pocket-rocket', 'bargain-hero', 'analogue-joy'],
      rivals: ['toyota-aygo-ab40', 'hyundai-i10-ac3', 'fiat-500-312'] },

    { model: 'Polo', gen: 'Mk6', years: [2017, 0], bodies: ['hatch'], segment: 'supermini',
      priceNew: [16000, 28000], used: [9000, 24000], accel: 6.5, power: [80, 207], top: 149,
      fuels: ['petrol'], mpg: 52, ev: null, seats: 5, doors: 5, boot: 351, len: 4053, kg: 1105,
      mpy: 8000, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 82, drive: 70, practicality: 74, value: 76, design: 66, running: 82 },
      verdict: 'A Golf in all but name — Mk5 Golf size, grown-up manners. The GTI is the stealth hot supermini nobody clocks.',
      issues: ['Dull unless GTI', 'Touch controls post-2021'],
      buy: '1.0 TSI 95 Life for sense; Polo GTI for quiet speed.',
      tags: ['first-car-friendly', 'crowd-pleaser', 'cheap-to-run', 'discreet'],
      rivals: ['ford-fiesta-mk8', 'renault-clio-v', 'toyota-yaris-xp210'] },

    { model: 'Golf', gen: 'Mk5', years: [2003, 2009], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [14000, 26000], used: [1500, 6500], accel: 6.9, power: [75, 250], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 45, ev: null, seats: 5, doors: 5, boot: 350, len: 4204, kg: 1305,
      mpy: 8500, ncap: [5, 2004], onSale: false, halo: false,
      g: { build: 74, drive: 74, practicality: 74, value: 82, design: 62, running: 70 },
      verdict: 'The generation that made the GTI great again. Everything else is honest transport at shoestring prices.',
      issues: ['DSG mechatronics', 'Cam-follower wear on 2.0 TFSI'],
      buy: 'Mk5 GTI manual 3dr — an all-time great for £5k.',
      tags: ['bargain-hero', 'first-car-friendly', 'crowd-pleaser', 'modern-classic'],
      rivals: ['ford-focus-mk2', 'audi-a3-8p', 'bmw-1-series-e87'] },

    { model: 'Golf', gen: 'Mk7', years: [2012, 2020], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [17000, 34000], used: [6500, 20000], accel: 4.6, power: [85, 310], top: 155,
      fuels: ['petrol', 'diesel', 'phev', 'ev'], mpg: 55, ev: 144, seats: 5, doors: 5, boot: 380, len: 4258, kg: 1270,
      mpy: 9000, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 84, drive: 80, practicality: 80, value: 86, design: 72, running: 80 },
      verdict: 'Peak Golf, arguably peak car-as-appliance. From 1.0 TSI to R, there is no bad answer — the used-market default.',
      issues: ['1.5 evo kangaroo idle (updated)', 'DSG service history vital'],
      buy: 'GTI Performance Pack manual, or a 1.5 TSI Match for everyone else.',
      tags: ['crowd-pleaser', 'bulletproof', 'bargain-hero', 'motorway-muncher', 'first-car-friendly', 'discreet'],
      rivals: ['ford-focus-mk4', 'audi-a3-8v', 'seat-leon-5f'] },

    { model: 'Golf GTI', gen: 'Mk7', years: [2013, 2020], bodies: ['hatch'], segment: 'hot-hatch',
      priceNew: [28000, 35000], used: [12000, 24000], accel: 6.2, power: [220, 290], top: 155,
      fuels: ['petrol'], mpg: 44, ev: null, seats: 5, doors: 5, boot: 380, len: 4268, kg: 1360,
      mpy: 8000, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 84, drive: 86, practicality: 78, value: 84, design: 74, running: 68 },
      verdict: 'The complete hot hatch: fast enough, comfy enough, classless tartan. Clubsport S held the Ring record for a reason.',
      issues: ['Check for track use and remaps', 'Water pumps'],
      buy: 'Performance Pack manual in Tornado Red; Clubsport if you find one.',
      tags: ['pocket-rocket', 'drivers-car', 'crowd-pleaser', 'b-road-hero', 'modern-classic', 'school-run'],
      rivals: ['honda-civic-type-r-fk8', 'ford-focus-st-mk4', 'hyundai-i30-n-pd'] },

    { model: 'Golf R', gen: 'Mk7', years: [2014, 2020], bodies: ['hatch', 'estate'], segment: 'hot-hatch',
      priceNew: [32000, 40000], used: [15000, 28000], accel: 4.6, power: [300, 310], top: 155,
      fuels: ['petrol'], mpg: 40, ev: null, seats: 5, doors: 5, boot: 380, len: 4276, kg: 1495,
      mpy: 8000, ncap: [5, 2012], onSale: false, halo: false,
      g: { build: 84, drive: 82, practicality: 78, value: 80, design: 70, running: 62 },
      verdict: 'Four-wheel-drive point-to-point pace with zero tantrums. The estate is the great all-weather one-car answer.',
      issues: ['Many are modified — walk away', 'Haldex service often skipped'],
      buy: 'Standard, unmodified R estate with every stamp.',
      tags: ['pocket-rocket', 'discreet', 'motorway-muncher', 'dog-friendly', 'crowd-pleaser'],
      rivals: ['audi-s3-8v', 'bmw-m135i-f20', 'mercedes-amg-a35-w177'] },

    { model: 'Golf', gen: 'Mk8', years: [2020, 0], bodies: ['hatch', 'estate'], segment: 'family-hatch',
      priceNew: [25000, 42000], used: [14000, 34000], accel: 4.7, power: [110, 333], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 54, ev: 62, seats: 5, doors: 5, boot: 381, len: 4284, kg: 1320,
      mpy: 9000, ncap: [5, 2019], onSale: true, halo: false,
      g: { build: 76, drive: 78, practicality: 78, value: 74, design: 66, running: 78 },
      verdict: 'Still fundamentally excellent, initially sabotaged by its own touchscreens. The 2024 facelift fixed most of the rage.',
      issues: ['Pre-facelift infotainment misery', 'Touch sliders unlit at night (fixed 2024)'],
      buy: 'Facelift GTE or 1.5 eTSI Match; GTI Clubsport for the fast one.',
      tags: ['crowd-pleaser', 'company-car-hero', 'school-run', 'tech-fest'],
      rivals: ['audi-a3-8y', 'ford-focus-mk4', 'toyota-corolla-e210'] },

    { model: 'Passat', gen: 'B8', years: [2014, 2023], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [23000, 42000], used: [8000, 26000], accel: 5.9, power: [120, 280], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 55, ev: 35, seats: 5, doors: 4, boot: 650, len: 4767, kg: 1470,
      mpy: 11000, ncap: [5, 2014], onSale: false, halo: false,
      g: { build: 82, drive: 68, practicality: 88, value: 84, design: 64, running: 78 },
      verdict: 'The estate that does everything except excite — which, at 55mpg with a caravan on, is its own kind of thrilling.',
      issues: ['DSG at high miles', 'GTE battery health check'],
      buy: '2.0 TDI 150 Estate SEL or a GTE for the commute maths.',
      tags: ['tardis', 'motorway-muncher', 'tow-car', 'bargain-hero', 'dog-friendly', 'discreet'],
      rivals: ['skoda-superb-b8', 'ford-mondeo-mk5', 'mazda-6-gj'] },

    { model: 'Arteon', gen: '3H', years: [2017, 2024], bodies: ['saloon', 'estate'], segment: 'exec',
      priceNew: [32000, 48000], used: [14000, 32000], accel: 5.6, power: [150, 320], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 50, ev: 36, seats: 5, doors: 5, boot: 563, len: 4862, kg: 1560,
      mpy: 10000, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 82, drive: 70, practicality: 82, value: 78, design: 80, running: 72 },
      verdict: 'The best-looking VW in years, ignored because badge. A Shooting Brake R is a £60k car’s presence for half that.',
      issues: ['Not actually sportier than a Passat'],
      buy: 'Shooting Brake 2.0 TDI 200 R-Line — style with a Passat heart.',
      tags: ['sleek', 'left-field', 'head-turner', 'tardis', 'bargain-hero'],
      rivals: ['audi-a5-b9', 'peugeot-508-r8', 'bmw-4-series-g22'] },

    { model: 'T-Roc', gen: 'A11', years: [2017, 0], bodies: ['suv', 'convertible'], segment: 'small-suv',
      priceNew: [23000, 40000], used: [12000, 30000], accel: 4.9, power: [110, 300], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 47, ev: null, seats: 5, doors: 5, boot: 445, len: 4234, kg: 1310,
      mpy: 9000, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 76, drive: 70, practicality: 76, value: 74, design: 70, running: 74 },
      verdict: 'Golf on stilts, Britain’s default crossover. Fine everywhere, thrilling nowhere — exactly what most buyers want.',
      issues: ['Early cabins scratchy (improved 2022)'],
      buy: '1.5 TSI 150 Style DSG — the one everyone actually needs.',
      tags: ['crowd-pleaser', 'school-run', 'city-darling', 'first-car-friendly'],
      rivals: ['nissan-qashqai-j12', 'kia-xceed-cd', 'ford-puma-mk1'] },

    { model: 'Tiguan', gen: 'AD', years: [2016, 2024], bodies: ['suv'], segment: 'family-suv',
      priceNew: [28000, 45000], used: [12000, 32000], accel: 5.5, power: [130, 320], top: 152,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 47, ev: 30, seats: 7, doors: 5, boot: 615, len: 4486, kg: 1560,
      mpy: 10500, ncap: [5, 2016], onSale: false, halo: false,
      g: { build: 82, drive: 70, practicality: 84, value: 78, design: 66, running: 70 },
      verdict: 'The Golf of SUVs: unshowy, roomy, resale-proof. Allspace adds seats six and seven for the school-run surge.',
      issues: ['DSG shunt in traffic', 'AdBlue on diesels'],
      buy: '2.0 TDI 150 Match 4Motion; Allspace if the family is growing.',
      tags: ['school-run', 'crowd-pleaser', 'tow-car', 'dog-friendly', 'tardis'],
      rivals: ['skoda-kodiaq-ns7', 'nissan-qashqai-j12', 'toyota-rav4-xa50'] },

    { model: 'Touareg', gen: 'CR', years: [2018, 0], bodies: ['suv'], segment: 'large-suv',
      priceNew: [48000, 75000], used: [24000, 58000], accel: 5.9, power: [231, 462], top: 155,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 38, ev: 30, seats: 5, doors: 5, boot: 810, len: 4878, kg: 2070,
      mpy: 10000, ncap: [5, 2018], onSale: true, halo: false,
      g: { build: 84, drive: 72, practicality: 86, value: 78, design: 66, running: 50 },
      verdict: 'A Bentayga skeleton in sensible clothes. Immense towing, vault cabin — the connoisseur’s quiet Q7 alternative.',
      issues: ['No seven-seat option', 'Air suspension bills later in life'],
      buy: 'V6 TDI Black Edition — 3.5-tonne towing, first-class refinement.',
      tags: ['tow-car', 'wafty', 'discreet', 'muscular', 'dog-friendly'],
      rivals: ['audi-q7-4m', 'bmw-x5-g05', 'land-rover-discovery-l462'] },

    { model: 'ID.3', gen: 'E11', years: [2020, 0], bodies: ['hatch'], segment: 'ev-native',
      priceNew: [30000, 43000], used: [12000, 30000], accel: 7.3, power: [145, 326], top: 99,
      fuels: ['ev'], mpg: null, ev: 347, seats: 5, doors: 5, boot: 385, len: 4261, kg: 1730,
      mpy: 8500, ncap: [5, 2020], onSale: true, halo: false,
      g: { build: 70, drive: 72, practicality: 78, value: 78, design: 68, running: 84 },
      verdict: 'VW’s electric Golf moment, fumbled at launch by software, redeemed by updates and collapsing used prices.',
      issues: ['Early software woes — insist on updates', 'Cheap cabin plastics pre-facelift'],
      buy: 'Pro S 77kWh facelift used — 300 real miles for Fiesta money.',
      tags: ['silent-cruiser', 'cheap-to-run', 'depreciation-king', 'school-run', 'city-darling'],
      rivals: ['cupra-born-k11', 'renault-megane-e-tech-bcb', 'nissan-leaf-ze1'] },

    { model: 'ID.4 / ID.5', gen: 'E21', years: [2021, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [37000, 55000], used: [16000, 38000], accel: 5.4, power: [148, 340], top: 112,
      fuels: ['ev'], mpg: null, ev: 335, seats: 5, doors: 5, boot: 543, len: 4584, kg: 2120,
      mpy: 9000, ncap: [5, 2021], onSale: true, halo: false,
      g: { build: 74, drive: 66, practicality: 84, value: 76, design: 64, running: 82 },
      verdict: 'The family-EV workhorse: huge inside, softly sprung, anonymous. Used GTX models are performance-car quick for £25k.',
      issues: ['Infotainment still laggy pre-2023', 'Uninspiring dynamics'],
      buy: 'Pro Match 77kWh, 2023-on software, heat pump optioned.',
      tags: ['school-run', 'tardis', 'silent-cruiser', 'depreciation-king', 'crowd-pleaser'],
      rivals: ['skoda-enyaq-5az', 'tesla-model-y-juniper', 'nissan-ariya-fe0'] },

    { model: 'ID. Buzz', gen: 'EB', years: [2022, 0], bodies: ['mpv'], segment: 'mpv-van',
      priceNew: [55000, 72000], used: [35000, 58000], accel: 7.9, power: [204, 340], top: 90,
      fuels: ['ev'], mpg: null, ev: 290, seats: 7, doors: 5, boot: 1121, len: 4712, kg: 2470,
      mpy: 9000, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 80, drive: 68, practicality: 90, value: 62, design: 94, running: 76 },
      verdict: 'The happiest-looking vehicle on sale. A rolling smile with van-space inside — pricey, but nothing else is this joyful.',
      issues: ['Costs serious money', 'Range drops hard at motorway pace'],
      buy: 'LWB 7-seater in two-tone — commit to the bit.',
      tags: ['retro-charm', 'head-turner', 'van-with-windows', 'family-bus', 'future-classic', 'seven-seats'],
      rivals: ['mercedes-benz-v-class-w447', 'multivan-t7-volkswagen', 'kia-ev9-mv'] },

    { model: 'Multivan', gen: 'T7', years: [2021, 0], bodies: ['mpv'], segment: 'mpv-van',
      priceNew: [48000, 70000], used: [32000, 58000], accel: 8.1, power: [136, 245], top: 120,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 40, ev: 30, seats: 7, doors: 5, boot: 1844, len: 4973, kg: 2110,
      mpy: 11000, ncap: [5, 2022], onSale: true, halo: false,
      g: { build: 80, drive: 64, practicality: 94, value: 66, design: 64, running: 62 },
      verdict: 'The Swiss-army family room on wheels. Seats slide, fold, vanish; nothing carries seven humans with less fuss.',
      issues: ['Van-sized parking reality', 'PHEV boot bite'],
      buy: 'eHybrid Life LWB — school-run electric, holiday diesel-free-ish.',
      tags: ['van-with-windows', 'family-bus', 'tardis', 'seven-seats', 'adventure-ready'],
      rivals: ['mercedes-benz-v-class-w447', 'ford-tourneo-custom-mk2', 'volkswagen-id-buzz-eb'] },

    { model: 'California', gen: 'T6.1', years: [2019, 2024], bodies: ['van'], segment: 'mpv-van',
      priceNew: [55000, 85000], used: [40000, 75000], accel: 10.5, power: [110, 204], top: 119,
      fuels: ['diesel'], mpg: 36, ev: null, seats: 4, doors: 4, boot: 1000, len: 4904, kg: 2510,
      mpy: 8000, ncap: null, onSale: false, halo: false,
      g: { build: 84, drive: 60, practicality: 90, value: 60, design: 76, running: 56 },
      verdict: 'The pop-top dream, priced like the dream it is. Holds value absurdly because everyone wants the same escape.',
      issues: ['Values mean thefts — garage it', 'Camper tax: pay to play'],
      buy: 'Ocean 150 DSG, heated everything, awning ready.',
      tags: ['adventure-ready', 'van-with-windows', 'off-grid', 'future-classic', 'go-anywhere'],
      rivals: ['mercedes-benz-marco-polo-w447', 'ford-transit-custom-nugget-mk2'] },

    { model: 'Scirocco', gen: 'Mk3', years: [2008, 2017], bodies: ['coupe'], segment: 'sports',
      priceNew: [21000, 33000], used: [5000, 14000], accel: 5.5, power: [122, 280], top: 155,
      fuels: ['petrol', 'diesel'], mpg: 44, ev: null, seats: 4, doors: 2, boot: 312, len: 4256, kg: 1305,
      mpy: 7500, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 78, drive: 76, practicality: 58, value: 80, design: 80, running: 68 },
      verdict: 'A Golf GTI in a party dress that undercuts it used. The R remains a seriously quick, seriously cool bargain.',
      issues: ['Rear visibility', 'Cam chain tensioner on early 1.4 TSI'],
      buy: 'Scirocco R DSG or a 2.0 TSI GT — style per pound champion.',
      tags: ['sleek', 'bargain-hero', 'modern-classic', 'head-turner', 'first-car-friendly'],
      rivals: ['audi-tt-8j', 'peugeot-rcz-t75', 'toyota-gt86-zn6'] },

    { model: 'Touran', gen: '5T', years: [2015, 0], bodies: ['mpv'], segment: 'seven-seater',
      priceNew: [26000, 38000], used: [10000, 28000], accel: 8.9, power: [110, 190], top: 130,
      fuels: ['petrol', 'diesel'], mpg: 50, ev: null, seats: 7, doors: 5, boot: 917, len: 4527, kg: 1520,
      mpy: 10500, ncap: [5, 2015], onSale: true, halo: false,
      g: { build: 78, drive: 62, practicality: 92, value: 82, design: 52, running: 76 },
      verdict: 'Deeply unfashionable, devastatingly useful. Seven seats, fold-flat everything — the MPV the SUV crowd secretly needs.',
      issues: ['Invisible to your neighbours', 'DSG history check'],
      buy: '2.0 TDI 150 SEL — the family logistics answer.',
      tags: ['seven-seats', 'family-bus', 'tardis', 'school-run', 'bargain-hero', 'dog-friendly'],
      rivals: ['citroen-grand-c4-spacetourer-b78', 'ford-s-max-mk2', 'seat-alhambra-7n'] }
  ]
};
