// Volvo — model-generations, UK market. Curated for Vroom.
export default {
  make: 'Volvo',
  cars: [
    { model: 'V70', gen: 'P3', years: [2007, 2016], bodies: ['estate'], segment: 'exec',
      priceNew: [25000, 40000], used: [4000, 13000], accel: 6.2, power: [136, 304], top: 149,
      fuels: ['petrol', 'diesel'], mpg: 48, ev: null, seats: 5, doors: 5, boot: 575, len: 4823, kg: 1711,
      mpy: 10500, ncap: [5, 2007], onSale: false, halo: false,
      g: { build: 84, drive: 62, practicality: 90, value: 84, design: 64, running: 70 },
      verdict: 'The archetypal Volvo estate’s final form: heated everything, dog guard optional, 300k miles entirely expected.',
      issues: ['D5 swirl flaps and EGR at big miles', 'Rear air suspension (if fitted) ages'],
      buy: 'D4 SE Lux, later the better — antiques-run royalty.',
      tags: ['tardis', 'bulletproof', 'dog-friendly', 'wafty', 'bargain-hero', 'motorway-muncher'],
      rivals: ['mercedes-benz-e-class-w212', 'audi-a6-c7', 'bmw-5-series-f10'] },

    { model: 'V60', gen: 'P6', years: [2018, 0], bodies: ['estate'], segment: 'compact-exec',
      priceNew: [32000, 50000], used: [15000, 38000], accel: 4.6, power: [150, 405], top: 112,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 50, ev: 55, seats: 5, doors: 5, boot: 529, len: 4761, kg: 1680,
      mpy: 10000, ncap: [5, 2018], onSale: true, halo: false,
      g: { build: 86, drive: 70, practicality: 84, value: 78, design: 84, running: 74 },
      verdict: 'The estate as Scandi furniture — cool, calm, beautifully lit. T6 Recharge does 55 electric miles between lattes.',
      issues: ['112mph cap divides opinion', 'Sensus infotainment ages (pre-Google cars)'],
      buy: 'T6 Recharge Plus — the tasteful family plug-in.',
      tags: ['sleek', 'dog-friendly', 'posh-interior', 'wafty', 'school-run', 'discreet'],
      rivals: ['bmw-3-series-g20', 'audi-a4-b9', 'mercedes-benz-c-class-w206'] },

    { model: 'V90', gen: 'P5', years: [2016, 2024], bodies: ['estate', 'saloon'], segment: 'exec',
      priceNew: [37000, 60000], used: [15000, 42000], accel: 4.8, power: [150, 405], top: 112,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 50, ev: 54, seats: 5, doors: 5, boot: 560, len: 4936, kg: 1770,
      mpy: 10500, ncap: [5, 2017], onSale: false, halo: false,
      g: { build: 88, drive: 68, practicality: 88, value: 80, design: 86, running: 72 },
      verdict: 'Scandinavian sanctuary on wheels. The most beautiful big estate of its era, gliding rather than hurrying.',
      issues: ['Not a driver’s car and doesn’t care', 'PHEV boot loses underfloor space'],
      buy: 'D5 or T6 Recharge Inscription — velvet motorway life.',
      tags: ['wafty', 'sleek', 'tardis', 'posh-interior', 'dog-friendly', 'motorway-muncher'],
      rivals: ['mercedes-benz-e-class-w213', 'audi-a6-c8', 'bmw-5-series-g30'] },

    { model: 'XC40', gen: 'P8', years: [2017, 0], bodies: ['suv'], segment: 'small-suv',
      priceNew: [28000, 46000], used: [14000, 36000], accel: 4.9, power: [129, 408], top: 112,
      fuels: ['petrol', 'phev', 'ev'], mpg: 45, ev: 334, seats: 5, doors: 5, boot: 452, len: 4425, kg: 1685,
      mpy: 9500, ncap: [5, 2018], onSale: true, halo: false,
      g: { build: 84, drive: 68, practicality: 80, value: 76, design: 84, running: 74 },
      verdict: 'The Tonka-chic small Volvo that made rivals look try-hard. Recharge EV twins carry the same cool silently.',
      issues: ['Firm-ish ride on 20s', 'Petrol T2 modest'],
      buy: 'B4 Plus, or the EX40 twin for the school-run silent type.',
      tags: ['boxy-icon', 'city-darling', 'posh-interior', 'school-run', 'head-turner', 'crowd-pleaser'],
      rivals: ['bmw-x1-u11', 'audi-q3-f3', 'range-rover-evoque-l551'] },

    { model: 'XC60', gen: 'P6', years: [2017, 0], bodies: ['suv'], segment: 'family-suv',
      priceNew: [40000, 60000], used: [18000, 48000], accel: 4.8, power: [163, 455], top: 112,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 45, ev: 50, seats: 5, doors: 5, boot: 483, len: 4688, kg: 1830,
      mpy: 10500, ncap: [5, 2017], onSale: true, halo: false,
      g: { build: 88, drive: 68, practicality: 84, value: 76, design: 82, running: 70 },
      verdict: 'Britain’s favourite premium SUV by stealth: serene, gorgeous inside, safe as houses. T8 does 50 miles on volts.',
      issues: ['PHEV price walk', 'Not sporty — by design'],
      buy: 'T8 Recharge Plus Dark — quiet luxury, tax-code friendly.',
      tags: ['posh-interior', 'wafty', 'school-run', 'crowd-pleaser', 'silent-cruiser', 'dog-friendly'],
      rivals: ['bmw-x3-g01', 'audi-q5-fy', 'mercedes-benz-glc-x254'] },

    { model: 'XC90', gen: 'P2', years: [2015, 0], bodies: ['suv'], segment: 'seven-seater',
      priceNew: [50000, 80000], used: [22000, 65000], accel: 5.3, power: [190, 455], top: 112,
      fuels: ['petrol', 'diesel', 'phev'], mpg: 42, ev: 43, seats: 7, doors: 5, boot: 680, len: 4953, kg: 2050,
      mpy: 10500, ncap: [5, 2015], onSale: true, halo: false,
      g: { build: 88, drive: 68, practicality: 92, value: 76, design: 84, running: 60 },
      verdict: 'A decade on sale and still the seven-seat class act — light-filled, elegant, calm. The T8 hauls the tribe on volts.',
      issues: ['Air suspension age on early cars', 'D5 gone — petrol thirst without plug'],
      buy: 'T8 Recharge Plus 7-seat, 2022-on with the bigger battery.',
      tags: ['seven-seats', 'family-bus', 'posh-interior', 'wafty', 'school-run', 'crowd-pleaser', 'dog-friendly'],
      rivals: ['audi-q7-4m', 'bmw-x5-g05', 'kia-ev9-mv'] },

    { model: 'EX30', gen: 'Y1', years: [2023, 0], bodies: ['suv'], segment: 'ev-native',
      priceNew: [33000, 45000], used: [22000, 36000], accel: 3.6, power: [272, 428], top: 112,
      fuels: ['ev'], mpg: null, ev: 296, seats: 5, doors: 5, boot: 318, len: 4233, kg: 1830,
      mpy: 8500, ncap: [5, 2024], onSale: true, halo: false,
      g: { build: 80, drive: 74, practicality: 62, value: 80, design: 86, running: 84 },
      verdict: 'Small, fast, furniture-showroom cool. Everything on the screen annoys; everything else delights. 3.6s for £40k.',
      issues: ['Screen-only controls infuriate', 'Small boot and rear seat'],
      buy: 'Single Motor Extended Range Plus — the sane sweet spot.',
      tags: ['city-darling', 'minimalist', 'head-turner', 'pocket-rocket', 'silent-cruiser'],
      rivals: ['smart-1-hx11', 'kia-ev3-sv', 'mini-countryman-u25'] },

    { model: 'EX90', gen: 'P3', years: [2024, 0], bodies: ['suv'], segment: 'seven-seater',
      priceNew: [82000, 100000], used: [65000, 88000], accel: 4.9, power: [408, 517], top: 112,
      fuels: ['ev'], mpg: null, ev: 374, seats: 7, doors: 5, boot: 655, len: 5037, kg: 2745,
      mpy: 9500, ncap: [5, 2024], onSale: true, halo: true,
      g: { build: 88, drive: 70, practicality: 90, value: 64, design: 84, running: 76 },
      verdict: 'The XC90’s electric heir: seven seats, 374 miles, lidar watching the road. Launch software wobbles now settling.',
      issues: ['Software maturing in public', '2.7 tonnes needs its brakes'],
      buy: 'Twin Motor Plus 7-seat once the updates land — or wait a year used.',
      tags: ['seven-seats', 'family-bus', 'silent-cruiser', 'tech-fest', 'posh-interior'],
      rivals: ['kia-ev9-mv', 'mercedes-benz-eqs-suv-x296', 'bmw-ix-i20'] },

    { model: 'C30', gen: 'P1', years: [2006, 2013], bodies: ['hatch'], segment: 'family-hatch',
      priceNew: [15000, 25000], used: [2500, 7500], accel: 6.2, power: [100, 230], top: 149,
      fuels: ['petrol', 'diesel'], mpg: 47, ev: null, seats: 4, doors: 3, boot: 251, len: 4266, kg: 1347,
      mpy: 8000, ncap: [5, 2009], onSale: false, halo: false,
      g: { build: 80, drive: 68, practicality: 54, value: 76, design: 82, running: 72 },
      verdict: 'The glass-hatch style statement that time forgot. P1800 nods, T5 warble — a design-first used bargain.',
      issues: ['Rear seats strictly two', 'T5 thirst'],
      buy: 'T5 R-Design manual — future-classic Swede for hot-hatch pennies.',
      tags: ['left-field', 'sleek', 'modern-classic', 'head-turner', 'bargain-hero'],
      rivals: ['audi-a3-8p', 'volkswagen-scirocco-mk3', 'mini-hatch-r56'] }
  ]
};
